const {test}=require('node:test'),a=require('node:assert/strict');
const E=require('../src/systems/economy.js'),D=require('../src/data/economy.js'),H=require('../src/data/high-realms.js'),C=require('../src/systems/character.js'),B=require('../src/systems/bag-crafting.js'),L=require('../src/systems/legend-alerts.js');
const p=()=>{const p={realm:8,stones:1e8,inventory:[],equipment:{},ownedTreasures:[],levelPet:{}};E.normalize(p);C.normalize(p);return p;};
test('books migrate into an independent 100-slot category without changing old stacks',()=>{const x=p();x.inventory=[{id:'v21_book_0',count:3},{id:'v21_fragment_1',count:12},{id:'herb',count:9}];const before=JSON.stringify(x.inventory);C.normalize(x);a.equal(x.bag.capacities.books,100);a.equal(Object.keys(C.categories).length,6);a.equal(C.entries(x,'books').length,2);a.equal(C.entries(x,'materials').length,1);a.equal(JSON.stringify(x.inventory),before);for(let i=0;i<100;i++)x.inventory.push({id:'mat_'+i,count:1});a.equal(E.addStack(x,'v21_fragment_2',1),true);a.equal(E.addStack(x,'otherMaterial',1),false);});
test('10 matching fragments make each corresponding book and retain remainder and locks',()=>{const x=p();x.inventory=[{id:'v21_fragment_0',count:27},{id:'v21_fragment_1',count:9},{id:'v21_fragment_2',count:20}];x.bag.locked={v21_fragment_2:true};const quote=B.plan(x,'books');a.equal(quote.cost,0);a.deepEqual(quote.made,[{id:'v21_book_0',count:2}]);a.equal(x.inventory[0].count,27);B.craft(x,'books');a.equal(x.inventory.find(e=>e.id==='v21_fragment_0').count,7);a.equal(x.inventory.find(e=>e.id==='v21_fragment_2').count,20);a.equal(x.inventory.find(e=>e.id==='v21_book_0').count,2);a.equal(B.craft(x,'books').ok,false);});
test('book crafting checks final capacity atomically and allows freeing its own slot',()=>{const x=p();x.bag.capacities.books=1;x.inventory=[{id:'v21_fragment_0',count:11}];let before=JSON.stringify(x);a.equal(B.craft(x,'books').reason,'full');a.equal(JSON.stringify(x),before);x.inventory[0].count=10;a.equal(B.craft(x,'books').ok,true);a.deepEqual(x.inventory,[{id:'v21_book_0',count:1}]);});
test('bulk gems cascade to selectable fourth, fifth and sixth tiers with exact cost',()=>{for(const target of [4,5,6]){const x=p(),n=3**(target-1);E.addStack(x,'gem_fire_1',n);const before=x.stones,quote=B.plan(x,'gems',target);let cost=0;for(let i=1;i<target;i++)cost+=3**(target-i-1)*50*i;a.equal(quote.cost,cost);a.deepEqual(quote.made,[{id:'gem_fire_'+target,count:1}]);a.equal(x.inventory[0].count,n);a.equal(B.craft(x,'gems',target).ok,true);a.deepEqual(x.inventory,[{id:'gem_fire_'+target,count:1}]);a.equal(x.stones,before-cost);}});
test('bulk gems retain higher tiers, locked types, remainders and stop within available funds',()=>{const x=p();x.stones=150;x.inventory=[{id:'gem_fire_3',count:10},{id:'gem_life_3',count:9},{id:'gem_fire_6',count:2}];x.bag.locked={gem_life_3:true};const r=B.craft(x,'gems',4);a.equal(r.cost,150);a.equal(x.stones,0);a.equal(x.inventory.find(e=>e.id==='gem_fire_3').count,7);a.equal(x.inventory.find(e=>e.id==='gem_fire_4').count,1);a.equal(x.inventory.find(e=>e.id==='gem_fire_6').count,2);a.equal(x.inventory.find(e=>e.id==='gem_life_3').count,9);const before=JSON.stringify(x);a.equal(B.craft(x,'gems',7).ok,false);a.equal(JSON.stringify(x),before);});
test('bulk gem final capacity failure does not spend and consumes a freed slot safely',()=>{const x=p();x.bag.capacities.materials=1;x.inventory=[{id:'gem_fire_3',count:4}];const before=JSON.stringify(x);a.equal(B.craft(x,'gems',4).reason,'full');a.equal(JSON.stringify(x),before);x.inventory[0].count=3;a.equal(B.craft(x,'gems',4).ok,true);a.equal(x.inventory[0].id,'gem_fire_4');});
test('monsters and dark cultivators drop persistent typed fragments once and overflow safely',()=>{for(const enemy of [{realm:4},{dark:true,darkRealm:3},{role:'cultivator',realm:8},{role:'boss',realm:8}]){const x=p();x.bag.capacities.books=1;x.inventory=[{id:'v21_book_29',count:1}];const r=B.reward(x,enemy,()=>0);a.equal(r.id,'v21_fragment_0');a.equal(r.count,1);a.deepEqual(x.economy.mail[0],{id:r.id,count:1,source:'技能殘卷掉落'});const before=JSON.stringify(x);a.equal(B.reward(x,enemy,()=>0).ok,false);a.equal(JSON.stringify(x),before);x.inventory=[];a.equal(E.recover(x),1);a.equal(x.inventory[0].id,r.id);}});
test('non-legend mailbox treasure can be claimed or directly equipped with full category; displaced item survives reload',()=>{H.install([],D,{});const x=p(),old=E.create(x,'v21_treasure_0',2,'old',()=>.5);E.grant(x,old);x.activeTreasure=old.id;x.economy.loadout.treasures[0]=old.id;x.bag.capacities.treasures=1;const next=E.create(x,'v21_treasure_1',2,'new',()=>.5);a.equal(E.grant(x,next),false);a.equal(E.recover(x),0);a.equal(L.equip(x,next.id).ok,true);a.equal(x.activeTreasure,next.id);a.equal(x.economy.loadout.treasures[0],next.id);a.deepEqual(x.ownedTreasures,[next.id]);a.equal(x.economy.mail[0].id,old.id);let copy=JSON.parse(JSON.stringify(x));E.normalize(copy);copy.bag.capacities.treasures=2;a.equal(E.recover(copy),1);a.equal(copy.ownedTreasures.includes(old.id),true);a.equal(copy.economy.mail.length,0);});
test('mailbox realm failure is unchanged; a stale held receipt is removed even when full',()=>{const x=p(),it=E.create(x,'gear_weapon_0',2,'test',()=>.5);E.grant(x,it);x.bag.capacities.equipment=1;x.economy.mail.push(it.id);a.equal(E.recover(x),1);a.equal(x.inventory.length,1);const item=E.create(x,'gear_weapon_0',2,'test',()=>.5);item.realm=8;E.grant(x,item);x.realm=0;const before=JSON.stringify(x);a.equal(L.equip(x,item.id).reason,'realm');a.equal(JSON.stringify(x),before);});

test('displaced legacy treasure can be directly selected from mailbox without losing next item',()=>{const x=p();x.bag.capacities.treasures=1;const next=E.create(x,'treasure_0',2,'test',()=>.5);E.grant(x,next);x.activeTreasure=next.id;x.economy.mail.push({id:'mirror',companion:'treasure',level:1,count:1});a.equal(L.equip(x,'mirror',{mirror:{id:'mirror',name:'昊天靈鏡',realm:0,rarity:1}}).ok,true);a.equal(x.activeTreasure,'mirror');a.deepEqual(x.ownedTreasures,['mirror']);a.equal(x.economy.mail[0].id,next.id);a.equal(x.economy.instances[next.id].quality,2);});
test('insufficient lower gems do not create unwanted intermediate tiers',()=>{const x=p();x.inventory=[{id:'gem_fire_1',count:242}];const before=JSON.stringify(x);a.equal(B.craft(x,'gems',6).ok,false);a.equal(JSON.stringify(x),before);});
