const {test}=require('node:test'),a=require('node:assert/strict'),E=require('../src/systems/economy.js');
function fixture(q=0){const p={stones:1e8,inventory:[],equipment:{},ownedTreasures:[],levelPet:{}};E.normalize(p);const it=E.create(p,'gear_weapon_0',q,'test',()=>.5);E.grant(p,it);E.addStack(p,'forgeDust',1000);E.addStack(p,'celestialOre',1000);return {p,it};}
test('bulk reaches cap using evolving costs and preserves equipment across reload',()=>{const {p,it}=fixture();p.inventory=p.inventory.filter(e=>e.id!==it.id);p.equipment.weapon=it.id;let money=0,dust=0;for(let n=0;n<10;n++){const c=E.forgeCost({...it,enhancement:n});money+=c.stones;dust+=c.material;}const r=E.enhanceMax(p,it.id,()=>0);a.equal(r.after,10);a.equal(r.reason,'cap');a.equal(r.successes,10);a.equal(r.spent.stones,money);a.equal(r.spent.material,dust);a.equal(JSON.parse(JSON.stringify(p)).equipment.weapon,it.id);const before=JSON.stringify(p);a.equal(E.enhanceMax(p,it.id).ok,false);a.equal(JSON.stringify(p),before);});
test('failures consume exact resources and insufficient next attempt never partially charges',()=>{const {p,it}=fixture();it.enhancement=8;p.stones=E.forgeCost(it).stones*2;const r=E.enhanceMax(p,it.id,()=>.999);a.equal(r.failures,2);a.equal(r.after,8);a.equal(r.reason,'funds');a.equal(p.stones,0);});
test('selected gem exhaustion stops without falling back to unboosted attempts',()=>{const {p,it}=fixture(4);it.enhancement=29;E.addStack(p,'gem_fire_6',2);const r=E.enhanceMax(p,it.id,()=>0,'gem_fire_6');a.equal(r.attempts,2);a.equal(r.after,31);a.equal(r.reason,'gem');a.equal(r.spent.gems,2);a.equal(r.unlocked.length,1);a.equal(it.forgeAffixes.length,1);a.equal(p.economy.forgeLog.length,2);});
test('missing ore or invalid random does not charge and invalid item is rejected',()=>{const {p,it}=fixture(2);p.inventory=p.inventory.filter(e=>e.id!=='celestialOre');const before=JSON.stringify(p);a.equal(E.enhanceMax(p,it.id).ok,false);a.equal(JSON.stringify(p),before);E.addStack(p,'celestialOre',100);const saved=JSON.stringify(p);a.equal(E.enhanceMax(p,it.id,()=>NaN).reason,'random');a.equal(JSON.stringify(p),saved);a.equal(E.enhanceMax(p,'missing').ok,false);});

test('target estimate matches actual all-success cost and target stops before resource cap',()=>{const {p,it}=fixture(4);const before=JSON.stringify(p),quote=E.forgeEstimate(it,50);a.equal(JSON.stringify(p),before);a.equal(quote.minimum.attempts,50);a.ok(quote.expected.stones>quote.minimum.stones);const r=E.enhanceMax(p,it.id,()=>0,null,50);a.equal(r.after,50);a.equal(r.reason,'targetReached');for(const k of ['stones','material','ore','gems'])a.equal(r.spent[k],quote.minimum[k]);a.ok(p.stones>0);});
test('invalid targets never consume; gemstone boost updates expected estimate',()=>{const {p,it}=fixture(2);for(const n of [0,-1,51,1.5,NaN,Infinity]){const before=JSON.stringify(p);a.equal(E.forgeEstimate(it,n).ok,false);a.equal(E.enhanceMax(p,it.id,()=>0,null,n).ok,false);a.equal(JSON.stringify(p),before);}const plain=E.forgeEstimate(it,50),boost=E.forgeEstimate(it,50,'gem_fire_6');a.ok(boost.expected.stones<plain.expected.stones);a.equal(boost.minimum.gems,50);a.equal(boost.minimum.stones,plain.minimum.stones);});
