const {test}=require('node:test'),a=require('node:assert/strict'),E=require('../src/systems/economy.js'),M=require('../src/systems/companion-merge.js');
const player=()=>{const p={realm:8,stones:100,inventory:[],equipment:{},ownedTreasures:[],levelPet:{},companions:{order:[],deployed:[],cooldowns:{},cursor:0}};E.normalize(p);return p;};
function make(p,type,n,q=2){return Array.from({length:n},()=>{const it=E.create(p,type+'_0',q,'test',()=>.5);E.grant(p,it);it.sockets.fill(null);return it;});}
test('nine identical first-level treasures merge into one ninth-level instance without currency cost',()=>{const p=player(),items=make(p,'treasure',9),before=p.stones;const quote=M.preview(p,'treasure');a.equal(quote.count,8);a.equal(quote.groups[0].after,9);a.equal(p.ownedTreasures.length,9);const r=M.merge(p,'treasure');a.equal(r.ok,true);a.equal(p.ownedTreasures.length,1);a.equal(p.economy.instances[p.ownedTreasures[0]].fusionLevel,9);a.equal(p.stones,before);for(const it of items.filter(it=>it.id!==p.ownedTreasures[0]))a.equal(it.mergedInto,p.ownedTreasures[0]);a.equal(M.merge(p,'treasure').ok,false);});
test('two identical pets merge to level two; later merges add accumulated levels',()=>{const p=player(),items=make(p,'pet',2);M.merge(p,'pet');const id=Object.keys(p.levelPet)[0];a.equal(p.levelPet[id],2);make(p,'pet',1);M.merge(p,'pet');a.equal(Object.keys(p.levelPet).length,1);a.equal(p.levelPet[id],3);a.equal(p.economy.instances[id].level,3);});
test('main instance and modified attributes survive; deployment loadout and cooldowns consolidate',()=>{const p=player(),items=make(p,'treasure',3),main=items[2];p.activeTreasure=main.id;main.enhancement=12;main.sockets=['gem_fire_4'];const affixes=JSON.stringify(main.affixes);p.economy.loadout.treasures=[items[0].id,main.id,items[1].id,null,null,null];p.companions.order=items.map(it=>'treasure:'+it.id);p.companions.deployed=p.companions.order.slice();p.companions.cooldowns={'treasure:xi_1':100,'treasure:xi_3':50};M.merge(p,'treasure');a.equal(p.activeTreasure,main.id);a.equal(main.enhancement,12);a.deepEqual(main.sockets,['gem_fire_4']);a.equal(JSON.stringify(main.affixes),affixes);a.deepEqual(p.companions.order,['treasure:'+main.id]);a.deepEqual(p.companions.deployed,p.companions.order);a.equal(p.companions.cooldowns['treasure:'+main.id],100);a.equal(p.economy.loadout.treasures.filter(Boolean).length,1);});
test('locked, socketed and cultivated donor items remain; different qualities and templates do not mix',()=>{const p=player(),items=make(p,'pet',6);items[0].locked=true;items[1].sockets=['gem_fire_4'];items[2].cultivation=1;p.activePet=items[3].id;const gold=make(p,'pet',1,3)[0],other=E.create(p,'pet_1',2,'test',()=>.5);E.grant(p,other);const r=M.merge(p,'pet');a.equal(r.count,2);for(const it of [items[0],items[1],items[2],gold,other])a.equal(p.levelPet[it.id],1);a.equal(p.levelPet[items[3].id],3);});
test('fusion levels increase treasure stats without changing base, affixes or forge scaling',()=>{const p=player(),it=make(p,'treasure',2)[0],base=structuredClone(it.base),old=E.effects(it);p.activeTreasure=it.id;M.merge(p,'treasure');a.deepEqual(it.base,base);a.equal(E.effects(it).atk,old.atk*1.05);a.equal(E.effects(it).def,old.def*1.05);});
test('merging frees full companion bag capacity and lets mailbox recover the saved item',()=>{const p=player();p.bag={capacities:{treasures:2}};make(p,'treasure',2);const mail=E.create(p,'treasure_1',2,'mail',()=>.5);a.equal(E.grant(p,mail),false);a.equal(E.recover(p),0);M.merge(p,'treasure');a.equal(E.recover(p),1);a.equal(p.ownedTreasures.length,2);a.equal(p.ownedTreasures.includes(mail.id),true);});
test('reload preserves merged levels and prevents consuming retired instances again',()=>{const p=player();make(p,'treasure',3);M.merge(p,'treasure');const copy=JSON.parse(JSON.stringify(p));E.normalize(copy);const id=copy.ownedTreasures[0];a.equal(copy.economy.instances[id].fusionLevel,3);a.equal(M.preview(copy,'treasure').ok,false);make(copy,'treasure',1);a.equal(M.merge(copy,'treasure').groups[0].after,4);});
test('different realms stay separate and invalid categories never mutate the save',()=>{const p=player(),items=make(p,'treasure',2);items[1].realm++;const before=JSON.stringify(p);a.equal(M.merge(p,'treasure').ok,false);a.equal(M.merge(p,'equip').ok,false);a.equal(JSON.stringify(p),before);});

test('consumed companion cannot be resurrected by a stale mailbox receipt',()=>{const p=player(),items=make(p,'treasure',2);p.activeTreasure=items[0].id;p.economy.mail.push(items[1].id);M.merge(p,'treasure');a.equal(p.economy.mail.length,0);a.equal(E.grant(p,items[1]),false);p.economy.mail.push(items[1].id);a.equal(E.recover(p),0);a.equal(p.economy.mail.length,0);a.equal(p.ownedTreasures.length,1);});
