const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),{test}=require('node:test');
const source=fs.readFileSync('tests/rift-integration.test.cjs','utf8'),body=source.slice(source.indexOf('function harness()'),source.indexOf("test('real damage"));
const baseHarness=new Function('fs','vm',body+';return harness;')(fs,vm);
function harness(){const h=baseHarness();h.c.Math=Object.create(Math);h.c.Math.random=()=>0;for(const f of ['src/data/economy.js','src/systems/economy.js'])vm.runInContext(fs.readFileSync(f,'utf8'),h.c);h.run('Economy.normalize(p);function economyHydrate(){}function characterQuality(q){return String(q)}function economyAsset(){return ""}');vm.runInContext(fs.readFileSync('src/ui/economy-drops.js','utf8'),h.c);return h;}
test('actual ten-wave boss kill awards once and persists stable receipts across callbacks and reload',()=>{const h=harness();h.run('beginRift(0)');assert.match(h.run('p.rift.runId'),/^rift:ember:/);for(let w=1;w<=10;w++){h.run('[...enemies].forEach(e=>hurtEnemy(e,10000000));stepEncounters(.01)');if(w<10)h.run('stepEncounters(3.1)');}assert.equal(h.run('p.economy.drops.length'),1);assert.equal(h.run('p.economy.drops[0].rewards.length'),2);const saved=JSON.parse(h.saved.get('TAIXU_ASCEND_V2_SAVE'));assert.equal(Object.keys(saved.economy.claims).length,1);assert.equal(saved.economy.worlds.ember.boss,'defeated');const before=h.run('p.economy.sequence');h.run('finishRift(true);Economy.reward(p,"rift:ember:1:boss","boss","normal",()=>0)');assert.equal(h.run('p.economy.sequence'),before);});
test('quest and ancient landmark complete once and award independently of normal quest proceeds',()=>{const h=harness();h.run('p.encounters.pending={id:3,kind:"quest",index:0,expiresAt:Date.now()+30000};Encounters.accept(p);p.killCount=12');assert.equal(h.run('Encounters.claim(p,3,()=>true)'),true);assert.equal(h.run('p.economy.drops[0].level'),'ordinary');assert.equal(h.run('p.economy.drops[0].rewards.length'),1);assert.equal(h.run('Encounters.claim(p,3,()=>true)'),false);h.run('p.exploration={claimed:{},cooldowns:{}}');assert.equal(h.run('Progression.collectLandmark(p,0,Progression.landmarks[3],stats()).ok'),true);assert.equal(h.run('Progression.collectLandmark(p,0,Progression.landmarks[3],stats()).ok'),false);assert.equal(h.run('p.economy.drops.length'),2);});
test('world requirements reject entry without consuming encounter or moving character',()=>{const h=harness(),pos=h.run('JSON.stringify(p.position)');h.run('beginRift(4)');assert.equal(h.run('riftRunning'),false);assert.equal(h.run('JSON.stringify(p.position)'),pos);assert.equal(h.run('p.rift'),undefined);});
function combatHarness(){const h=harness();vm.runInContext(fs.readFileSync('src/systems/economy-combat.js','utf8'),h.c);h.run('function fireCompanion(){return false};p.hp=50;');vm.runInContext(fs.readFileSync('src/ui/economy-combat.js','utf8'),h.c);return h;}
test('real hurtEnemy path applies damage, splash, ice slow and lifesteal without recursive splashes',()=>{const h=combatHarness();h.run('const item=Economy.create(p,"gear_weapon_0",4,"test",()=>.5);item.affixes=[];item.sockets=["gem_fire_1","gem_blast_1","gem_blood_1","gem_frost_1",null,null];p.equipment.weapon=item.id;enemies=Array.from({length:6},(_,i)=>({x:100+i*10,y:100,hp:1000,maxHp:1000,def:0}));Math.random=()=>.99;hurtEnemy(enemies[0],100)');assert.ok(h.run('enemies[0].hp')<900);assert.equal(h.run('enemies.filter(e=>e.hp<1000).length'),4);assert.ok(h.run('p.hp')>50);assert.ok(h.run('enemies[0].slowUntil')>Date.now()-100);const count=h.run('enemies[1].hp');h.run('hurtEnemy(enemies[0],100)');assert.equal(h.run('enemies[1].hp'),count);});
test('existing cast cooldown receives bounded reduction and recovery has one loop hook',()=>{const h=combatHarness();h.run('const it=Economy.create(p,"gear_weapon_0",4,"test",()=>.5);it.affixes=[{key:"cooldown",name:"test",value:1}];it.sockets=[];p.equipment.weapon=it.id;enemies=[{x:p.position.x+50,y:p.position.y,hp:10000,maxHp:10000,def:0}];cast(0)');assert.equal(h.run('cd[0]'),360);const source=fs.readFileSync('src/game.js','utf8');assert.equal((source.match(/stepEconomy\(dt,modalOpen\)/g)||[]).length,1);});
