const {test}=require('node:test'),assert=require('node:assert/strict');
const D=require('../src/data/economy.js'),E=require('../src/systems/economy.js');
const player=()=>({version:2,realm:4,stage:2,qi:55,hp:100,mp:75,stones:1000000,jade:12,inventory:[],equipment:{weapon:'sword'},levelPet:{fox:2},ownedTreasures:['mirror'],activePet:'fox',activeTreasure:'mirror',auto:true,autoMeditate:true,position:{x:123,y:456}});
function seeded(seed){return ()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};}
test('120 gear, 12 treasures, 12 pets, 72 gems have distinct asset IDs and slots',()=>{for(const [type,n]of [['equip',120],['treasure',12],['pet',12],['gem',72]])assert.equal(Object.values(D.templates).filter(t=>t.type===type).length,n);assert.equal(new Set(Object.values(D.templates).map(t=>t.assetId)).size,216);for(const slot of Object.keys(D.slots))assert.equal(Object.values(D.templates).filter(t=>t.slot===slot).length,10);});
test('additive migration is repeatable and preserves inventory, unknown fields and automation',()=>{const p=player();p.future={keep:1};p.inventory=[{id:'unknown',count:7},{id:'sword',count:3}];const before=structuredClone(p);E.normalize(p);const once=JSON.stringify(p);E.normalize(p);assert.equal(JSON.stringify(p),once);for(const k of ['inventory','future','auto','autoMeditate','position','qi'])assert.deepEqual(p[k],before[k]);assert.equal(p.version,2);assert.equal(p.economy.loadout.pets.length,6);});
test('all five quality ranges generate distinct persistent instances and requirement/source metadata',()=>{const p=player(),r=seeded(123);for(let q=0;q<5;q++)for(let n=0;n<100;n++){const it=E.create(p,'gear_weapon_0',q,'test',r),rule=D.qualities[q];assert.ok(it.affixes.length>=rule.affixes[0]&&it.affixes.length<=rule.affixes[1]);assert.ok(it.sockets.length>=rule.holes[0]&&it.sockets.length<=rule.holes[1]);assert.equal(it.source,'test');assert.ok(it.base.atk>=12);assert.equal(p.economy.instances[it.id],it);}assert.equal(Object.keys(p.economy.instances).length,500);assert.deepEqual(JSON.parse(JSON.stringify(p)).economy,p.economy);});
test('shop rejects gold, legendary and fifth/sixth gems before charging or changing ownership',()=>{const p=player();E.normalize(p);for(const id of ['gear_weapon_0','pet_0','treasure_0'])for(const q of [3,4]){const before=JSON.stringify(p);assert.equal(E.buy(p,id,q).ok,false);assert.equal(JSON.stringify(p),before);}for(const id of ['gem_fire_5','gem_life_6'])assert.equal(E.buy(p,id,0).ok,false);assert.equal(E.buy(p,'gem_fire_4',0).ok,true);assert.equal(E.buy(p,'gear_weapon_0',2,seeded(7)).ok,true);});
test('enhancement failure retains item, sockets replace atomically and reload retains state',()=>{const p=player(),it=E.create(p,'gear_weapon_0',4,'test',seeded(9));E.grant(p,it);E.addStack(p,'forgeDust',100);E.addStack(p,'celestialOre',100);it.enhancement=14;assert.equal(E.enhance(p,it.id,()=>.99).success,false);assert.equal(it.enhancement,14);assert.ok(p.inventory.some(x=>x.id===it.id));assert.equal(E.enhance(p,it.id,()=>0).success,true);assert.equal(it.enhancement,15);E.addStack(p,'gem_wisdom_6',2);assert.equal(E.socket(p,it.id,0,'gem_wisdom_6'),true);assert.equal(E.socket(p,it.id,1,'gem_wisdom_6'),true);p.equipment.weapon=it.id;assert.equal(E.bonuses(p).qi,3);assert.equal(E.socket(p,it.id,0,null),true);assert.equal(p.inventory.find(x=>x.id==='gem_wisdom_6').count,1);const reloaded=JSON.parse(JSON.stringify(p));E.normalize(reloaded);assert.equal(reloaded.economy.instances[it.id].enhancement,15);assert.equal(reloaded.economy.instances[it.id].sockets[1],'gem_wisdom_6');});
test('one encounter roll totals 4/5/6 percent; independent boss rates converge with fixed seed',()=>{const N=200000;for(const [kind,prob]of Object.entries(D.config.encounters)){const r=seeded(12),n=[0,0];for(let i=0;i<N;i++){const q=E.encounterQuality(kind,r);if(q!==null)n[0]++;if(q===4)n[1]++;}assert.ok(Math.abs(n[0]/N-prob)<.002);assert.ok(Math.abs(n[1]/N-prob*.05)<.0005);}for(const [kind,probs]of Object.entries(D.config.boss)){const r=seeded(42),n=[0,0];for(let i=0;i<N;i++){const q=E.bossQualities(kind,r);n[0]+=q.includes(3);n[1]+=q.includes(4);}assert.ok(Math.abs(n[0]/N-probs.gold)<.002);assert.ok(Math.abs(n[1]/N-probs.legendary)<.001);}});
test('reward claim and full-bag mailbox survive reload and prevent duplicate callbacks',()=>{const p=player();E.normalize(p);p.bag={capacities:{equipment:1,pets:1,treasures:1}};p.inventory=[{id:'sword',count:1}];const r=()=>0;assert.equal(E.reward(p,'boss:run1','boss','ancient',r).ok,true);assert.equal(p.economy.drops.length,1);const copy=JSON.parse(JSON.stringify(p)),before=JSON.stringify(copy);assert.equal(E.reward(copy,'boss:run1','boss','ancient',r).ok,false);assert.equal(JSON.stringify(copy),before);assert.equal(copy.economy.mail.length,2);copy.inventory=[];copy.bag.capacities.equipment=100;assert.equal(E.recover(copy),2);assert.equal(copy.inventory.filter(x=>x.id.startsWith('xi_')).length,2);});
test('gem fusion consumes exactly three, checks currency and capacity, legends require three gold',()=>{const p=player();E.normalize(p);E.addStack(p,'gem_life_4',3);assert.equal(E.fuse(p,'gem_life_4'),true);assert.equal(p.inventory.find(x=>x.id==='gem_life_5').count,1);assert.equal(E.fuse(p,'gem_life_6'),false);const ids=Array.from({length:3},()=>{const it=E.create(p,'gear_weapon_0',3,'test',seeded(4));E.grant(p,it);return it.id;});assert.equal(E.synthesize(p,ids,seeded(1)).quality,4);assert.equal(E.synthesize(p,ids,seeded(1)),false);});
module.exports={player,seeded};
test('world bosses use their exclusive item and gem pools even when both high rolls hit',()=>{for(const world of D.config.worlds){const p=player(),r=seeded(75);for(let i=0;i<100;i++){let calls=0;E.reward(p,'world:'+i,'boss',world.boss,()=>++calls<=2?0:r(),world.id);}for(const drop of p.economy.drops)for(const id of drop.rewards){const item=p.economy.instances[id],t=D.templates[item.baseId],pool=world.dropPool;assert.ok(t.type==='equip'?pool.slots.includes(t.slot):pool[t.type==='pet'?'pets':'treasures'].includes(Number(t.id.split('_')[1])));}for(const entry of p.inventory.filter(x=>x.id.startsWith('gem_')))assert.ok(world.dropPool.gems.includes(D.templates[entry.id].kind));}});
test('legacy single-copy conversion preserves stats and never shares enhancement across a stack',()=>{const p=player();E.normalize(p);p.inventory=[{id:'sword',count:3},{id:'forgeDust',count:20}];const catalog={sword:{id:'sword',name:'原劍',type:'equip',slot:'weapon',atk:13,rarity:1,price:60}};const equipped=E.convertLegacy(p,'sword',catalog);assert.equal(p.equipment.weapon,equipped.id);assert.equal(p.inventory.find(x=>x.id==='sword').count,3);assert.equal(equipped.base.atk,13);assert.equal(E.enhance(p,equipped.id,()=>0).success,true);const bag=E.convertLegacy(p,'sword',catalog);assert.notEqual(bag.id,equipped.id);assert.equal(p.inventory.find(x=>x.id==='sword').count,2);assert.equal(bag.enhancement,0);assert.equal(equipped.enhancement,1);const copy=JSON.parse(JSON.stringify(p));E.normalize(copy);assert.equal(copy.economy.instances[equipped.id].enhancement,1);assert.equal(copy.economy.instances[bag.id].template.name,'原劍');});
test('legacy treasure conversion retains its independent cooldown and loadout position',()=>{const p=player();E.normalize(p);p.companions={order:['treasure:mirror'],deployed:['treasure:mirror'],cooldowns:{'treasure:mirror':999999}};p.economy.loadout.treasures[0]='mirror';const it=E.convertLegacy(p,'mirror',{mirror:{id:'mirror',type:'treasure',name:'原鏡',atk:3,def:8,rarity:1}});assert.equal(p.activeTreasure,it.id);assert.equal(p.ownedTreasures[0],it.id);assert.equal(p.companions.cooldowns['treasure:'+it.id],999999);assert.equal(p.economy.loadout.treasures[0],it.id);});
