const {test}=require('node:test'),assert=require('node:assert/strict');
const E=require('../src/systems/encounters.js'),P=require('../src/systems/progression.js');
const player=()=>({version:2,levelPet:{fox:1},equipment:{},inventory:[{id:'herb',count:15}],herbs:15,materialsInBag:true,killCount:50,stones:0,jade:0,position:{x:460,y:355},custom:'keep'});
test('encounters use active exploration time and never overwrite a pending event',()=>{const p=player();E.normalize(p);assert.equal(E.advance(p,29,()=>.1),false);assert.equal(E.advance(p,1,()=>.1),true);const pending=p.encounters.pending;assert.equal(pending.kind,'rift');E.advance(p,1000);assert.equal(p.encounters.pending,pending);assert.equal(p.custom,'keep');});
test('kill quests count only kills after acceptance; claim is single use',()=>{const p=player();E.normalize(p);p.encounters.pending={id:1,kind:'quest',index:0};assert.ok(E.accept(p));const q=p.encounters.quests[0];assert.equal(E.progress(p,q),0);assert.equal(E.claim(p,1,()=>true),false);p.killCount+=12;assert.ok(E.claim(p,1,()=>true));assert.equal(p.stones,130);assert.equal(p.jade,1);assert.equal(E.claim(p,1,()=>true),false);});
test('collection quests atomically consume bag materials and synchronize alchemy stock',()=>{const p=P.normalize(player());E.normalize(p);p.encounters.pending={id:2,kind:'quest',index:1};E.accept(p);assert.ok(E.claim(p,2,(id,n)=>P.takeItem(p,id,n)));assert.equal(p.herbs,0);assert.equal(p.inventory.some(i=>i.id==='herb'),false);assert.equal(p.stones,160);});
test('full quest log leaves the encounter available and failed collection never pays',()=>{const p=player();E.normalize(p);for(let i=0;i<3;i++){p.encounters.pending={id:i,kind:'quest',index:1};E.accept(p)}p.encounters.pending={id:4,kind:'quest',index:0};assert.equal(E.accept(p),false);assert.equal(p.encounters.pending.id,4);assert.equal(E.claim(p,0,()=>false),false);assert.equal(p.stones,0);assert.equal(p.encounters.quests.length,3);});
test('all five realms scale ten waves, add elites from wave five and a 1.5-power boss',()=>{const base={atk:100,def:20,combat:400};for(let t=0;t<5;t++){let previous=0;for(let w=1;w<=10;w++){const enemies=E.wave(t,w,base);const regular=enemies.find(e=>!e.boss);assert.ok(regular.maxHp>previous);previous=regular.maxHp;if(w<5)assert.equal(enemies.filter(e=>e.elite).length,0);if(w>=5&&w<10)assert.equal(enemies.filter(e=>e.elite).length,w-3);if(w===10){const boss=enemies.find(e=>e.boss);assert.equal(boss.atk,600);assert.ok(boss.maxHp>regular.maxHp);}}}});
test('boss transforms once strictly below 20%, never heals or resurrects',()=>{const e=E.wave(0,10,{atk:100,def:20,combat:400})[0];e.hp=e.maxHp*.2;assert.equal(E.transform(e),false);e.hp--;const hp=e.hp;assert.ok(E.transform(e));assert.equal(e.hp,hp);assert.equal(e.atk,810);assert.equal(E.transform(e),false);e.hp=0;assert.equal(E.transform(e),false);});
