const {test}=require('node:test'),assert=require('node:assert/strict'),E=require('../src/systems/economy.js'),D=require('../src/systems/dismantle.js');
function fixture(q=0){const p={stones:1e9,inventory:[],equipment:{},ownedTreasures:[],levelPet:{},future:{keep:1}};E.normalize(p);const it=E.create(p,'gear_weapon_0',q,'test',()=>.5);E.grant(p,it);E.addStack(p,'forgeDust',10000);E.addStack(p,'celestialOre',10000);return {p,it};}
test('all five forging caps permit final upgrade then stop without charging, including worn equipment',()=>{for(const [q,cap]of [10,30,50,80,200].entries()){const {p,it}=fixture(q);assert.equal(E.forgeCap(it),cap);it.enhancement=cap-1;p.inventory=p.inventory.filter(e=>e.id!==it.id);p.equipment.weapon=it.id;assert.equal(E.enhance(p,it.id,()=>0).success,true);assert.equal(it.enhancement,cap);const before=JSON.stringify(p);assert.equal(E.enhance(p,it.id,()=>0).ok,false);assert.equal(JSON.stringify(p),before);assert.equal(JSON.parse(JSON.stringify(p)).economy.instances[it.id].enhancement,cap);}});
test('ore requirements scale by quality/level and missing ore never partly consumes funds or stones',()=>{for(let q=0;q<5;q++){const {p,it}=fixture(q),start=E.forgeCost(it).ore;it.enhancement=20;assert.equal(q<2?E.forgeCost(it).ore===0:E.forgeCost(it).ore>start,true);}const {p,it}=fixture(2);p.inventory=p.inventory.filter(e=>e.id!=='celestialOre');const before=JSON.stringify(p);assert.equal(E.enhance(p,it.id,()=>0).ok,false);assert.equal(JSON.stringify(p),before);});
test('old over-cap white enhancement is retained; failed forging preserves item and charges exact costs',()=>{const {p,it}=fixture(0);it.enhancement=15;assert.equal(E.enhance(p,it.id,()=>0).ok,false);assert.equal(it.enhancement,15);const f=fixture(4);f.it.enhancement=100;const cost=E.forgeCost(f.it),money=f.p.stones;assert.equal(E.enhance(f.p,f.it.id,()=>.99).success,false);assert.equal(f.it.enhancement,100);assert.equal(f.p.stones,money-cost.stones);assert.equal(f.p.inventory.find(e=>e.id==='celestialOre').count,10000-cost.ore);const snapshot=JSON.stringify(f.p);assert.equal(E.enhance(f.p,f.it.id,()=>NaN).ok,false);assert.equal(JSON.stringify(f.p),snapshot);});
test('dismantle returns forge stones, grade-appropriate bonus gems and all socket gems, once only',()=>{for(let q=0;q<5;q++){const {p,it}=fixture(q);it.sockets=['gem_fire_6'];const r=D.attempt(p,it.id,()=>0);assert.equal(r.ok,true);assert.equal(r.bonus,q>=2);assert.equal(r.rewards[0].count,D.config.stoneYield[q]);assert.ok(r.rewards.some(e=>e.id==='gem_fire_6'&&e.count===1));if(q>=2){const bonus=r.rewards[1];assert.equal(Number(bonus.id.split('_').at(-1)),D.config.gemTiers[q][0]);assert.equal(bonus.count,D.config.gemCounts[q][0]);}assert.equal(E.held(p,it.id),false);assert.equal(D.attempt(p,it.id,()=>0).ok,false);assert.deepEqual(p.future,{keep:1});}});
test('locked dismantle rejected; worn gear unmounts; full materials preserve all rewards in mailbox and across reload',()=>{const {p,it}=fixture(4);it.locked=true;const before=JSON.stringify(p);assert.equal(D.attempt(p,it.id,()=>0).ok,false);assert.equal(JSON.stringify(p),before);it.locked=false;p.inventory=p.inventory.filter(e=>e.id!==it.id&&e.id!=='forgeDust');p.equipment.weapon=it.id;p.bag={capacities:{materials:1}};const r=D.attempt(p,it.id,()=>0);assert.equal(r.ok,true);assert.equal(p.equipment.weapon,null);assert.equal(p.economy.mail.length,2);const saved=JSON.parse(JSON.stringify(p));assert.equal(saved.economy.mail[0].id,'forgeDust');assert.equal(D.attempt(saved,it.id,()=>0).ok,false);});

test('bulk dismantle multi-select keeps locked and worn items, handles stacks and recovers each selected copy once',()=>{const {p,it}=fixture(2),catalog={};it.locked=true;const other=E.create(p,'gear_head_0',1,'test',()=>.5);E.grant(p,other);p.inventory.find(e=>e.id===other.id).count=3;const worn=E.create(p,'gear_robe_0',0,'test',()=>.5);p.equipment.robe=worn.id;p.inventory.push({id:'sword',count:2});catalog.sword={id:'sword',name:'舊劍',type:'equip',slot:'weapon',rarity:1,atk:10};assert.equal(D.previewBulk(p,[0,1,2],catalog).count,5);const r=D.bulk(p,[0,1,2],catalog,()=>.99);assert.equal(r.count,5);assert.equal(r.rewards.find(e=>e.id==='forgeDust').count,25);assert.equal(E.held(p,it.id),true);assert.equal(p.equipment.robe,worn.id);assert.equal(p.inventory.some(e=>e.id===other.id||e.id==='sword'),false);assert.equal(D.bulk(p,[0,1,2],catalog,()=>0).ok,false);});
test('bulk dismantle rolls back entire batch if random validation fails and ignores unchecked grades',()=>{const {p,it}=fixture(2);assert.equal(D.previewBulk(p,[0,1],{}).count,0);const before=JSON.stringify(p);assert.equal(D.bulk(p,[2],{},()=>NaN).ok,false);assert.equal(JSON.stringify(p),before);assert.equal(D.bulk(p,[],{}).ok,false);});
