const {test}=require('node:test'),a=require('node:assert/strict'),D=require('../src/data/high-realms.js'),ED=require('../src/data/economy.js'),E=require('../src/systems/economy.js'),M=require('../src/systems/forgemaster.js');D.install([],ED,{});
function fixture(theme='cloud'){const npc=D.npcs.find(n=>n.theme===theme&&n.role.includes('鍛造')),map=D.maps.find(m=>m.theme===theme),p={realm:8,finished:true,mapIndex:5+D.maps.indexOf(map),position:{x:npc.x,y:npc.y},stones:1e8,inventory:[{id:'forgeDust',count:10000},{id:'celestialOre',count:10000}],equipment:{},ownedTreasures:[],levelPet:{}};E.normalize(p);const item=E.create(p,'gear_weapon_0',4,'test',()=>.5);E.grant(p,item);item.enhancement=99;return {p,npc,map,item};}
test('map smith recipes discount 50–70 percent and improve both crafting and enhancement rates',()=>{for(const theme of ['cloud','palace','ascend']){const {p,npc,map,item}=fixture(theme),q=M.quote(p,npc.id,map,item.id);a.equal(q.ok,true);a.ok(q.service.discount>=.5&&q.service.discount<=.7);for(const k of ['stones','material','ore'])a.equal(q.cost[k],Math.ceil(q.original[k]*(1-q.service.discount)-1e-9));a.ok(q.cost.chance>q.original.chance);a.ok(q.cost.chance<=1);const craft=M.craftQuote(p,npc.id,map,'gear_weapon_0');a.equal(craft.cost.stones,Math.round(craft.original.stones*(1-q.service.discount)));}});
test('smith enhancement charges the displayed discount and preserves item on failure',()=>{const {p,npc,map,item}=fixture(),q=M.quote(p,npc.id,map,item.id),before=p.stones,level=item.enhancement;const r=M.upgrade(p,npc.id,map,item.id,()=>.999);a.equal(r.success,false);a.equal(item.enhancement,level);a.equal(p.stones,before-q.cost.stones);a.deepEqual(E.forgeCost(item),q.original);const normal=E.forgeCost(item),stones=p.stones;E.enhance(p,item.id,()=>0);a.equal(p.stones,stones-normal.stones);});
test('legendary equipment and treasures are crafted independently and overflow survives reload',()=>{for(const type of ['equip','treasure']){const {p,npc,map}=fixture();p.bag={capacities:{equipment:1,treasures:1}};if(type==='treasure')E.grant(p,E.create(p,'treasure_0',2,'full',()=>.5));const id=M.templates(p,npc.id,map,type)[0].id,q=M.craftQuote(p,npc.id,map,id),before=p.stones,r=M.craft(p,npc.id,map,id,()=>0);a.equal(r.success,true);a.equal(r.item.quality,4);a.equal(ED.templates[r.item.baseId].type,type);a.equal(p.stones,before-q.cost.stones);a.ok(p.economy.mail.includes(r.item.id));const copy=JSON.parse(JSON.stringify(p));E.normalize(copy);a.equal(copy.economy.instances[r.item.id].quality,4);a.ok(copy.economy.mail.includes(r.item.id));a.equal(E.canBuy(id,4),false);}});
test('gold and unsuccessful commissions have explicit outcomes; invalid inputs do not charge',()=>{const {p,npc,map}=fixture(),base=M.templates(p,npc.id,map,'equip')[0].id;const gold=M.craft(p,npc.id,map,base,()=>.5);a.equal(gold.item.quality,3);const n=Object.keys(p.economy.instances).length,r=M.craft(p,npc.id,map,base,()=>.99);a.equal(r.success,false);a.equal(r.item,null);a.equal(Object.keys(p.economy.instances).length,n);const before=JSON.stringify(p);a.equal(M.craft(p,npc.id,map,base,()=>NaN).ok,false);a.equal(JSON.stringify(p),before);p.stones=0;const poor=JSON.stringify(p);a.equal(M.craft(p,npc.id,map,base,()=>0).ok,false);a.equal(JSON.stringify(p),poor);});
test('smith benefits cannot be used remotely, on another map or below required realm',()=>{const {p,npc,map,item}=fixture();p.position.x+=101;a.equal(M.upgrade(p,npc.id,map,item.id,()=>0).ok,false);p.position.x=npc.x;p.mapIndex++;a.equal(M.craftQuote(p,npc.id,map,'gear_weapon_0').ok,false);p.mapIndex--;p.realm=0;a.equal(M.quote(p,npc.id,map,item.id).ok,false);});
test('batch estimation matches successful actual costs and stops without overcharging',()=>{const {p,npc,map,item}=fixture(),plan=M.estimate(p,npc.id,map,item.id,102),r=M.upgradeTo(p,npc.id,map,item.id,102,()=>0);a.equal(r.after,102);a.equal(r.attempts,3);a.deepEqual(r.spent,plan.minimum);a.equal(M.upgradeTo(p,npc.id,map,item.id,201,()=>0).ok,false);p.stones=0;const before=JSON.stringify(p);a.equal(M.upgradeTo(p,npc.id,map,item.id,103,()=>0).ok,false);a.equal(JSON.stringify(p),before);});
test('seeded 10000 commission sampling matches per-attempt legendary and success probabilities',()=>{const {p,npc,map}=fixture();let seed=10010;const rng=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/4294967296);let legendary=0,success=0;for(let i=0;i<10000;i++){p.stones=1e8;p.inventory=[{id:'forgeDust',count:10000},{id:'celestialOre',count:10000}];p.economy.instances={};p.economy.mail=[];p.economy.masterForgeLog=[];const r=M.craft(p,npc.id,map,'gear_weapon_0',rng);legendary+=Number(r.item?.quality===4);success+=Number(r.success);}a.ok(legendary/10000>.13&&legendary/10000<.17);a.ok(success/10000>.83&&success/10000<.87);console.log('Forgemaster simulation: legendary='+legendary+'/10000; success='+success+'/10000');});
