const {test}=require('node:test');const assert=require('node:assert/strict');const R=require('../src/systems/progression.js');
const player=()=>R.normalize({version:2,name:'採集測試',inventory:[{id:'ring',count:10}],equipment:{ring:'ring'},herbs:7,stones:100,jade:0,hp:10,mp:5});
test('old herb pools merge once without duplication or mutating the original save',()=>{const old={version:2,inventory:[{id:'herb',count:4}],equipment:{},herbs:7,stones:100};const p=R.normalize(old);assert.equal(p.herbs,7);assert.equal(p.inventory[0].count,7);assert.equal(old.inventory[0].count,4);assert.deepEqual(R.normalize(p),p);R.sellItem(p,'herb',7,3);assert.equal(R.normalize(p).herbs,0);});
test('collection puts herbs into the bag once per cooldown',()=>{const p=player(),point=R.landmarks[1];assert.equal(R.collectLandmark(p,0,point,{hp:100,mp:50},1000).ok,true);assert.equal(p.herbs,10);assert.equal(p.inventory.find(i=>i.id==='herb').count,10);assert.equal(R.collectLandmark(p,0,point,{},2000).ok,false);assert.equal(R.collectLandmark(p,0,point,{},46000).ok,true);assert.equal(p.herbs,13)});
test('full inventory blocks new materials without consuming cooldown or granting partial ore rewards',()=>{const p=player();p.inventory=Array.from({length:40},(_,i)=>({id:'slot'+i,count:1}));const point=R.landmarks[2];const before=JSON.stringify(p);assert.equal(R.collectLandmark(p,1,point,{},1000).reason,'full');assert.equal(JSON.stringify(p),before);p.inventory[0]={id:'wood',count:1};assert.equal(R.collectLandmark(p,1,point,{},1000).ok,true);assert.equal(p.inventory[0].count,3);assert.equal(p.stones,150);});
test('automatic relic interaction claims each map only once and springs recover vitals',()=>{const p=player();const relic=R.landmarks[3],spring=R.landmarks[0];assert.equal(R.collectLandmark(p,0,relic,{},1000).ok,true);assert.equal(R.collectLandmark(p,0,relic,{},2000).ok,false);assert.equal(p.jade,5);assert.equal(R.collectLandmark(p,1,relic,{},2000).ok,true);R.collectLandmark(p,0,spring,{hp:188,mp:111},3000);assert.equal(p.hp,188);assert.equal(p.mp,111);});
test('bulk sale grants exact proceeds and preserves equipped gear',()=>{const p=player();assert.deepEqual(R.sellItem(p,'ring',3,75),{ok:true,amount:3,gain:225});assert.equal(p.inventory.find(i=>i.id==='ring').count,7);assert.equal(p.stones,325);assert.equal(p.equipment.ring,'ring');assert.equal(R.sellItem(p,'ring',7,75).ok,true);assert.equal(p.inventory.some(i=>i.id==='ring'),false);assert.equal(p.stones,850);assert.equal(p.equipment.ring,'ring');});
test('sales reject over-limit, zero, negative, fractional and non-finite quantities atomically',()=>{for(const n of [0,-1,11,1.5,NaN,Infinity]){const p=player(),before=JSON.stringify(p);assert.equal(R.sellItem(p,'ring',n,75).ok,false);assert.equal(JSON.stringify(p),before);}});
test('selling and consuming herbs update the shared alchemy stock without resurrection',()=>{const p=player();R.sellItem(p,'herb',2,3);assert.equal(p.herbs,5);assert.equal(R.takeItem(p,'herb',2),true);assert.equal(p.herbs,3);assert.equal(R.normalize(p).herbs,3);R.takeItem(p,'herb',3);assert.equal(p.herbs,0);assert.equal(R.takeItem(p,'herb',1),false);});
test('a mature crop remains intact when its materials cannot fit',()=>{const p=player();R.plant(p,0,1000);p.inventory=Array.from({length:40},(_,i)=>({id:'slot'+i,count:1}));const before=JSON.stringify(p.estate.plots[0]);assert.equal(R.harvest(p,0,91000),0);assert.equal(JSON.stringify(p.estate.plots[0]),before);p.inventory.pop();assert.equal(R.harvest(p,0,92000),4);assert.equal(p.herbs,4);});

test('migration retains old herb stock even when the legacy bag is already full',()=>{const old={version:2,inventory:Array.from({length:40},(_,i)=>({id:'item'+i,count:1})),equipment:{},herbs:7};const p=R.normalize(old);assert.equal(p.inventory.length,41);assert.equal(p.herbs,7);assert.equal(old.inventory.length,40);assert.equal(R.addItem(p,'new',1),false);assert.equal(R.addItem(p,'herb',3),true);assert.equal(p.herbs,10);});
