const {test}=require('node:test'),a=require('node:assert/strict'),D=require('../src/data/high-realms.js'),ED=require('../src/data/economy.js'),E=require('../src/systems/economy.js'),H=require('../src/systems/high-realms.js'),fs=require('fs'),vm=require('vm');D.install([],ED,{});
function fixture(){const p={realm:8,finished:false,skills:{flame:3,sword:2,heal:1,heart:4},equipment:{weapon:'legacySword'},inventory:[],ownedTreasures:[],levelPet:{},stones:100,mp:200,future:{preserve:true},auto:true,autoMeditate:true};E.normalize(p);H.normalize(p);return p;}
test('six realms contain 30 zones, 48 appropriate enemies and 18 functional NPC definitions',()=>{a.equal(D.maps.length,30);a.equal(D.enemies.length,48);a.equal(D.npcs.length,18);for(const t of D.themes){a.equal(D.maps.filter(m=>m.theme===t.id).length,5);a.equal(D.enemies.filter(e=>e.theme===t.id&&e.role==='cultivator').length,2);a.equal(D.enemies.filter(e=>e.theme===t.id&&e.role==='boss').length,1);a.ok(D.enemies.filter(e=>e.theme===t.id&&['normal','elite'].includes(e.role)).length>=5);a.equal(t.props.length,3);}const p=fixture();p.realm=3;a.ok(D.maps.every(m=>!H.canEnter(p,m)));p.realm=8;a.equal(H.canEnter(p,D.maps.at(-1)),false);p.finished=true;a.equal(H.canEnter(p,D.maps.at(-1)),true);});
test('90 unique templates and books all attainable; repeats and realm requirements preserve books',()=>{const p=fixture();a.equal(D.templates.filter(t=>t.type==='pet').length,30);a.equal(D.templates.filter(t=>t.type==='treasure').length,30);a.equal(D.skills.length,30);for(const t of D.templates){const it=E.create(p,t.id,2,'test',()=>.5);a.equal(E.grant(p,it),true);a.equal(ED.templates[it.baseId].name,t.name);}for(const s of D.skills){E.addStack(p,s.bookId,2);a.equal(H.learn(p,s.bookId).ok,true);a.equal(H.learn(p,s.bookId).ok,false);a.equal(p.inventory.find(e=>e.id===s.bookId).count,1);}const low=fixture();low.realm=0;E.addStack(low,D.skills[0].bookId,1);a.equal(H.learn(low,D.skills[0].bookId).ok,false);a.equal(low.inventory[0].count,1);});
test('migration preserves original skills, eight-slot configuration and unknown save data',()=>{const p=fixture();a.deepEqual(p.highRealms.slots,['attack','flame','sword','heal',null,null,null,null]);a.equal(H.assign(p,7,'v21_skill_0'),false);p.skills.v21_skill_0=1;a.equal(H.assign(p,7,'v21_skill_0'),true);H.assign(p,0,'v21_skill_0');a.equal(p.highRealms.slots[7],'attack');const saved=JSON.parse(JSON.stringify(p));H.normalize(saved);a.deepEqual(saved.highRealms,p.highRealms);a.equal(saved.skills.flame,3);a.equal(saved.equipment.weapon,'legacySword');a.deepEqual(saved.future,{preserve:true});a.equal(saved.auto,true);a.equal(saved.autoMeditate,true);});
test('boss always grants purple or higher and receipts stop duplicate payout after reload',()=>{for(let i=0;i<50;i++){const p=fixture(),enemy={claimId:'boss:'+i,realm:4+i%5,role:'boss'},r=H.reward(p,enemy,()=>.999);a.equal(r.ok,true);a.ok(r.ids.some(id=>p.economy.instances[id].quality>=2));const copy=JSON.parse(JSON.stringify(p)),snapshot=JSON.stringify(copy);a.equal(H.reward(copy,enemy,()=>0).ok,false);a.equal(JSON.stringify(copy),snapshot);}});
test('gold legendary pet book and six-tier gem drops remain separate from rift and encounter rates; overflow retained',()=>{const p=fixture();p.bag={capacities:{equipment:0,treasures:1,pets:1,materials:1}};p.ownedTreasures=['full'];p.levelPet={full:1};const high=H.reward(p,{claimId:'boss:all',realm:8,role:'boss'},()=>0);a.ok(high.ids.some(id=>p.economy.instances[id].quality===4));a.ok(high.ids.some(id=>p.economy.instances[id].quality===3));a.ok(high.rewards.some(x=>x.id.startsWith('v21_book')));a.ok(p.economy.mail.length>0);a.equal(ED.config.encounters.ordinary,.04);a.equal(ED.config.encounters.rare,.05);a.equal(ED.config.encounters.ancient,.06);const before=JSON.stringify(p);a.equal(H.reward(p,{claimId:'invalid',realm:8,role:'boss'},()=>NaN).ok,false);a.equal(JSON.stringify(p),before);});
test('automatic skill decisions honor healing, mana, area and per-skill disable conditions',()=>{const p=fixture();p.hp=30;p.mp=20;const st={hp:100,mp:100};a.equal(H.autoEligible(p,D.skills[14],st,0),true);a.equal(H.autoEligible(p,D.skills[17],st,0),true);a.equal(H.autoEligible(p,D.skills[0],st,1),false);a.equal(H.autoEligible(p,D.skills[0],st,2),true);p.highRealms.auto[D.skills[0].id]={enabled:false};a.equal(H.autoEligible(p,D.skills[0],st,5),false);});
const source=fs.readFileSync('tests/rift-integration.test.cjs','utf8'),body=source.slice(source.indexOf('function harness()'),source.indexOf("test('real damage"));
function runtime(){const h=new Function('fs','vm',body+';return harness;')(fs,vm)();h.c.Image=class{constructor(){this.complete=false;this.naturalWidth=0;}};h.c.window.addEventListener=()=>{};for(const f of ['src/data/economy.js','src/data/forge-affixes.js','src/data/high-realms.js','src/systems/economy.js','src/systems/high-realms.js','src/systems/economy-combat.js'])vm.runInContext(fs.readFileSync(f,'utf8'),h.c);h.run(`HighRealmData.install(MAPS,EconomyData,ITEMS);function economyHydrate(){Economy.normalize(p);}function characterIcon(){return ''}function characterIsOpen(){return false}function closeCharacter(){}function economyMoveRate(){return 1}function fireCompanion(){return false}function interactPoint(){return false}function drawLandmarks(){}function drawCreature(){}const economyAsset=id=>'';p.realm=4;p.stage=0;p.mp=10000;p.hp=10000;Economy.normalize(p);HighRealms.normalize(p);for(const s of HighRealmData.skills)p.skills[s.id]=1;`);vm.runInContext(fs.readFileSync('src/ui/high-realms.js','utf8'),h.c);return h;}
test('real skill adapter deals multi-target damage, moves player and creates a firing clone',()=>{const h=runtime();h.run(`p.highRealms.slots[4]='v21_skill_2';enemies=Array.from({length:4},(_,i)=>({x:p.position.x+80+i*15,y:p.position.y,hp:1e9,maxHp:1e9,def:0,stone:1,qi:1}));cast(4)`);a.equal(h.run('enemies.filter(e=>e.hp<1e9).length'),4);h.run(`p.highRealms.slots[4]='v21_skill_20';p.highRealms.cooldowns={};const before=p.position.y;cast(4)`);a.notEqual(h.run('p.position.y'),400);h.run(`p.highRealms.slots[4]='v21_skill_26';p.highRealms.cooldowns={};cast(4);stepV21(.01)`);a.ok(h.run('p.highRealms.clone.until')>Date.now());a.ok(h.run('projectiles.length')>0);});
test('shield actually absorbs incoming damage, healing and mana recovery respect maximums',()=>{const h=runtime();h.run(`p.highRealms.slots[4]='v21_skill_10';cast(4);const blocked=EconomyCombat.incoming(100,Economy.bonuses(p));`);a.equal(h.run('blocked'),0);h.run(`p.hp=1;p.highRealms.slots[4]='v21_skill_14';cast(4)`);a.ok(h.run('p.hp')>1);a.ok(h.run('p.hp<=stats().hp'));h.run(`p.mp=40;p.highRealms.slots[4]='v21_skill_17';cast(4)`);a.ok(h.run('p.mp')>40);a.ok(h.run('p.mp<=stats().mp'));});
test('real high realm spawning enforces map entry and one boss; low HP changes phase and skills damage player',()=>{const h=runtime();a.equal(h.run('switchMap(10)'),false);a.equal(h.run('switchMap(9)'),true);a.equal(h.run('enemies.length'),1);h.run('spawnEnemy();spawnEnemy()');a.equal(h.run('enemies.length'),1);h.run(`const boss=enemies[0];boss.hp=boss.maxHp*.15;boss.x=p.position.x+60;boss.y=p.position.y;boss.skills=['heavy'];boss.skillTimer=0;p.hp=stats().hp;stepV21(.3);boss.warning.at=0;const hpBefore=p.hp;stepV21(.1);`);a.equal(h.run('boss.phase'),2);a.ok(h.run('p.hp<hpBefore'));});

test('high realm companions stay drop-only and all rare materials have reachable drops',()=>{for(const t of D.templates)a.equal(E.canBuy(t.id,2),false);const found=new Set();for(const n of [0,.4,.8]){let i=0;const p=fixture();const r=H.reward(p,{claimId:'materials:'+n,realm:8,role:'boss'},()=>i++===18?n:0);for(const x of r.rewards)found.add(x.id);}for(let i=6;i<9;i++)a.ok(found.has('v21_mat_'+i));});

test('all 30 learned high realm skills execute through the live cast adapter',()=>{for(const s of D.skills){const h=runtime();h.run(`p.realm=8;p.highRealms.slots[4]='${s.id}';p.hp=1;p.mp=10000;enemies=[{x:p.position.x+80,y:p.position.y,hp:1e9,maxHp:1e9,def:0,stone:1,qi:1}];`);a.equal(h.run('cast(4)'),true,s.id);a.ok(h.run(`p.highRealms.cooldowns['${s.id}']`)>Date.now(),s.id);}});
test('seeded 5000-boss simulation matches configured gold and legendary extra chances',()=>{let seed=20261010;const rng=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/4294967296);let gold=0,legend=0;for(let i=0;i<5000;i++){const p=fixture(),r=H.reward(p,{claimId:'sim:'+i,realm:8,role:'boss'},rng);gold+=r.ids.some(id=>p.economy.instances[id].quality===3)?1:0;legend+=r.ids.some(id=>p.economy.instances[id].quality===4&&ED.templates[p.economy.instances[id].baseId].type==='treasure')?1:0;}a.ok(gold/5000>.15&&gold/5000<.21);a.ok(legend/5000>.01&&legend/5000<.03);console.log('V2.1 boss simulation: gold='+gold+'/5000; legendary treasure='+legend+'/5000');});

test('high realm pet cultivation consumes its material only on a valid upgrade and deployment respects realm',()=>{const C=require('../src/systems/character.js'),p=fixture(),t=D.templates.find(t=>t.type==='pet'),it=E.create(p,t.id,2,'test',()=>.5);E.grant(p,it);p.stones=10000;C.normalize(p);p.companions={deployed:[]};const before=p.stones;a.equal(C.upgrade(p,it.id),false);a.equal(p.stones,before);E.addStack(p,t.cultivationRequirement.material,t.cultivationRequirement.count);a.equal(C.upgrade(p,it.id),true);p.realm=0;a.equal(C.primary(p,'pet',it.id),false);a.equal(C.deployment(p,'pet:'+it.id),false);p.realm=t.realm;a.equal(C.primary(p,'pet',it.id),true);a.equal(C.deployment(p,'pet:'+it.id),true);});

test('all V2.1 ComfyUI assets have matching RGBA masters and runtime files',()=>{const assets=JSON.parse(fs.readFileSync('art/v21/assets.json','utf8')),ready=vm.runInNewContext(fs.readFileSync('src/data/v21-assets.js','utf8')+';V21Assets');a.equal(assets.length,189);a.equal(new Set(assets.map(x=>x.asset_id)).size,189);a.equal(ready.length,189);for(const x of assets){a.ok(ready.includes(x.asset_id));for(const kind of ['master','runtime']){const b=fs.readFileSync('src/assets/v21/'+kind+'/'+x.asset_id+'.png');a.equal(b.subarray(1,4).toString(),'PNG');a.equal(b.readUInt32BE(16),x[kind]);a.equal(b.readUInt32BE(20),x[kind]);a.equal(b[25],6,'RGBA '+x.asset_id);}}for(const m of D.maps)a.ok(ready.includes(m.assetId));});

test('NPC transmission counts only high realm kills and its reward cannot be claimed twice',()=>{const h=runtime();h.run(`mapIndex=5;function nearestPoint(){return {...HighRealmData.npcs[0],kind:'npc'};}let npcButtons=[];modal=(t,html,buttons)=>{npcButtons=buttons};interactPoint();npcButtons[2].fn();p.killCount=100;interactPoint();npcButtons[2].fn();`);a.equal(h.run('!!p.highRealms.npcQuests[HighRealmData.npcs[0].id].claimed'),false);h.run('p.highRealms.killCount=10;interactPoint();npcButtons[2].fn()');a.equal(h.run('p.highRealms.npcQuests[HighRealmData.npcs[0].id].claimed'),true);const before=h.run('JSON.stringify(p.inventory)');h.run('interactPoint();npcButtons[2].fn()');a.equal(h.run('JSON.stringify(p.inventory)'),before);});
