const {test}=require('node:test'),assert=require('node:assert/strict'),E=require('../src/systems/economy.js'),L=require('../src/systems/legend-alerts.js');
const player=()=>({realm:4,stones:0,inventory:[],equipment:{weapon:'sword'},levelPet:{fox:7},ownedTreasures:['mirror'],activePet:'fox',activeTreasure:'mirror',companions:{order:['pet:fox','treasure:mirror'],deployed:['pet:fox'],cooldowns:{'pet:fox':99999}},bag:{capacities:{equipment:1,pets:1,treasures:1},locked:{sword:true}},future:{keep:42}});
test('mailbox legend directly replaces worn gear despite full bag, with old gear and lock preserved',()=>{const p=player();E.normalize(p);p.bag.capacities.equipment=100;const catalog={sword:{type:'equip'}};for(let i=0;i<100;i++){const g=E.create(p,'gear_head_0',0,'test',()=>.5);E.grant(p,g);catalog[g.id]={type:'equip'};}const it=E.create(p,'gear_weapon_0',4,'drop',()=>.5);E.grant(p,it);assert.equal(L.pending(p).length,1);assert.equal(L.equip(p,it.id,catalog).ok,true);assert.equal(p.equipment.weapon,it.id);assert.equal(p.economy.mail.includes(it.id),false);assert.ok(p.economy.mail.some(e=>e.id==='sword'));assert.equal(p.bag.locked.sword,true);assert.equal(L.pending(JSON.parse(JSON.stringify(p))).length,0);assert.deepEqual(p.future,{keep:42});});
test('bag legend consumes its original copy and returns previous gear without duplication',()=>{const p=player();p.bag.capacities.equipment=100;E.normalize(p);const it=E.create(p,'gear_weapon_0',4,'drop',()=>.5);E.grant(p,it);assert.equal(L.equip(p,it.id).ok,true);assert.equal(p.inventory.some(e=>e.id===it.id),false);assert.equal(p.inventory.filter(e=>e.id==='sword').length,1);L.equip(p,it.id);assert.equal(p.inventory.filter(e=>e.id==='sword').length,1);});
test('insufficient realm never consumes reward or changes equipment',()=>{const p=player();p.realm=0;E.normalize(p);const it=E.create(p,'gear_weapon_9',4,'drop',()=>.5);E.grant(p,it);const before=JSON.stringify(p);assert.equal(L.equip(p,it.id).reason,'realm');assert.equal(JSON.stringify(p),before);});
test('full companion categories swap main into mailbox, preserve old levels/cooldowns and can recover later',()=>{for(const type of ['pet','treasure']){const p=player();E.normalize(p);const it=E.create(p,type+'_0',4,'drop',()=>.5);E.grant(p,it);assert.equal(L.equip(p,it.id).ok,true);assert.equal(p[type==='pet'?'activePet':'activeTreasure'],it.id);const displaced=p.economy.mail.find(e=>e.companion===type);assert.equal(displaced.id,type==='pet'?'fox':'mirror');if(type==='pet'){assert.equal(displaced.level,7);assert.equal(p.companions.cooldowns['pet:fox'],99999);p.bag.capacities.pets=100;}else p.bag.capacities.treasures=100;assert.equal(E.recover(p),1);assert.equal(type==='pet'?p.levelPet.fox:p.ownedTreasures.includes('mirror'),type==='pet'?7:true);}});
test('dismissal persists, only held or mailbox legends appear, countdown uses ten wall-clock seconds',()=>{const p=player();E.normalize(p);const it=E.create(p,'gear_head_0',4,'drop',()=>.5);assert.equal(L.pending(p).length,0);E.grant(p,it);L.dismiss(p,it.id);assert.equal(L.pending(JSON.parse(JSON.stringify(p))).length,0);assert.equal(L.seconds(11000,1000),10);assert.equal(L.seconds(11000,10999),1);assert.equal(L.seconds(11000,11000),0);assert.equal(L.seconds(11000,20000),0);});

test('reward countdown closes at ten seconds and never closes a replacement dialog',()=>{const vm=require('node:vm'),source=require('node:fs').readFileSync(require('node:path').join(__dirname,'../src/ui/legend-alerts.js'),'utf8').slice(require('node:fs').readFileSync(require('node:path').join(__dirname,'../src/ui/legend-alerts.js'),'utf8').indexOf('const legendModalBase='));let now=0,closed=0,clock,callback;const ctx={modal(){},Date:{now:()=>now},LegendAlerts:{seconds:deadline=>L.seconds(deadline,now)},document:{createElement:()=>({setAttribute(){}})},$:id=>id==='modalContent'?{prepend(c){clock=c}}:{classList:{contains:()=>false}},setInterval(fn){callback=fn;return 1},clearInterval(){},closeModal(){closed++}};vm.createContext(ctx);vm.runInContext(source,ctx);ctx.modal('魔修已伏誅 · 擊殺獎勵','',[]);assert.match(clock.textContent,/10 秒/);now=9000;callback();assert.match(clock.textContent,/1 秒/);assert.equal(closed,0);now=10000;callback();assert.equal(closed,1);ctx.modal('魔修已伏誅 · 擊殺獎勵','',[]);ctx.modal('傳說物品','',[]);now=21000;callback();assert.equal(closed,1);});


