const {test}=require('node:test'),assert=require('node:assert/strict'),F=require('../src/systems/legend-forge.js'),E=require('../src/systems/economy.js');
function fixture(){const p={stones:10000,realm:3,inventory:[],equipment:{},levelPet:{},ownedTreasures:[],future:{keep:1}};E.normalize(p);const ids=Array.from({length:3},()=>{const it=E.create(p,'gear_weapon_0',3,'test',()=>.5);E.grant(p,it);return it.id});E.addStack(p,'celestialOre',5);return {p,ids};}
test('independent synthesis consumes three distinct gold only on success and persists legend/log',()=>{const {p,ids}=fixture(),r=F.attempt(p,ids,5,()=>.5);assert.equal(r.success,true);assert.equal(r.item.quality,4);assert.equal(p.stones,7000);assert.equal(p.inventory.some(e=>ids.includes(e.id)),false);assert.equal(p.inventory.some(e=>e.id==='celestialOre'),false);assert.equal(p.economy.synthesisLog.length,1);assert.equal(E.held(JSON.parse(JSON.stringify(p)),r.item.id),true);assert.deepEqual(p.future,{keep:1});assert.equal(F.attempt(p,ids,0,()=>0).ok,false);});
test('failed synthesis retains all gold, charges only selected ore and stones, rolls boundary correctly',()=>{const {p,ids}=fixture();assert.equal(F.quote(p,ids,0).chance,.45);assert.equal(F.quote(p,ids,5).chance,.95);const r=F.attempt(p,ids,2,()=>.65);assert.equal(r.success,false);assert.equal(p.stones,7000);assert.equal(p.inventory.find(e=>e.id==='celestialOre').count,3);ids.forEach(id=>assert.equal(E.held(p,id),true));assert.equal(p.economy.synthesisLog[0].success,false);});
test('invalid materials, locks, enhancement, socket, worn, funds, ore, duplicate and invalid RNG never charge',()=>{for(const mode of ['lock','enhance','socket','worn','funds','ore','duplicate','rng']){const {p,ids}=fixture();if(mode==='lock')p.economy.instances[ids[0]].locked=true;if(mode==='enhance')p.economy.instances[ids[0]].enhancement=1;if(mode==='socket')p.economy.instances[ids[0]].sockets=['gem_fire_1'];if(mode==='worn')p.equipment.weapon=ids[0];if(mode==='funds')p.stones=1;if(mode==='duplicate')ids[1]=ids[0];const before=JSON.stringify(p);assert.equal(F.attempt(p,ids,mode==='ore'?6:0,()=>mode==='rng'?NaN:0).ok,false);assert.equal(JSON.stringify(p),before);}});
test('ore rates increase at nascent and rifts, receipts prevent duplication, full materials go to mailbox',()=>{assert.ok(F.dropChance(3)>F.dropChance(2));assert.ok(F.dropChance(4)>F.dropChance(3));assert.ok(F.dropChance(0,true)>F.dropChance(3));assert.ok(F.dropChance(0,true,true)>F.dropChance(0,true));const {p}=fixture();p.inventory=p.inventory.filter(e=>e.id!=='celestialOre');p.bag={capacities:{materials:1}};p.inventory.push({id:'wood',count:1});assert.equal(F.drop(p,'boss',3,true,true,()=>0).count,2);assert.equal(p.economy.mail[0].id,'celestialOre');const saved=JSON.parse(JSON.stringify(p));assert.equal(F.drop(saved,'boss',3,true,true,()=>0).ok,false);assert.equal(saved.economy.mail.length,1);let hits=0;for(let i=0;i<10000;i++)hits+=(i/10000<F.dropChance(3));assert.equal(hits,600);});

test('high realm gold retains actual realm, level and scaled base when promoted to legend',()=>{for(const realm of [4,5,6,7,8]){const {p,ids}=fixture();for(const id of ids){const it=p.economy.instances[id];it.realm=realm;it.level=90;it.base={atk:1000,def:200,hp:300};}const r=F.attempt(p,ids,5,()=>.5);assert.equal(r.item.realm,realm);assert.equal(r.item.level,90);assert.equal(r.item.base.atk,1297);assert.equal(r.item.base.def,259);assert.equal(r.item.sockets.length,6);assert.equal(r.record.sourceRealm,realm);}});
test('mixed realm materials are rejected without deductions',()=>{const {p,ids}=fixture();p.economy.instances[ids[0]].realm=4;const before=JSON.stringify(p);assert.equal(F.attempt(p,ids,5,()=>0).ok,false);assert.equal(JSON.stringify(p),before);});
test('old synthesis receipts repair inherited stats once while preserving upgrades and gems',()=>{const {p,ids}=fixture();const source=p.economy.instances[ids[0]];for(const id of ids)p.economy.instances[id].realm=4;source.base.atk=4000;source.level=80;const r=F.attempt(p,ids,5,()=>.5);r.item.realm=0;r.item.level=1;r.item.base.atk=29;r.item.enhancement=30;r.item.sockets[0]='gem_fire_6';delete r.record.inheritanceVersion;assert.equal(F.repair(p),1);assert.equal(r.item.realm,4);assert.equal(r.item.level,80);assert.equal(r.item.base.atk,5189);assert.equal(r.item.enhancement,30);assert.equal(r.item.sockets[0],'gem_fire_6');assert.equal(F.repair(p),0);});
