const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),{test}=require('node:test');
function harness(){const nodes=new Map(),saved=new Map(),timers=[];function node(){return {style:{setProperty(){}},dataset:{},children:[],classList:{contains:name=>name==='hidden',add(){},remove(){},toggle(){}},getContext:()=>({}),addEventListener(){},append(){},prepend(){},before(){},remove(){},replaceChildren(){},querySelectorAll:()=>[],setAttribute(){},textContent:'',innerHTML:''}}const document={getElementById:id=>{if(!nodes.has(id))nodes.set(id,node());return nodes.get(id)},querySelector:()=>node(),querySelectorAll:()=>[],createElement:()=>node(),createTextNode:s=>s};const c=vm.createContext({document,window:{},console,Math,Date,performance:{now:()=>0},localStorage:{setItem:(k,v)=>saved.set(k,v),getItem:k=>saved.get(k)||null,removeItem:k=>saved.delete(k)},setTimeout:fn=>timers.push(fn),setInterval(){},requestAnimationFrame:()=>1,cancelAnimationFrame(){}});c.window.localStorage=c.localStorage;for(const f of ['src/data/catalog.js','src/systems/progression.js','src/systems/encounters.js','src/game.js'])vm.runInContext(fs.readFileSync(f,'utf8').replace(/\ninit\(\);\s*$/,''),c);vm.runInContext(`let destination=null,activeView='explore',explorationGraceUntil=0;function updateJourney(){} function stepExploration(){} function setView(v){activeView=v}function currentPoints(){return []}renderAll=()=>{};renderCurrent=()=>{};renderUI=()=>{};renderDungeons=()=>{};chooseTab=()=>{};note=()=>{};log=()=>{};p=Progression.normalize(initialPlayer('試煉','five'));p.position={x:300,y:400};p.stones=0;p.jade=0;`,c);vm.runInContext(fs.readFileSync('src/ui/encounters.js','utf8'),c);vm.runInContext('Encounters.normalize(p)',c);return {c,saved,timers,run:code=>vm.runInContext(code,c)}}
test('real damage and loot path clears exactly ten waves, pays each once, restores exploration',()=>{const h=harness();h.run('beginRift(0)');const base=h.run('p.rift.base.combat'),bag=h.run('JSON.stringify(p.inventory)');let total=0;for(let w=1;w<=10;w++){assert.equal(h.run('p.rift.wave'),w);h.run('[...enemies].forEach(e=>hurtEnemy(e,10000000))');assert.equal(h.run('enemies.length'),0);h.run('stepEncounters(.01)');total+=h.run(`Encounters.waveReward({combat:${base}},${w})`);if(w<10){assert.equal(h.run('p.stones'),total);h.run('stepEncounters(3.1)');for(const fn of h.timers.splice(0))fn();assert.equal(h.run('enemies.length'),h.run(`Encounters.wave(0,${w+1},p.rift.base).length`));}}assert.equal(h.run('riftRunning'),false);assert.equal(h.run('p.rift'),null);assert.equal(h.run('p.encounters.clears.ember'),1);assert.equal(h.run('p.jade'),5);assert.equal(h.run('p.stones'),total+Math.round(base*1.5+300));assert.equal(h.run('JSON.stringify(p.inventory)'),bag);assert.equal(h.run('p.position.x'),300);assert.equal(h.run('p.position.y'),400);const money=h.run('p.stones');h.run('finishRift(true)');assert.equal(h.run('p.stones'),money);});
test('lethal telegraphed skill exits without clear reward; moving outside its area avoids damage',()=>{const h=harness();h.run("beginRift(1);enemies[0].elite=true;enemies[0].atk=1000;enemies[0].warning={x:900,y:800,radius:70,left:.01,total:1};");const hp=h.run('p.hp');h.run('stepEncounters(.02)');assert.equal(h.run('p.hp'),hp);h.run('enemies[0].warning={...p.position,radius:70,left:.01,total:1}');h.run('stepEncounters(.02)');assert.equal(h.run('riftRunning'),false);assert.equal(h.run('p.jade'),0);assert.equal(h.run('p.encounters.clears.frost||0'),0);});
test('rift snapshot reload resumes remaining enemies and wave without ambient respawns',()=>{const h=harness();h.run('beginRift(2);hurtEnemy(enemies[0],1000000);save(true)');const save=JSON.parse(h.saved.get('TAIXU_ASCEND_V2_SAVE'));assert.equal(save.rift.enemies.length,2);h.c.imported=save;h.run('p=imported;startGame()');assert.equal(h.run('riftRunning'),true);assert.equal(h.run('enemies.length'),2);h.run('spawnEnemy()');assert.equal(h.run('enemies.length'),2);assert.equal(h.run('p.rift.wave'),1);});



test('all five rift styles render desktop and mobile, boss transformation and hazard circles safely',()=>{const h=harness();const finite=args=>args.filter(a=>typeof a==='number').forEach(a=>assert.ok(Number.isFinite(a)));const gradient={addColorStop(){}};const g=new Proxy({}, {get(target,key){if(key in target)return target[key];if(key==='createLinearGradient'||key==='createRadialGradient')return ()=>gradient;return (...args)=>{finite(args);if(key==='arc')assert.ok(args[2]>=0);if(key==='ellipse'){assert.ok(args.length>=7);assert.ok(args[2]>=0&&args[3]>=0)}}},set(target,key,value){target[key]=value;return true}});h.c.g=g;h.c.document.createElement=()=>({getContext:()=>g});h.run('beginRift(0)');for(let t=0;t<5;t++){h.run(`p.rift.theme=${t};p.rift.wave=10;enemies=Encounters.wave(${t},10,p.rift.base);enemies[0].hp=1;Encounters.transform(enemies[0]);enemies[0].warning={x:460,y:355,radius:165,left:1,total:2.2};`);const before=h.run('JSON.stringify({rift:p.rift,enemies})');h.run('drawRiftScene(g,335,324,3);drawRiftScene(g,1000,460,4)');assert.equal(h.run('JSON.stringify({rift:p.rift,enemies})'),before);}});


