'use strict';
const bagHeading=document.querySelector('.character-bag-heading');
for(const [label,fn]of [['售白品裝備',()=>bagBulkSale(0)],['售藍品裝備',()=>bagBulkSale(1)],['整理背包',()=>{BagTools.organize(p,ITEMS);save(true);renderAll();renderCharacterBag();note('背包已整理：可堆疊物品合併，依品質與名稱排列')} ]]){const b=document.createElement('button');b.className='btn line';b.textContent=label;b.onclick=fn;bagHeading.append(b);}
function bagBulkSale(q){const plan=BagTools.preview(p,q,ITEMS);modal('批次販售 · '+characterQuality(q),'<p>可販售裝備 '+fmt(plan.count)+' 件 · 合計 '+fmt(plan.total)+' 靈石</p><p>僅出售背包中的指定品質裝備。鎖定、穿戴中、已強化及已鑲嵌物品一律保留。</p>',[{text:'取消'},{text:'確認販售',style:'gold',fn:()=>{const fresh=BagTools.preview(p,q,ITEMS);if(fresh.count!==plan.count||fresh.total!==plan.total||JSON.stringify(fresh.entries)!==JSON.stringify(plan.entries))return bagBulkSale(q);const r=BagTools.sell(p,q,ITEMS);if(!r.ok)return note('沒有可販售的裝備');save(true);renderAll();renderCharacterBag();modal('販售完成','<p>已出售 '+r.count+' 件裝備 · 獲得 '+fmt(r.total)+' 靈石</p>',[{text:'完成',style:'gold'}]);}}]);$('modalActions').lastElementChild.disabled=!plan.count;}
function bagLockButton(id){if(!count(id)&&!Object.values(p.equipment).includes(id))return;const button=document.createElement('button');button.className='btn line';button.textContent=BagTools.locked(p,id)?'解鎖物品':'鎖定物品';button.onclick=()=>{BagTools.lock(p,id);save(true);renderCharacterBag();showItem(id)};$('modalActions').append(button);if(BagTools.locked(p,id)){$('modalContent').querySelectorAll('.sale-panel input,.sale-panel button').forEach(e=>e.disabled=true);$('modalContent').insertAdjacentHTML('afterbegin','<p role="status">🔒 已鎖定：不會被單件或批次販售。</p>');$('modalActions').querySelectorAll('button').forEach(b=>{if(b.textContent.startsWith('出售')){b.disabled=true;b.title='請先解鎖物品';}});}}
const bagShowItem=showItem;showItem=function(id){bagShowItem(id);bagLockButton(id)};
const bagRender=renderCharacterBag;renderCharacterBag=function(){bagRender();$('characterItems').querySelectorAll('[data-character-item]').forEach(b=>{if(BagTools.locked(p,b.dataset.characterItem)){const mark=document.createElement('strong');mark.textContent='🔒';mark.className='bag-lock-mark';b.append(mark)}});bagHeading.querySelectorAll('button').forEach(b=>{if(b.textContent.startsWith('收納匣')||b.textContent.startsWith('未領取匣'))b.textContent='未領取匣 · '+(p.economy?.mail.length||0);});};
economyMailbox=function(){const n=Economy.recover(p);economyHydrate();save(true);renderAll();renderCharacterBag();modal('未領取匣','<p>本次取回 '+n+' 份；尚有 '+p.economy.mail.length+' 份等待空間。滿格掉落會隨存檔保留。</p><div class="bag-mail-list">'+p.economy.mail.map(entry=>{const id=typeof entry==='string'?entry:entry.id,it=p.economy.instances[id],t=EconomyData.templates[it?.baseId||id]||it?.template||ITEMS[id]||PETS.find(t=>t.id===id)||TREASURES.find(t=>t.id===id);return '<p>'+escapeHTML(t?.name||id)+' ×'+(typeof entry==='string'?1:entry.count)+(it?' · '+characterQuality(it.quality):'')+'</p>';}).join('')+'</div>',[{text:'關閉'},{text:'再次領取',fn:()=>economyMailbox()}]);};
// Replace the old direct callback as well as the global entry point.
bagHeading.querySelectorAll('button').forEach(b=>{if(b.textContent==='收納匣'){b.textContent='未領取匣';b.onclick=()=>economyMailbox()}});
add=function(id,n=1){if(!ITEMS[id])return false;const before=JSON.stringify(p.economy?.mail||[]),ok=BagTools.receive(p,id,n,ITEMS);if(ok&&JSON.stringify(p.economy.mail)!==before){save(true);note('背包已滿，物品已存入未領取匣');}return ok;};
