'use strict';
(function(){const world=document.querySelector('.world'),button=document.createElement('button'),panel=document.createElement('section');button.className='battle-message-button';button.innerHTML='💬<small hidden></small>';button.setAttribute('aria-label','戰鬥即時訊息');button.setAttribute('aria-expanded','false');button.setAttribute('aria-controls','battleMessagePanel');panel.id='battleMessagePanel';panel.className='battle-message-panel hidden';panel.setAttribute('aria-label','戰鬥即時訊息紀錄');panel.innerHTML='<header><strong>即時訊息</strong><button type="button" aria-label="關閉即時訊息">X</button></header><div class="battle-message-list"></div>';world.append(button,panel);panel.querySelector('header button').onclick=close;
 function refresh(){const n=BattleNotices.unread();button.querySelector('small').hidden=!n;button.querySelector('small').textContent=n>9?'9+':String(n);button.title=BattleNotices.list()[0]?.text||'點擊查看戰鬥即時訊息';button.setAttribute('aria-label','戰鬥即時訊息'+(n?' · '+n+' 則未讀':''));if(!panel.classList.contains('hidden'))draw();}
 function draw(){panel.querySelector('.battle-message-list').innerHTML=BattleNotices.list().map(m=>'<p><time>'+new Date(m.at).toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit'})+'</time> '+escapeHTML(m.text)+(m.count>1?' <small>×'+m.count+'</small>':'')+'</p>').join('')||'<p>目前沒有訊息。</p>';}

 function close(){panel.classList.add('hidden');button.setAttribute('aria-expanded','false');}
 button.onclick=()=>{if(!panel.classList.contains('hidden'))return close();BattleNotices.read();panel.classList.remove('hidden');button.setAttribute('aria-expanded','true');refresh();};document.addEventListener('pointerdown',e=>{if(!panel.classList.contains('hidden')&&!panel.contains(e.target)&&!button.contains(e.target))close();},true);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!panel.classList.contains('hidden')){close();button.focus();}});
 const oldNote=note;note=function(text){BattleNotices.add(text);if(activeView==='manage')oldNote(text);else{clearTimeout(toastTimer);$('toast').classList.add('hidden');}if(!panel.classList.contains('hidden'))BattleNotices.read();refresh();};
 const oldView=setView;setView=function(view){oldView(view);if(view==='explore')$('toast').classList.add('hidden');};
})();
