'use strict';
// ComfyUI battle presentation. No combat rules or save schema changes.
const BattleArt = (() => {
  const images = new Map();
  const names = ['hero-sword','hero-jade','hero-sage','hero-moon','creature-wolf','creature-treant','creature-fox','prop-bamboo','prop-rock','prop-pavilion','prop-grass','forest-floor','icon-fox','icon-pearl','icon-sword','icon-fire','icon-taiji','icon-cauldron'];
  let generation=0;
  for(const name of names){const image=new Image();image.decoding='async';image.onload=()=>generation++;image.src='./src/assets/art/'+name+'.webp';images.set(name,image);}
  function ready(name){const image=images.get(name);return image?.complete&&image.naturalWidth>0?image:null;}
  function sprite(g,name,x,y,width,height,flip=false,angle=0){const image=ready(name);if(!image)return false;g.save();g.translate(x,y);g.rotate(angle);g.scale(flip?-1:1,1);const fit=Math.min(width/image.naturalWidth,height/image.naturalHeight),w=image.naturalWidth*fit,h=image.naturalHeight*fit;g.drawImage(image,-w/2,-h,w,h);g.restore();return true;}
  const fallbackHero=drawCharacter, fallbackCreature=drawCreature;
  let lastPosition=null, facing=false;
  drawCharacter=function(g,x,y,time){if(lastPosition&&Math.abs(x-lastPosition.x)>.15)facing=x<lastPosition.x;const moving=lastPosition&&Math.hypot(x-lastPosition.x,y-lastPosition.y)>.08;lastPosition={x,y};const name='hero-'+selectedPortrait().id;if(!ready(name)){fallbackHero(g,x,y,time);return;}g.save();g.fillStyle='#092b2e88';g.beginPath();g.ellipse(x,y+8,23,8,0,0,Math.PI*2);g.fill();g.strokeStyle='#dcbd7655';g.lineWidth=1;g.beginPath();g.ellipse(x,y+8,27,10,0,0,Math.PI*2);g.stroke();const bob=moving?Math.abs(Math.sin(time*11))*3:Math.sin(time*2.2)*.7;sprite(g,name,x,y+9-bob,66,86,facing,moving?Math.sin(time*11)*.025:0);g.restore();};
  drawCreature=function(g,x,y,size,color,pet=false){const name=pet?'creature-fox':mapIndex===0?'creature-wolf':mapIndex===1?'creature-treant':null;if(!name||!ready(name)){fallbackCreature(g,x,y,size,color,pet);return;}g.fillStyle='#072a2d70';g.beginPath();g.ellipse(x,y+10,size*1.1,6,0,0,Math.PI*2);g.fill();sprite(g,name,x,y+11,pet?48:mapIndex===1?51:65,pet?46:mapIndex===1?63:53);};
  drawPet=function(g,x,y,time){if(!p.activePet)return;const name=p.activePet==='fox'?'creature-fox':null;if(!name||!ready(name)){fallbackCreature(g,x-38,y+Math.sin(time*3)*3,13,'#d7be87',true);return;}g.fillStyle='#062b2b60';g.beginPath();g.ellipse(x-39,y+6,15,5,0,0,Math.PI*2);g.fill();sprite(g,name,x-39,y+7+Math.sin(time*3)*2,45,44);};
  let groundCache=null, cacheKey='';
  function floor(){const key=mapIndex+':'+generation;if(groundCache&&cacheKey===key)return groundCache;cacheKey=key;const canvas=document.createElement('canvas');canvas.width=1500;canvas.height=900;const g=canvas.getContext('2d');g.fillStyle='#365f52';g.fillRect(0,0,1500,900);const texture=ready('forest-floor');if(texture){g.drawImage(texture,0,0,1500,900);g.fillStyle='#1b575b25';g.fillRect(0,0,1500,900);}const wash=g.createLinearGradient(0,0,0,900);wash.addColorStop(0,'#092f3a45');wash.addColorStop(.5,'#63a59000');wash.addColorStop(1,'#083b3550');g.fillStyle=wash;g.fillRect(0,0,1500,900);
  // A quiet stone trail leaves the landmarks and movement field readable.
  g.beginPath();g.moveTo(-30,510);g.bezierCurveTo(310,360,500,510,745,340);g.bezierCurveTo(1040,180,1190,430,1530,250);g.lineCap='round';g.lineWidth=85;g.strokeStyle='#b7bf9540';g.stroke();g.lineWidth=46;g.strokeStyle='#d0cbaa38';g.stroke();for(let i=0;i<55;i++){const x=i*29-30,y=440-x*.10+Math.sin(i*.24)*55;g.save();g.translate(x,y);g.rotate(seeded(i+580));g.fillStyle='#dbd6b225';g.beginPath();g.ellipse(0,0,9+seeded(i+780)*10,4,0,0,Math.PI*2);g.fill();g.restore();}
  if(mapIndex>=2){g.fillStyle=['','','#1d153d77','#2e9baa35','#5d355c55'][mapIndex];g.fillRect(0,0,1500,900);}groundCache=canvas;return canvas;}
  let propCache=[],propMap=-1;
  const props=()=>{if(propMap===mapIndex)return propCache;propMap=mapIndex;const objects=[];for(let i=0;i<43;i++){const x=seeded(i+51)*1500,y=seeded(i+81)*900;if(Math.abs(y-(480-x*.12))<75||currentPoints().some(point=>Math.hypot(point.x-x,point.y-y)<110))continue;objects.push({x,y,kind:i%5===0?'rock':mapIndex<2?'bamboo':i%2?'rock':'grass',scale:.65+seeded(i+101)*.55});}propCache=objects;return objects;};
  function drawProp(g,item,time){const isTree=item.kind==='bamboo',width=(isTree?98:item.kind==='rock'?66:50)*item.scale,height=(isTree?132:item.kind==='rock'?42:32)*item.scale;g.save();if(isTree&&Math.abs(p.position.x-item.x)<width*.55&&p.position.y<item.y&&p.position.y>item.y-height)g.globalAlpha=.45;sprite(g,'prop-'+item.kind,item.x+(isTree?Math.sin(time*.65+item.x)*1.2:0),item.y,width,height,false,isTree?Math.sin(time*.6+item.x)*.008:0);g.restore();}
  drawGround=function(g,time){g.drawImage(floor(),0,0);};
  drawLandmarks=function(g,time){for(const point of currentPoints()){const visited=p.exploration.visited[Progression.key(mapIndex,point.id)],near=Math.hypot(point.x-p.position.x,point.y-p.position.y)<100;g.save();g.translate(point.x,point.y);g.strokeStyle=near?'#f2d89c':'#8dd9be85';g.fillStyle='#164c4a66';g.lineWidth=near?2:1;g.beginPath();g.ellipse(0,10,point.kind==='ruins'?50:32,12,0,0,Math.PI*2);g.fill();g.stroke();if(point.kind==='spring'){g.fillStyle='#69c6c4a8';g.beginPath();g.ellipse(0,6,29,12,0,0,Math.PI*2);g.fill();for(let i=0;i<3;i++){g.globalAlpha=.6-i*.14;g.strokeStyle='#b8efde';g.beginPath();g.ellipse(0,5,12+((time*6+i*8)%20),4+((time*2+i*2)%7),0,0,Math.PI*2);g.stroke();}g.globalAlpha=1;}else if(point.kind==='herbs'){sprite(g,'prop-grass',0,12+Math.sin(time*2)*1.1,58,43);}else if(point.kind==='ore'){sprite(g,'prop-rock',0,15,73,49);}else{sprite(g,'prop-pavilion',0,15,118,100);g.fillStyle='#f6dc9390';g.beginPath();g.arc(0,-32,2+Math.sin(time*2),0,Math.PI*2);g.fill();}const labelY=point.kind==='ruins'?-100:point.kind==='ore'?-49:-46;g.font='11px serif';g.textAlign='center';g.fillStyle='#0e3038da';g.beginPath();g.roundRect(-40,labelY-14,80,23,6);g.fill();g.fillStyle=near?'#f7dfa6':visited?'#b2e5ce':'#d5dac0';g.fillText(point.name,0,labelY+2);g.restore();}};
  function projectile(g,pr){if(pr.companion&&typeof drawCompanionProjectile==='function'){drawCompanionProjectile(g,pr);return;}const dx=pr.target.x-pr.x,dy=pr.target.y-pr.y,angle=Math.atan2(dy,dx);g.save();g.translate(pr.x,pr.y);g.rotate(angle);g.shadowBlur=12;g.shadowColor=pr.kind==='fire'?'#ed9d4c':'#9cdfd9';if(pr.kind==='fire'){const glow=g.createRadialGradient(0,0,1,0,0,15);glow.addColorStop(0,'#fff4b8');glow.addColorStop(.35,'#ffb050');glow.addColorStop(1,'#d75d2600');g.fillStyle=glow;g.beginPath();g.arc(0,0,15,0,Math.PI*2);g.fill();g.strokeStyle='#e9925666';g.lineWidth=5;g.beginPath();g.moveTo(-30,0);g.lineTo(-5,0);g.stroke();}else{g.strokeStyle='#8cdec45c';g.lineWidth=6;g.beginPath();g.moveTo(-36,0);g.lineTo(0,0);g.stroke();g.fillStyle='#e7fff8';g.beginPath();g.moveTo(15,0);g.lineTo(-12,-3);g.lineTo(-12,3);g.closePath();g.fill();g.strokeStyle='#e4c985';g.lineWidth=2;g.beginPath();g.moveTo(-10,-6);g.lineTo(-10,6);g.moveTo(-18,0);g.lineTo(-10,0);g.stroke();}g.restore();}
  function effect(g,e,time){const life=clamp(e.t,0,1),radius=Progression.effectRadius(e.t);g.save();g.translate(e.x,e.y-12);g.globalAlpha=life;if(e.kind==='sword'){g.rotate(-.6);g.strokeStyle='#e6fff1';g.lineWidth=3;g.beginPath();g.arc(0,0,27+radius*.3,-1.8,.4);g.stroke();g.strokeStyle='#d5c38b';g.lineWidth=1;g.beginPath();g.arc(0,0,32+radius*.3,-1.8,.4);g.stroke();}else if(e.kind==='fire'){for(let i=0;i<9;i++){const angle=i*Math.PI*2/9;g.fillStyle=i%2?'#ed9a4b':'#ffda85';g.beginPath();g.arc(Math.cos(angle)*radius*.45,Math.sin(angle)*radius*.3,Math.max(1,life*5),0,Math.PI*2);g.fill();}}else if(e.kind==='heal'){g.strokeStyle='#9aedd199';g.lineWidth=2;g.beginPath();g.ellipse(0,19,radius*.6,radius*.19,0,0,Math.PI*2);g.stroke();for(let i=0;i<6;i++){const angle=i*Math.PI/3+time;g.save();g.translate(Math.cos(angle)*22,Math.sin(angle)*12-(1-life)*35);g.rotate(angle);g.fillStyle='#9de5b7';g.beginPath();g.ellipse(0,0,3,7,0,0,Math.PI*2);g.fill();g.restore();}}else{g.strokeStyle=e.kind==='break'?'#f7d895':'#a9e5db';g.lineWidth=e.kind==='break'?4:1.5;g.beginPath();g.arc(0,0,radius,0,Math.PI*2);g.stroke();if(e.kind==='break'){g.rotate(time*.4);g.strokeRect(-radius*.7,-radius*.7,radius*1.4,radius*1.4);}}g.restore();}
  const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  drawScene=function(g,W,H,time){if(reducedMotion)time=0;const zoom=Math.max(W/850,H/490),viewW=W/zoom,viewH=H/zoom;cam.x=clamp(p.position.x-viewW/2,0,1500-viewW);cam.y=clamp(p.position.y-viewH/2,0,900-viewH);g.save();g.scale(zoom,zoom);g.translate(-cam.x,-cam.y);drawGround(g,time);drawLandmarks(g,time);const actors=props().map(item=>({y:item.y,draw:()=>drawProp(g,item,time)}));for(const e of enemies){actors.push({y:e.y,draw:()=>{g.save();if(e.hit>0){g.globalAlpha=.65;g.translate(Math.sin(time*70)*2,0);}drawCreature(g,e.x,e.y-6+Math.sin(time*3+e.x)*1.4,20,'#769481');g.restore();const labelY=e.y-(mapIndex===1?69:58);g.fillStyle='#0b2832bd';g.beginPath();g.roundRect(e.x-31,labelY-20,62,23,5);g.fill();g.font='10px serif';g.textAlign='center';g.fillStyle='#e7ddb9';g.fillText(e.name,e.x,labelY-9);g.fillStyle='#19342b';g.fillRect(e.x-25,labelY-3,50,4);g.fillStyle='#d48b77';g.fillRect(e.x-25,labelY-3,50*clamp(e.hp/e.maxHp,0,1),4);}});}actors.push({y:p.position.y-1,draw:()=>drawPet(g,p.position.x,p.position.y,time)});actors.push({y:p.position.y,draw:()=>drawCharacter(g,p.position.x,p.position.y,time)});actors.sort((a,b)=>a.y-b.y);for(const actor of actors)actor.draw();for(const pr of projectiles)projectile(g,pr);for(const e of effects)effect(g,e,time);
  if(destination){g.strokeStyle='#f5d393b8';g.lineWidth=1.5;g.beginPath();g.ellipse(destination.x,destination.y,13+Math.sin(time*5)*2,6,0,0,Math.PI*2);g.stroke();g.beginPath();g.moveTo(destination.x-5,destination.y);g.lineTo(destination.x+5,destination.y);g.moveTo(destination.x,destination.y-5);g.lineTo(destination.x,destination.y+5);g.stroke();}
  // A bounded atmospheric pass adds movement without per-frame textures or filters.
  for(let i=0;i<10;i++){const x=cam.x+((i*137+time*(5+i%3))%viewW),y=cam.y+((i*79+Math.sin(time*.5+i)*12)%viewH);g.save();g.translate(x,y);g.rotate(time*.3+i);g.fillStyle=i%3?'#c2d0a13b':'#f1d79170';g.beginPath();g.ellipse(0,0,2,5,0,0,Math.PI*2);g.fill();g.restore();}const fog=g.createLinearGradient(0,cam.y,0,cam.y+viewH*.28);fog.addColorStop(0,'#d4e6d21a');fog.addColorStop(1,'#d4e6d200');g.fillStyle=fog;g.fillRect(cam.x,cam.y,viewW,viewH*.28);g.restore();};
  return {ready};
})();
