'use strict';
(function(){
 const world=document.querySelector('.world'),footer=document.createElement('div');footer.className='battle-controls';world.classList.add('compact-battle');world.append(footer);
 footer.append(document.querySelector('.battle-hud'),document.querySelector('.world-hotkeys'));
 const tools=document.createElement('div');tools.className='battle-control-tools';tools.innerHTML='<button type="button" aria-label="配置戰鬥技能" title="配置技能">⚙</button><button type="button" aria-label="收合戰鬥介面" aria-expanded="true" title="收合介面">⌄</button>';footer.append(tools);
 tools.children[0].onclick=showBattleSkills;tools.children[1].onclick=()=>{const compact=world.classList.toggle('hud-folded');tools.children[1].textContent=compact?'⌃':'⌄';tools.children[1].setAttribute('aria-expanded',String(!compact));tools.children[1].setAttribute('aria-label',compact?'展開戰鬥介面':'收合戰鬥介面');};
 const fold=document.createElement('button');fold.className='companion-fold';fold.textContent='‹';fold.setAttribute('aria-label','收合伙伴列');fold.setAttribute('aria-expanded','true');world.append(fold);fold.onclick=()=>{const hidden=world.classList.toggle('companions-folded');fold.textContent=hidden?'›':'‹';fold.setAttribute('aria-label',hidden?'展開伙伴列':'收合伙伴列');fold.setAttribute('aria-expanded',String(!hidden));};
 const mini=document.createElement('button');mini.className='battle-minimap';mini.setAttribute('aria-label','小地圖：選擇境界與地圖');mini.title='點擊小地圖傳送';mini.innerHTML='<canvas width="144" height="144" aria-hidden="true"></canvas><span>地圖 ⌕</span>';world.append(mini);mini.onclick=()=>showBattleMaps(MAPS[mapIndex].level);
 function dot(g,x,y,color,r){g.fillStyle=color;g.beginPath();g.arc(8+x/1500*128,8+y/900*128,r,0,Math.PI*2);g.fill();}
 function renderMini(){if(!p)return;const g=mini.querySelector('canvas').getContext('2d');g.clearRect(0,0,144,144);g.fillStyle='#163d3d';g.fillRect(0,0,144,144);g.strokeStyle='#8bbbaa33';g.lineWidth=1;for(let i=24;i<144;i+=24){g.beginPath();g.moveTo(i,0);g.lineTo(i,144);g.moveTo(0,i);g.lineTo(144,i);g.stroke();}for(const point of currentPoints())dot(g,point.x,point.y,'#e3c780',3);for(const enemy of enemies)if(enemy.hp>0)dot(g,enemy.x,enemy.y,'#e4837a',2.4);dot(g,p.position.x,p.position.y,'#a0ffe1',5);mini.title=MAPS[mapIndex].name+' · 金色地點／紅色敵人／綠色人物 · 點擊選地圖';}
 const ui=renderUI;renderUI=function(){ui();renderMini();};
 function showBattleSkills(){const h=HighRealms.normalize(p),choices=['attack','flame','sword','heal',...HighRealmData.skills.map(s=>s.id)].filter(id=>HighRealms.learned(p,id));modal('戰鬥技能 · 八格配置','<p>選擇已學會的技能；重複配置會交換欄位。變更即儲存。</p><div class="v21-slot-grid">'+h.slots.map((id,i)=>'<label>第 '+(i+1)+' 格<select data-battle-slot="'+i+'" aria-label="技能第 '+(i+1)+' 格"><option value="">空欄位</option>'+choices.map(key=>'<option value="'+key+'" '+(key===id?'selected':'')+'>'+v21SkillMeta(key).name+'</option>').join('')+'</select></label>').join('')+'</div>',[{text:'完成',fn:()=>{closeModal();renderV21Hotbar();}}]);document.querySelectorAll('[data-battle-slot]').forEach(b=>b.onchange=()=>{HighRealms.assign(p,Number(b.dataset.battleSlot),b.value);save(true);renderV21Hotbar();showBattleSkills();});}
 function showBattleMaps(level){const levels=[...new Set(MAPS.map(m=>m.level))].sort((a,b)=>a-b);modal('萬界傳送 · 選擇地圖','<div class="realm-map-tabs" role="tablist" aria-label="小地圖境界">'+levels.map(n=>'<button class="btn '+(n===level?'gold':'line')+'" role="tab" aria-selected="'+(n===level)+'" data-battle-realm="'+n+'">'+REALMS[n].name+'</button>').join('')+'</div><div class="battle-map-options">'+MAPS.map((m,i)=>({m,i})).filter(x=>x.m.level===level).map(({m,i})=>{const locked=p.realm<m.level||(p.realm===m.level&&(p.stage||0)<(m.stage||0))||(m.finished&&!p.finished);return '<button class="btn line" data-battle-map="'+i+'" '+(locked?'disabled':'')+'><strong>'+escapeHTML(m.name)+'</strong><small>'+ (locked?(m.finished?'完成渡劫後解鎖':'境界未足'):i===mapIndex?'目前所在地':'點擊前往')+'</small></button>';}).join('')+'</div>',[{text:'返回戰鬥'}]);document.querySelectorAll('[data-battle-realm]').forEach(b=>b.onclick=()=>showBattleMaps(Number(b.dataset.battleRealm)));document.querySelectorAll('[data-battle-map]').forEach(b=>b.onclick=()=>{if(switchMap(Number(b.dataset.battleMap))!==false){closeModal();renderAll();save(true);}});const active=document.querySelector('[data-battle-realm="'+level+'"]');active.parentElement.scrollLeft=Math.max(0,active.offsetLeft-active.parentElement.offsetLeft-(active.parentElement.clientWidth-active.offsetWidth)/2);}
})();
