'use strict';
ITEMS.trib.desc='突破時手動放入最多兩顆：第一顆 +25%，第二顆再 +10% 成功率';
ITEMS.celestialPill={id:'celestialPill',name:'天靈丹',icon:'⚗',type:'pill',rarity:3,price:0,craftOnly:true,desc:'僅可煉製。突破成功率 +15%，天雷傷害減半；每次最多一顆。'};
const breakthroughIcon=characterIcon;
characterIcon=function(id,...args){return id==='celestialPill'?'./src/assets/breakthrough/celestial-pill.png':breakthroughIcon(id,...args)};
let breakthroughBusy=false;
breakthrough=function(){
 if(breakthroughBusy)return;if(p.finished)return note('已飛升，功參造化');if(p.qi<qiMax())return note('靈氣尚未圓滿');
 const sourceRealm=p.realm,sourceStage=p.stage;let trib=0,celestial=0;
 const draw=()=>{const q=BreakthroughSystem.quote(p,REALMS,trib,celestial);
 modal(q.thunder?'天雷渡劫 · 衝擊瓶頸':'衝擊瓶頸',`<p>當前境界：<b>${realmLabel()}</b></p><p>突破成功率：<strong id="tribChance">${Math.round(q.chance*100)}%</strong>（基礎 ${Math.round(q.base*100)}%）</p><div class="trib-slots"><label>護劫丹 · 持有 ${count('trib')} 顆<select id="tribQuantity" aria-label="護劫丹數量">${[0,1,2].map(n=>`<option value="${n}" ${n===trib?'selected':''} ${n>count('trib')?'disabled':''}>${n===0?'空白 · 不放入':'放入 '+n+' 顆'}</option>`).join('')}</select></label><label><img src="./src/assets/breakthrough/celestial-pill.png" alt="">天靈丹 · 持有 ${count('celestialPill')} 顆<select id="celestialQuantity" aria-label="天靈丹數量"><option value="0">空白 · 不放入</option><option value="1" ${celestial?'selected':''} ${count('celestialPill')<1?'disabled':''}>放入 1 顆</option></select></label></div><p class="muted">護劫丹：第一顆 +25%，第二顆 +10%；天靈丹 +15% 並減半雷傷。確認突破後才消耗，成功或失敗均消耗。</p><p>${q.thunder?'天雷 '+q.bolts+' 道 · 雷傷為最大氣血 '+Math.round(q.damage*100)+'%（最低保留 1 氣血）。':'靈氣圓滿，可衝擊下一階。'}</p><p class="muted">天靈丹只能於「世外洞府」煉製，不在萬寶閣販售。</p>`,[{text:'暫緩渡劫'},{text:'開始突破',style:'gold',fn:()=>{
 if(breakthroughBusy||p.realm!==sourceRealm||p.stage!==sourceStage)return;const result=BreakthroughSystem.attempt(p,REALMS,qiMax(),()=>stats(),trib,celestial);if(!result.ok)return note('丹藥或靈氣不足，請重新選擇');
 breakthroughBusy=true;closeModal();autoMeditateTimer=0;save(true);renderAll();ensureGameLoop();
 log(result.success?'突破成功，晉入 '+realmLabel():'渡劫失利，靈氣與氣血有所損',result.success?'good':'bad');
 playBreakthrough(result,()=>{breakthroughBusy=false;const s=stats();modal(result.success?(p.finished?'羽化登仙':'道境已成'):'突破失敗',`<div class="realm-seal">${result.success?'成':'劫'}</div><p>${result.success?'晉入 '+realmLabel():'心魔反噬，保留 72% 靈氣。可調息後再次挑戰。'}</p><p>消耗護劫丹 ${trib} 顆、天靈丹 ${celestial} 顆${result.thunder?' · 天雷傷害 '+fmt(result.thunderDamage):''}</p><p>戰力 ${fmt(s.combat)} · 氣血 ${fmt(p.hp)} / ${fmt(s.hp)}</p>`,[{text:'繼續問道',style:'gold'}]);});
 }}]);$('tribQuantity').onchange=e=>{trib=Number(e.target.value);draw()};$('celestialQuantity').onchange=e=>{celestial=Number(e.target.value);draw()};};draw();
};
function playBreakthrough(result,done){const overlay=document.createElement('div');overlay.className='trib-cinematic '+(result.success?'trib-success':'trib-failure')+' trib-style-'+result.asset;overlay.setAttribute('role','status');overlay.setAttribute('aria-label','突破動畫播放中');const name=REALMS[result.asset].name;overlay.innerHTML=`<div class="trib-aura"></div><img class="trib-art" src="./src/assets/breakthrough/${result.success?'success':'failure'}-${result.asset}.png" alt="${name}${result.success?'突破':'反噬'}特效">${Array.from({length:result.bolts},(_,i)=>`<img class="trib-bolt" style="--strike:${i};left:${25+i%3*22}%" src="./src/assets/breakthrough/thunder.png" alt="">`).join('')}<strong>${result.thunder?'天雷淬體':'靈氣沖霄'} · ${name}</strong><span>${result.success?'道心凝聚 · 破境':'心魔反噬 · 道心未散'}</span>`;document.body.append(overlay);setTimeout(()=>{overlay.remove();done()},result.duration);}
$('breakthrough').onclick=()=>breakthrough();
const tribItem=showItem;showItem=function(id){if(id==='trib'){tribItem(id);const b=$('modalActions').lastElementChild;if(b){b.textContent='前往突破';b.onclick=()=>breakthrough();}return;}if(id!=='celestialPill')return tribItem(id);if(!count(id))return;modal(ITEMS[id].name,`<img class="character-detail-icon" src="${characterIcon(id)}" alt=""><p>${ITEMS[id].desc}</p><p>持有 ${count(id)} 顆。於突破面板選擇放入，背包中不會直接消耗。</p>`,[{text:'關閉'},{text:'前往突破',style:'gold',fn:()=>breakthrough()}]);};
const tribRenderUI=renderUI;renderUI=function(){tribRenderUI();if(p)$('breakChance').textContent=p.finished?'已飛升成仙':'突破基礎成功率 '+Math.round(BreakthroughSystem.quote(p,REALMS).chance*100)+'% · 可放入丹藥';};
const tribAbode=renderAbode;renderAbode=function(){tribAbode();const anchor=$('alchemyTrib');if(!anchor)return;const box=document.createElement('div');box.className='celestial-recipe';box.innerHTML='<h3><img src="./src/assets/breakthrough/celestial-pill.png" alt="">天靈丹 · 僅限煉製</h3><p>靈草 ×20、護劫丹 ×2、靈石 ×1,200</p><p>突破 +15% 成功率、天雷傷害減半</p><button class="btn gold" id="craftCelestial">煉製天靈丹</button>';anchor.after(box);$('craftCelestial').onclick=()=>{const r=BreakthroughSystem.craft(p,(player,id)=>CharacterSystem.canStore(player,id,ITEMS));if(!r.ok)return note(r.reason==='full'?'丹藥背包已滿':'靈草、護劫丹或靈石不足');save(true);renderAll();modal('丹成 · 天靈丹','<p>成功煉製天靈丹 ×1，已放入丹藥背包。</p>',[{text:'收下',style:'gold'}]);};};

const tribRealm=renderRealm;renderRealm=function(){tribRealm();const row=Array.from($('panelContent').querySelectorAll('.rowline')).find(x=>x.textContent.startsWith('突破成功率'));if(row)row.querySelector('b').textContent=Math.round(BreakthroughSystem.quote(p,REALMS).chance*100)+'% · 未放入丹藥';};
