'use strict';
let characterCategory='equipment',characterSort='quality',characterPage=0;
const characterAssets='./src/assets/art/';
const characterIcons={head:0,earrings:1,inner:2,weapon:3,legs:4,necklace:5,bracelet:6,robe:7,ring:8,boots:9,pill:10,heal:11,trib:12,wood:13,herb:14,fang:15};
const characterPetIcons={fox:0,turtle:1,falcon:2,dragon:3,mirror:4,dagger:5,bell:6,gourd:7};
function characterIcon(id,companion=false){const it=ITEMS[id];const index=companion?characterPetIcons[id]:characterIcons[it?.slot||id];if(companion&&index===undefined)return characterAssets+'icon-pearl.webp';return characterAssets+'character-'+(companion?'companion-':'item-')+(index??14)+'.webp'}
for(const it of Object.values(ITEMS))it.icon='<img width="36" height="36" style="object-fit:contain" alt="" src="'+characterIcon(it.id)+'">';
const characterScreen=document.createElement('section');characterScreen.id='characterScreen';characterScreen.className='hidden';characterScreen.setAttribute('aria-label','角色管理');characterScreen.innerHTML='<div class="character-shell"><header class="character-header"><button class="btn line" id="characterBack">← 返回</button><h1>角色</h1><button class="btn line" id="characterPortrait">仙容</button></header><div id="characterSummary"></div><div class="character-stage"><aside id="characterPets" class="character-companions"></aside><div class="character-doll"><div id="characterSlotsLeft" class="doll-slots"></div><div class="doll-figure"><div class="doll-halo"></div><img id="characterBody" alt="人物全身立繪"><div id="characterAppearance"></div></div><div id="characterSlotsRight" class="doll-slots"></div></div><aside id="characterTreasures" class="character-companions"></aside></div><section class="character-bag"><div class="character-bag-heading"><h2>乾坤背包</h2><select id="characterSort" aria-label="背包排序"><option value="quality">依品質</option><option value="type">依類型</option><option value="name">依名稱</option></select><button class="btn line small" id="characterAcquire">尋寶閣</button></div><div id="characterCategories" class="character-categories"></div><p id="characterCapacity"></p><div id="characterItems" class="character-items" tabindex="0" aria-label="背包物品"></div><div class="character-pagination"><button class="btn line" id="characterPrevious">← 上頁</button><span id="characterPageLabel"></span><button class="btn line" id="characterNext">下頁 →</button></div></section><p class="character-footnote">裝備屬性即時生效 · 主靈寵與本命法寶提供加成 · 出戰編隊與山海戰鬥同步</p></div>';
document.body.append(characterScreen);
function characterIsOpen(){return !characterScreen.classList.contains('hidden')}
function openCharacter(entry='character'){if(!p)return;const categories={inventory:'equipment',equipment:'equipment',pets:'pets',treasures:'treasures'};if(categories[entry]){characterCategory=categories[entry];characterPage=0}CharacterSystem.normalize(p);characterScreen.classList.remove('hidden');document.body.classList.add('character-open');document.documentElement.classList.add('character-open');$('game').classList.add('character-covered');keys.clear();moveTouch=null;renderCharacter();characterScreen.scrollTop=0;$('characterBack').focus({preventScroll:true});if(['inventory','pets','treasures'].includes(entry))characterScreen.querySelector('.character-bag').scrollIntoView({block:'start'});document.querySelectorAll('#nav button[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===entry))}
function closeCharacter(){characterScreen.classList.add('hidden');document.body.classList.remove('character-open');document.documentElement.classList.remove('character-open');$('game').classList.remove('character-covered');keys.clear();moveTouch=null;lastTime=performance.now();renderUI();save(true);$('portraitPicker').focus()}
$('characterBack').onclick=closeCharacter;
const oldPortraitPicker=$('portraitPicker').onclick;
$('characterPortrait').onclick=oldPortraitPicker;
$('portraitPicker').onclick=()=>openCharacter();
const characterSyncPortrait=syncPortrait;syncPortrait=function(){characterSyncPortrait();$('portraitPicker').title='開啟角色管理';$('portraitPicker').setAttribute('aria-label','開啟角色管理')};
NAV.unshift(['character','', '角色']);
const characterChooseTab=chooseTab;chooseTab=function(id){if(['character','inventory','equipment','pets','treasures'].includes(id)){openCharacter(id);return}return characterChooseTab(id)};
const characterNav=document.createElement('button');characterNav.dataset.tab='character';characterNav.innerHTML='<span class="ni"><img src="'+characterAssets+'portrait-sword.webp" alt=""></span>角色';characterNav.onclick=()=>chooseTab('character');$('nav').prepend(characterNav);
function renderCharacterSummary(){if(!characterIsOpen()||!p)return;const s=stats();$('characterSummary').innerHTML='<div><h2>'+escapeHTML(p.name)+'</h2><span>'+realmLabel()+' · '+root().name+'</span></div><strong>戰力 '+fmt(s.combat)+'</strong><div class="character-vitals"><span>氣血 '+fmt(p.hp)+' / '+fmt(s.hp)+'</span><span>真元 '+fmt(p.mp)+' / '+fmt(s.mp)+'</span><span>攻擊 '+fmt(s.atk)+'</span><span>防禦 '+fmt(s.def)+'</span></div><div class="character-qi"><span>修為 '+fmt(p.qi)+' / '+fmt(qiMax())+'</span><progress max="'+qiMax()+'" value="'+p.qi+'"></progress></div>'}
function characterQuality(rarity=0){return ['凡品','靈品','珍品','仙品'][Math.min(3,rarity)]}
function renderCharacter(){if(!characterIsOpen()||!p)return;renderCharacterSummary();$('characterBody').src=characterAssets+'character-'+(p.equipment.robe?'outfit-':'body-')+selectedPortrait().id+'.webp';
 const slot=(key)=>{const id=p.equipment[key],it=ITEMS[id];return '<button class="character-slot '+(it?'rare'+(it.rarity||0):'')+'" data-character-slot="'+key+'" aria-label="'+CharacterSystem.slots[key]+' · '+(it?.name||'空欄位')+'"><img src="'+characterIcon(id||key)+'" alt="" '+(!id?'class="empty"':'')+'><span>'+CharacterSystem.slots[key]+'</span><small>'+(it?it.name:'未裝備')+'</small></button>'};
 $('characterSlotsLeft').innerHTML=['head','earrings','inner','weapon','legs'].map(slot).join('');$('characterSlotsRight').innerHTML=['necklace','bracelet','robe','ring','boots'].map(slot).join('');
 // Separate equipment appearance layer, ready for future dedicated costume sprites.
 $('characterAppearance').innerHTML=['inner','legs','robe','head','weapon','necklace','earrings','bracelet','ring','boots'].filter(k=>p.equipment[k]).map(k=>'<img class="appearance-'+k+'" src="'+characterIcon(p.equipment[k])+'" alt="'+ITEMS[p.equipment[k]]?.name+'">').join('');$('characterBody').dataset.outer=p.equipment.robe||'';$('characterAppearance').dataset.outer=p.equipment.robe||'';$('characterAppearance').dataset.portrait=selectedPortrait().id;
 for(const [type,list,target]of [['pet',PETS,'characterPets'],['treasure',TREASURES,'characterTreasures']]){const owned=list.filter(m=>Companions.owned(p,type+':'+m.id));$(target).innerHTML='<h3>'+(type==='pet'?'靈寵':'法寶')+'</h3><small>'+owned.length+' / '+list.length+'</small>'+owned.map(m=>'<button class="character-companion '+(p.companions.deployed.includes(type+':'+m.id)?'deployed':'')+'" data-character-unit="'+type+':'+m.id+'" aria-label="'+m.name+'"><img src="'+characterIcon(m.id,true)+'" alt=""><span>'+m.name+'</span><small>'+(type==='pet'?'Lv.'+p.levelPet[m.id]:'Lv.1')+' · '+characterQuality(m.rarity)+'</small></button>').join('')}
 renderCharacterBag();characterScreen.querySelectorAll('[data-character-slot]').forEach(b=>b.onclick=()=>showCharacterSlot(b.dataset.characterSlot));characterScreen.querySelectorAll('[data-character-unit]').forEach(b=>b.onclick=()=>showCharacterUnit(b.dataset.characterUnit));
}
function renderCharacterBag(){const cat=characterCategory,units=cat==='pets'||cat==='treasures',catalog=units?Object.fromEntries((cat==='pets'?PETS:TREASURES).map((m,i)=>[m.id,m])):ITEMS,items=CharacterSystem.sorted(p,cat,characterSort,catalog),capacity=CharacterSystem.capacity(p,cat),pages=Math.ceil(Math.max(capacity,items.length)/20);characterPage=Math.min(characterPage,pages-1);$('characterCategories').innerHTML=Object.entries(CharacterSystem.categories).map(([id,name])=>'<button class="btn '+(cat===id?'gold':'line')+'" data-character-category="'+id+'" aria-pressed="'+(cat===id)+'"><img src="'+characterIcon(id==='equipment'?'sword':id==='consumables'?'pill':id==='materials'?'herb':id==='pets'?'fox':'mirror',id==='pets'||id==='treasures')+'" alt="">'+name+'</button>').join('');$('characterCapacity').textContent=items.length+' / '+capacity+' 格 · 五類合計 '+Object.keys(CharacterSystem.categories).reduce((n,k)=>n+CharacterSystem.capacity(p,k),0)+' 格'+(items.length>capacity?' · 舊物品完整保留，請先整理':'');$('characterPageLabel').textContent=(characterPage+1)+' / '+pages;$('characterPrevious').disabled=characterPage===0;$('characterNext').disabled=characterPage===pages-1;
 $('characterItems').innerHTML=Array.from({length:20},(_,i)=>{const entry=items[characterPage*20+i];if(!entry)return '<div class="character-item empty" aria-hidden="true"></div>';const it=catalog[entry.id],label=it?.name||entry.id;return '<button class="character-item rare'+(it?.rarity||0)+'" data-character-item="'+entry.id+'" aria-label="'+escapeHTML(label)+' ×'+entry.count+'"><img src="'+characterIcon(entry.id,units)+'" alt=""><span>'+escapeHTML(label)+'</span><em>×'+entry.count+'</em></button>'}).join('');
 $('characterCategories').querySelectorAll('button').forEach(b=>b.onclick=()=>{characterCategory=b.dataset.characterCategory;characterPage=0;renderCharacterBag()});$('characterItems').querySelectorAll('button').forEach(b=>b.onclick=()=>units?showCharacterUnit((cat==='pets'?'pet:':'treasure:')+b.dataset.characterItem):showItem(b.dataset.characterItem));
}
$('characterSort').onchange=()=>{characterSort=$('characterSort').value;characterPage=0;renderCharacterBag()};$('characterPrevious').onclick=()=>{characterPage--;renderCharacterBag()};$('characterNext').onclick=()=>{characterPage++;renderCharacterBag()};
function finishCharacterMutation(message){p.hp=Math.min(p.hp,stats().hp);p.mp=Math.min(p.mp,stats().mp);closeModal();renderAll();renderCharacter();save(true);note(message)}
function showCharacterSlot(slot){const id=p.equipment[slot],current=ITEMS[id],choices=p.inventory.filter(e=>ITEMS[e.id]?.slot===slot);modal(CharacterSystem.slots[slot],'<p>目前：'+(current?current.name+' · '+characterQuality(current.rarity):'未裝備')+'</p>'+ (current?'<p>'+current.desc+'</p><p>攻擊 +'+(current.atk||0)+' · 防禦 +'+(current.def||0)+' · 氣血 +'+(current.hp||0)+' · 需求 '+REALMS[current.realm||0].name+'</p>':'')+'<div class="character-replacements">'+choices.map(e=>'<button class="btn cyan" data-character-replace="'+e.id+'"><img width="36" src="'+characterIcon(e.id)+'" alt="">'+ITEMS[e.id].name+' ×'+e.count+'</button>').join('')+'</div>'+(!choices.length?'<p>背包沒有可替換裝備，可前往尋寶閣購買。</p>':''),[{text:'關閉'},...(id?[{text:'卸下',fn:()=>{if(!CharacterSystem.unequip(p,slot,ITEMS))return note('裝備背包已滿，無法卸下');finishCharacterMutation('已卸下 '+current.name)}}]:[]),{text:'尋寶閣',style:'gold',fn:()=>showCharacterShop(slot)}]);document.querySelectorAll('[data-character-replace]').forEach(b=>b.onclick=()=>showItem(b.dataset.characterReplace))}
const characterShowItem=showItem;showItem=function(id){const it=ITEMS[id];if(!it){const entry=p.inventory.find(e=>e.id===id);if(entry)modal('未辨識物品','<p>'+escapeHTML(id)+' ×'+entry.count+'</p><p>此物品已保留，等待對應內容更新。</p>',[{text:'關閉'}]);return}characterShowItem(id);$('modalTitle').textContent=it.name;const picture=document.createElement('img');picture.src=characterIcon(id);picture.alt=it.name;picture.className='character-detail-icon';$('modalContent').prepend(picture);if(it.type!=='equip')return;
 const before=stats().combat,old=p.equipment[it.slot];p.equipment[it.slot]=id;const after=stats().combat;p.equipment[it.slot]=old;const info=document.createElement('p');info.className='character-item-stats';info.textContent=characterQuality(it.rarity)+' · '+CharacterSystem.slots[it.slot]+' · 需求 '+REALMS[it.realm||0].name+' · 戰力變化 '+(after-before>=0?'+':'')+(after-before);$('modalContent').prepend(info);const action=$('modalActions').lastElementChild;action.disabled=p.realm<(it.realm||0);action.onclick=()=>{const result=CharacterSystem.equip(p,id,ITEMS);if(!result.ok)return note(result.reason==='full'?'裝備背包已滿':result.reason==='equipped'?'已穿戴相同裝備':'不符合裝備條件');finishCharacterMutation('已裝備 '+it.name)};
};
function showCharacterUnit(key){const [type,id]=key.split(':'),m=companionMeta(key),u=Companions.unit(key);if(!m||!u){modal('尚未辨識的伙伴','<p>'+escapeHTML(id)+'</p><p>既有持有資料完整保留，等待對應內容更新。</p>',[{text:'關閉'}]);return}const owned=Companions.owned(p,key),active=type==='pet'?p.activePet===id:p.activeTreasure===id,deployed=p.companions.deployed.includes(key),level=type==='pet'?p.levelPet[id]||0:owned?1:0;modal(m.name,'<div class="character-unit-detail"><img src="'+characterIcon(id,true)+'" alt="'+m.name+'"><p>'+m.desc+'</p><p>'+characterQuality(m.rarity)+' · 等級 '+level+'</p><p>主選加成：攻擊 +'+((m.atk||0)*Math.max(1,level))+' · 防禦 +'+((m.def||0)*Math.max(1,level))+'</p><p>主動協同攻擊 · CD '+u.cd/1000+' 秒 · '+(deployed?'出戰中':'休息中')+'</p></div>',[{text:'關閉'},...(!owned?[{text:(type==='pet'?'締結靈契':'煉化')+' · '+m.cost+(type==='pet'?' 靈石':' 仙玉'),style:'gold',fn:()=>{if(!CharacterSystem.acquire(p,type,m))return note('資源不足或背包已滿');finishCharacterMutation('已取得 '+m.name)}}]:[{text:deployed?'休息':'出戰',fn:()=>{if(!CharacterSystem.deployment(p,key))return;finishCharacterMutation(deployed?'已休息':'已出戰')}},{text:active?'卸下主選加成':'設為'+(type==='pet'?'主靈寵':'本命法寶'),style:'gold',fn:()=>{if(!CharacterSystem.primary(p,type,active?null:id))return;finishCharacterMutation('主選加成已更新')}},...(type==='pet'?[{text:'升級 · '+level*70+' 靈石',fn:()=>{if(!CharacterSystem.upgrade(p,id))return note(level>=20?'靈寵已達最高等級':'靈石不足');finishCharacterMutation('靈寵已升級')}}]:[])]),{text:'攻擊順序',fn:showCompanionFormation}]);}
function showCharacterShop(slot){const catalog=Object.values(ITEMS).filter(it=>it.type==='equip'&&(!slot||it.slot===slot));modal('尋寶閣 · 法器交易','<p>法器購買直接放入裝備背包，穿戴不另扣費。售價低於購買價。</p><div class="character-shop">'+catalog.map(it=>'<button class="btn line" data-character-buy="'+it.id+'"><img src="'+characterIcon(it.id)+'" alt=""><span>'+it.name+'<small>'+characterQuality(it.rarity)+' · '+it.price*2+' 靈石</small></span></button>').join('')+'</div><h3>靈寵與法寶</h3><div class="character-replacements">'+[...PETS.map(m=>['pet',m]),...TREASURES.map(m=>['treasure',m])].map(([type,m])=>'<button class="btn line" data-character-discover="'+type+':'+m.id+'">'+m.name+'</button>').join('')+'</div>',[{text:'返回'}]);document.querySelectorAll('[data-character-buy]').forEach(b=>b.onclick=()=>{const it=ITEMS[b.dataset.characterBuy],cost=it.price*2;if(p.stones<cost)return note('靈石不足');if(!add(it.id))return;p.stones-=cost;finishCharacterMutation('已購買 '+it.name)});document.querySelectorAll('[data-character-discover]').forEach(b=>b.onclick=()=>showCharacterUnit(b.dataset.characterDiscover))}
$('characterAcquire').onclick=()=>showCharacterShop();
const characterRenderAll=renderAll;renderAll=function(){characterRenderAll();renderCharacter()};
const characterStart=startGame;startGame=function(){const raw=storage.getItem(SAVE);if(raw&&!storage.getItem(SAVE+'_PRE_CHARACTER'))storage.setItem(SAVE+'_PRE_CHARACTER',raw);CharacterSystem.normalize(p);characterScreen.classList.add('hidden');document.body.classList.remove('character-open');document.documentElement.classList.remove('character-open');$('game').classList.remove('character-covered');characterStart()};
setInterval(renderCharacterSummary,500);
document.addEventListener('keydown',event=>{if(!characterIsOpen())return;if(event.key==='Escape'&&$('modal').classList.contains('hidden'))closeCharacter();if(['INPUT','SELECT'].includes(event.target.tagName))return;event.stopImmediatePropagation();keys.clear()},true);
