'use strict';
let companionVolleyAt=0;
const companionMeta=key=>{const [type,id]=key.split(':');return (type==='pet'?PETS:TREASURES).find(u=>u.id===id)};
const companionArt=key=>{const id=key.split(':')[1];const item=typeof EconomyData!=='undefined'&&p?.economy?.instances[id];if(item&&EconomyData.templates[item.baseId])return './src/assets/economy/runtime/'+EconomyData.templates[item.baseId].assetId+'.png';const ids=['fox','turtle','falcon','dragon','mirror','dagger','bell','gourd'];return './src/assets/art/character-companion-'+ids.indexOf(item?.baseId||id)+'.webp'};
const companionImages=new Map();for(const u of Companions.units){const img=new Image();img.src=companionArt(u.key);companionImages.set(u.key,img)};
function companionPosition(key){const i=p.companions.deployed.indexOf(key),angle=-Math.PI+(i%8)*Math.PI/4,ring=Math.floor(i/8);return {x:p.position.x+Math.cos(angle)*(47+ring*24),y:p.position.y-18+Math.sin(angle)*(35+ring*18)}}
function fireCompanion(key,automatic=false){if(!p||!$('modal').classList.contains('hidden'))return false;const now=Date.now();if(!Companions.ready(p,key,now))return false;const enemy=targetNear(330);if(!enemy){if(!automatic)note('妖獸不在御靈攻擊範圍');return false}if(!Companions.launch(p,key,now))return false;const u=Companions.unit(key),meta=companionMeta(key),pos=companionPosition(key),level=key.startsWith('pet:')?p.levelPet[meta.id]:1;const execution=key.startsWith('treasure:')&&(p.economy?.instances[key.split(':')[1]]?.baseId||key.split(':')[1])==='dagger'&&enemy.hp/enemy.maxHp<.2?1.8:1;projectiles.push({...pos,target:enemy,damage:(stats().atk*u.scale+(meta.atk||8)*level)*execution,speed:410,kind:u.kind,companion:key});effects.push({...pos,t:.4,kind:'cast'});companionVolleyAt=now+350;save(true);return true}
function stepCompanions(){if(!p.companions)return;const now=Date.now();if(now>=companionVolleyAt){const key=Companions.next(p,now);if(key)fireCompanion(key,true)}}
(function(){
 const dock=document.createElement('div');dock.className='companion-dock';dock.setAttribute('aria-label','法寶與靈寵出戰');document.querySelector('.world').append(dock);
 function renderDock(){if(!p?.companions)return;const s=p.companions,signature=Companions.deployedKeys(p).join('|');if(dock.dataset.signature!==signature){dock.dataset.signature=signature;dock.innerHTML='<button class="formation-open" title="調整出戰及攻擊順序">御靈 ⚙</button><div class="companion-buttons">'+Companions.deployedKeys(p).map(key=>'<button data-companion="'+key+'"><img alt="" src="'+companionArt(key)+'"><small></small></button>').join('')+'</div>';dock.querySelector('.formation-open').onclick=showCompanionFormation;dock.querySelectorAll('[data-companion]').forEach(b=>b.onclick=()=>fireCompanion(b.dataset.companion))}dock.querySelectorAll('[data-companion]').forEach(b=>{const key=b.dataset.companion,remaining=Math.max(0,(s.cooldowns[key]||0)-Date.now());b.querySelector('small').textContent=remaining?(remaining/1000).toFixed(1)+'s':companionMeta(key).name.slice(0,2);b.classList.toggle('cooling',remaining>0);b.title=companionMeta(key).name+' · '+(remaining?'冷卻 '+(remaining/1000).toFixed(1)+' 秒':'點擊攻擊');b.setAttribute('aria-label',b.title)})}
 const start=startGame;startGame=function(){Companions.normalize(p);start();renderDock()};
 const ui=renderUI;renderUI=function(){ui();renderDock()};
 function companionCards(type){const list=type==='pet'?PETS:TREASURES,s=p.companions;$('panelContent').innerHTML='<button class="btn cyan" id="openFormation">出戰編隊 · 調整攻擊順序</button><p>主靈寵與本命法寶提供原有加成；所有已擁有的都可加入出戰，獨立冷卻。</p><div class="cards">'+list.map(m=>{const key=type+':'+m.id,owned=Companions.owned(p,key),main=(type==='pet'?p.activePet:p.activeTreasure)===m.id;return '<div class="card '+(main?'selected':'')+'"><div class="pet-icon"><img width="42" height="42" src="'+companionArt(key)+'" alt=""></div><h3>'+m.name+'</h3><p>'+m.desc+'</p><p>主動攻擊 · CD '+Companions.unit(key).cd/1000+' 秒'+(type==='pet'?' · 等級 '+(p.levelPet[m.id]||0):'')+'</p><button class="btn '+(main?'gold':'cyan')+'" data-main="'+key+'">'+(owned?(main?'主選加成中':'設為'+(type==='pet'?'主靈寵':'本命法寶')):(type==='pet'?'締結靈契 · '+m.cost+' 靈石':'煉化 · '+m.cost+' 仙玉'))+'</button>'+(owned?'<button class="btn line" data-deploy="'+key+'">'+(s.deployed.includes(key)?'收回出戰':'加入出戰')+'</button>':'')+(owned&&type==='pet'?'<button class="btn line" data-upgrade="'+m.id+'">升級 · '+p.levelPet[m.id]*70+' 靈石</button>':'')+'</div>'}).join('')+'</div>';
 $('openFormation').onclick=showCompanionFormation;
 document.querySelectorAll('[data-main]').forEach(b=>b.onclick=()=>{const key=b.dataset.main,m=companionMeta(key),owned=Companions.owned(p,key);if(!owned){const currency=type==='pet'?'stones':'jade';if(p[currency]<m.cost){note(type==='pet'?'靈石不足':'仙玉不足');return}p[currency]-=m.cost;if(type==='pet')p.levelPet[m.id]=1;else p.ownedTreasures.push(m.id);s.order.push(key);s.deployed.push(key)}if(type==='pet')p.activePet=m.id;else p.activeTreasure=m.id;renderAll();save(true)});
 document.querySelectorAll('[data-deploy]').forEach(b=>b.onclick=()=>{toggleCompanion(b.dataset.deploy);renderAll()});
 document.querySelectorAll('[data-upgrade]').forEach(b=>b.onclick=()=>{const id=b.dataset.upgrade,level=p.levelPet[id];if(level>=20){note('靈寵已達最高等級');return}if(p.stones<level*70){note('靈石不足');return}p.stones-=level*70;p.levelPet[id]++;renderAll();save(true)});
 }
 renderPets=()=>companionCards('pet');renderTreasures=()=>companionCards('treasure');
 const petDrawing=drawPet;drawPet=function(g,x,y,time){if(!p.companions){petDrawing(g,x,y,time);return}for(const key of Companions.deployedKeys(p)){const pos=companionPosition(key),m=companionMeta(key);g.save();g.fillStyle='#092d2ccc';g.strokeStyle=key.startsWith('pet:')?'#8bdac2':'#e6c583';g.lineWidth=1;g.beginPath();g.arc(pos.x,pos.y,14,0,Math.PI*2);g.fill();g.stroke();const art=key==='pet:fox'?BattleArt.ready('creature-fox'):companionImages.get(key);if(art?.complete&&art.naturalWidth>0)g.drawImage(art,pos.x-12,pos.y-12,24,24);else{g.font='21px serif';g.textAlign='center';g.fillText(m.icon,pos.x,pos.y+7)}g.restore()}};
})();
function toggleCompanion(key){const s=p.companions;if(s.deployed.includes(key))s.deployed=s.deployed.filter(k=>k!==key);else if(Companions.owned(p,key))s.deployed.push(key);save(true);renderUI()}
function showCompanionFormation(){const s=p.companions;modal('御靈編隊 · 攻擊順序','<p>按以下順序輪流出手，冷卻中的伙伴會跳過。戰鬥框左側圖示可手動攻擊。</p><button class="btn cyan" id="companionAuto">自動御靈：'+(s.auto?'開':'關')+'</button><div class="formation-list">'+s.order.map((key,i)=>'<div class="formation-row"><img width="30" height="30" alt="" src="'+companionArt(key)+'"><span>'+(i+1)+'. '+companionMeta(key).name+'</span><button class="btn line" data-roster="'+key+'">'+(s.deployed.includes(key)?'出戰中':'待命')+'</button><button class="btn line" aria-label="提前'+companionMeta(key).name+'" data-order="'+key+'" data-dir="-1" '+(i===0?'disabled':'')+'>↑</button><button class="btn line" aria-label="延後'+companionMeta(key).name+'" data-order="'+key+'" data-dir="1" '+(i===s.order.length-1?'disabled':'')+'>↓</button></div>').join('')+'</div>',[{text:'完成',fn:()=>{closeModal();renderAll();save(true)}}]);$('companionAuto').onclick=()=>{s.auto=!s.auto;save(true);showCompanionFormation()};document.querySelectorAll('[data-roster]').forEach(b=>b.onclick=()=>{toggleCompanion(b.dataset.roster);showCompanionFormation()});document.querySelectorAll('[data-order]').forEach(b=>b.onclick=()=>{const i=s.order.indexOf(b.dataset.order),j=i+Number(b.dataset.dir);[s.order[i],s.order[j]]=[s.order[j],s.order[i]];s.cursor=0;save(true);showCompanionFormation()})}

function drawCompanionProjectile(g,pr){const angle=Math.atan2(pr.target.y-pr.y,pr.target.x-pr.x),color=pr.companion.startsWith('pet:')?'#8ff4c9':'#ffe2a2';g.save();g.translate(pr.x,pr.y);g.rotate(angle);g.shadowBlur=10;g.shadowColor=color;g.strokeStyle=color;g.lineWidth=3;g.beginPath();g.moveTo(-25,0);g.lineTo(0,0);g.stroke();g.rotate(-angle);const art=companionImages.get(pr.companion);if(art?.complete&&art.naturalWidth>0)g.drawImage(art,-9,-9,18,18);else{g.fillStyle=color;g.beginPath();g.arc(0,0,6,0,Math.PI*2);g.fill()}g.restore()}
