'use strict';
// Claim receipts live in the same save transaction as generated rewards.
const economyAccept=Encounters.accept;Encounters.accept=function(player,now){const ok=economyAccept(player,now);if(ok){const q=player.encounters.quests.at(-1);q.tier=['ordinary','rare','ancient'][q.id%3];q.eventType=q.kind;q.rewardPool='general';q.highChance=EconomyData.config.encounters[q.tier];}return ok};
const economyClaim=Encounters.claim;Encounters.claim=function(player,id,take){const q=player.encounters.quests.find(x=>x.id===id);if(!q)return false;Economy.normalize(player);const key='quest:'+id;if(player.economy.claims[key])return false;const ok=economyClaim(player,id,take);if(ok){Economy.reward(player,key,'encounter',q.tier||'ordinary');if(player===p)economyHydrate();}return ok};
const economyLandmark=Progression.collectLandmark;Progression.collectLandmark=function(player,map,point,vitals,now){const result=economyLandmark(player,map,point,vitals,now);if(result.ok&&point.kind==='ruins'){Economy.reward(player,'ruins:'+map+':'+point.id,'encounter','ancient');if(player===p)economyHydrate();}return result};
const economyBegin=beginRift;beginRift=function(index){const world=EconomyData.config.worlds[index];if(!world||p.realm<world.realm){note('此異界需要 '+REALMS[world?.realm||0].name+' 境界');return;}if(riftRunning)return;Economy.normalize(p);p.economy.runSequence=(p.economy.runSequence||0)+1;economyBegin(index);if(p.rift){p.rift.runId='rift:'+world.id+':'+p.economy.runSequence;p.rift.worldId=world.id;p.rift.bossRank=world.boss;p.economy.worlds[world.id]={...p.economy.worlds[world.id],entered:true,wave:1,boss:'challenging'};save(true);}};
const economyLoot=gainLoot;gainLoot=function(enemy){economyLoot(enemy);if(enemy.rift&&enemy.boss&&p.rift){const run=p.rift,world=EconomyData.config.worlds[run.theme];if(!run.runId)run.runId='legacy-rift:'+world.id+':'+(p.encounters.clears[world.id]||0);const result=Economy.reward(p,run.runId+':boss','boss',run.bossRank||world.boss,Math.random,world.id);if(result.ok){economyHydrate();save(true);note('界主戰利已收納：寶石、淬靈砂'+(result.rewards.length?'、'+result.rewards.map(id=>characterQuality(p.economy.instances[id].quality)).join('、'):''));}}else if(!enemy.rift&&Math.random()<.08){const quality=enemy.elite?2:Math.random()<.25?1:0,pool=Object.values(EconomyData.templates).filter(t=>t.type==='equip'&&t.realm<=p.realm),template=pool[Math.floor(Math.random()*pool.length)],item=Economy.create(p,template.id,quality,enemy.elite?'精英妖獸':'普通妖獸');Economy.grant(p,item);economyHydrate();save(true);}};
const economyFinishRift=finishRift;finishRift=function(won=false){if(p.rift&&riftRunning){const run=p.rift,world=EconomyData.config.worlds[run.theme];p.economy.worlds[world.id]={...p.economy.worlds[world.id],wave:run.wave,boss:won?'defeated':'retreated',clears:(p.economy.worlds[world.id]?.clears||0)+(won?1:0)};}return economyFinishRift(won)};
const economyJournal=encounterJournal;encounterJournal=function(){economyJournal();$('modalContent').insertAdjacentHTML('beforeend','<h3>異界入口</h3><p>完成機緣總高階率：普通 4%、稀有 5%、上古 6%；命中後金品／傳說為 95／5。首領另外獨立抽取金品與傳說。</p><div class="economy-grid">'+EconomyData.config.worlds.map((w,i)=>'<button class="btn line" data-world-entry="'+i+'" '+(p.realm<w.realm?'disabled':'')+'><img src="'+economyAsset('feature_world')+'" alt=""><span>'+Encounters.themes[i].name+'<small>需求 '+REALMS[w.realm].name+' · 金品 '+EconomyData.config.boss[w.boss].gold*100+'%／傳說 '+EconomyData.config.boss[w.boss].legendary*100+'%</small></span></button>').join('')+'</div>');document.querySelectorAll('[data-world-entry]').forEach(b=>b.onclick=()=>{closeModal();beginRift(Number(b.dataset.worldEntry))});};
const economyRiftStep=stepEncounters;stepEncounters=function(dt){economyRiftStep(dt);if(p.rift){const world=EconomyData.config.worlds[p.rift.theme];p.economy.worlds[world.id]={...p.economy.worlds[world.id],wave:p.rift.wave,boss:p.rift.wave===10?'challenging':'exploring'};}};
const economySpawn=spawnEnemy;spawnEnemy=function(){const before=enemies.length;economySpawn();if(enemies.length>before&&!riftRunning&&Math.random()<.06){const enemy=enemies.at(-1);enemy.elite=true;enemy.name='精英 · '+enemy.name;enemy.hp=Math.round(enemy.hp*1.5);enemy.maxHp=enemy.hp;enemy.atk=Math.round(enemy.atk*1.15);}};
