'use strict';
function economyMoveRate(){return 1+(p?.economy?Economy.bonuses(p).speed:0)}
function economyEnemySpeed(enemy){return enemy.slowUntil>Date.now()?1-(enemy.slow||0):1}
// Called exactly once from the existing animation loop, never from an extra timer.
function stepEconomy(dt,modalOpen){if(!p?.economy)return;const s=stats(),fx=Economy.bonuses(p);EconomyCombat.recover(p,s,qiMax(),fx,dt);if(modalOpen){p.qi=Math.min(qiMax(),p.qi+qps()*dt);p.hp=Math.min(s.hp,p.hp+dt*.6);p.mp=Math.min(s.mp,p.mp+dt*3.5);if(autoMeditate&&(p.qi<qiMax()||p.mp<s.mp)){autoMeditateTimer+=dt;if(autoMeditateTimer>=1){const ticks=Math.floor(autoMeditateTimer);autoMeditateTimer-=ticks;p.qi=Math.min(qiMax(),p.qi+Math.ceil(qps()*3)*ticks);p.mp=Math.min(s.mp,p.mp+12*ticks);}}tickSave+=dt;if(tickSave>15){tickSave=0;save(true);}}}
const economyHit=hurtEnemy;hurtEnemy=function(enemy,damage){if(!p?.economy||!enemy||enemy.hp<=0)return economyHit(enemy,damage);const fx=Economy.bonuses(p),hp=enemy.hp,def=enemy.def;enemy.def=def*(1-fx.penetration);economyHit(enemy,damage*(1+fx.damage+fx.ice));enemy.def=def;const dealt=Math.max(0,Math.min(hp,hp-enemy.hp));p.hp=Math.min(stats().hp,p.hp+dealt*fx.leech*(1+fx.healing));if(fx.slow&&enemy.hp>0){enemy.slow=fx.slow;enemy.slowUntil=Date.now()+1500;}if(fx.aoe&&Date.now()>=(p.economy.procUntil||0)){p.economy.procUntil=Date.now()+EconomyData.config.aoe.interval;for(const target of EconomyCombat.splashTargets(enemies,enemy,EconomyData.config.aoe))economyHit(target,damage*fx.aoe);effects.push({x:enemy.x,y:enemy.y,t:.5,kind:'sword'});}};
const economyCast=cast;cast=function(which,...args){const before=cd[which],result=economyCast(which,...args);if(p?.economy&&cd[which]>before){const now=performance.now(),reduction=Economy.bonuses(p).cooldown;cd[which]=now+(cd[which]-now)*(1-reduction);}return result};
const economyFire=fireCompanion;fireCompanion=function(key,...args){const n=projectiles.length,result=economyFire(key,...args);if(!result||!p.economy)return result;const [type,id]=key.split(':'),load=p.economy.loadout[type==='pet'?'pets':'treasures'],aux=load.indexOf(id)===1,instance=p.economy.instances[id],template=instance&&(EconomyData.templates[instance.baseId]||instance.template),power=(aux?EconomyData.config.loadout.auxiliaryScale:1)*(instance?.growth||1);for(const shot of projectiles.slice(n))shot.damage*=power;if(template?.role==='恢復')p.hp=Math.min(stats().hp,p.hp+stats().hp*.035*power);if(template?.role==='輔助')p.mp=Math.min(stats().mp,p.mp+3*power);if(template?.role==='防禦')p.hp=Math.min(stats().hp,p.hp+Math.max(1,stats().def*.1)*power);return result};
// Existing roster screens route unowned acquisition through the restricted shop.
renderPets=function(){economyRoster('pet')};renderTreasures=function(){economyRoster('treasure')};
function economyRoster(type){const list=(type==='pet'?PETS:TREASURES).filter(m=>Companions.owned(p,type+':'+m.id));$('panelContent').innerHTML='<p>六格配置：主戰 1、輔助 1、待命 4；主戰與輔助獨立 CD，輔助攻擊為 25%。</p><button class="btn gold" id="rosterShop">萬寶閣</button><button class="btn cyan" id="rosterRole">角色配置</button><div class="cards">'+list.map(m=>'<button class="card" data-economy-roster="'+type+':'+m.id+'"><img width="56" src="'+characterIcon(m.id,true)+'" alt=""><h3>'+m.name+'</h3><p>'+characterQuality(m.rarity)+' · '+m.desc+'</p></button>').join('')+'</div>';$('rosterShop').onclick=()=>{economyShopType=type;showCharacterShop()};$('rosterRole').onclick=openCharacter;document.querySelectorAll('[data-economy-roster]').forEach(b=>b.onclick=()=>showCharacterUnit(b.dataset.economyRoster));}
const economyRenderUI=renderUI;renderUI=function(){economyRenderUI();if(p?.economy){const qi=Economy.bonuses(p).qi;$('qiRate').textContent='+'+(qps()+qi).toFixed(1)+' / 秒'+(qi?' · 仙寶 +'+qi.toFixed(1):'');}};
