'use strict';
// Runtime integration: ordinary exploration and rift combat share the same combat loop.
let riftRunning=false,riftSnapshotClock=0;
const encounterModalBase=modal;
modal=function(...args){delete $('modal').dataset.encounterId;return encounterModalBase(...args)};
// Wall time continues while the decision dialog pauses combat.
function tickEncounterDecision(){
 const e=p?.encounters?.pending;if(!e)return;
 const owns=$('modal').dataset.encounterId===String(e.id);
 if(Encounters.expire(p)){if(owns)closeModal();delete $('modal').dataset.encounterId;save(true);renderUI();note('30 秒未接受，已自動婉拒機緣');return}
 if(owns)$('encounterCountdown').textContent='剩餘 '+Math.max(0,Math.ceil((e.expiresAt-Date.now())/1000))+' 秒 · 逾時自動拒絕，不接任務、不進入異界';
}
function encounterStillAvailable(e){tickEncounterDecision();return p.encounters.pending===e}
function refuseEncounter(e){if(!encounterStillAvailable(e))return;p.encounters.pending=null;closeModal();delete $('modal').dataset.encounterId;save(true);renderUI();note('已婉拒機緣')}
setInterval(tickEncounterDecision,250);
function snapshotRift(){if(!riftRunning||!p.rift)return;p.rift.enemies=enemies.filter(e=>e.hp>0).map(e=>({...e,warning:e.warning?{...e.warning}:null}));p.rift.position={...p.position}}
function beginRift(index){if(riftRunning)return;const theme=Encounters.themes[index];if(!theme)return;const s=stats();p.encounters.pending=null;p.rift={theme:index,wave:1,base:{...s},returnMap:mapIndex,returnPosition:{...p.position},paid:0,intermission:0,enemies:Encounters.wave(index,1,s),position:{x:460,y:450}};riftRunning=true;enemies=p.rift.enemies.map(e=>({...e}));p.position={...p.rift.position};projectiles=[];effects=[];destination=null;spawnTimer=0;setView('explore');updateJourney();renderUI();save(true);note(theme.name+' · 第 1 波開始')}
function finishRift(won=false){if(!riftRunning)return;const run=p.rift,theme=Encounters.themes[run.theme];snapshotRift();p.rift=null;riftRunning=false;projectiles=[];effects=[];destination=null;const bonus=won?Math.round(run.base.combat*1.5+300):0;if(won){p.stones+=bonus;p.jade+=5;p.encounters.clears[theme.id]=(p.encounters.clears[theme.id]||0)+1}switchMap(run.returnMap,true);p.position={...run.returnPosition};updateJourney();renderAll();save(true);log(theme.name+(won?'十波通關 · 靈石 +'+bonus+'、仙玉 +5':'挑戰結束，返回山海'),'good');note(won?'十波通關！靈石 +'+bonus+' · 仙玉 +5':'已返回山海 · 已取得的波次獎勵保留')}
function stepEncounters(dt){if(!p?.encounters)return;if(!riftRunning){if(activeView==='explore'&&Encounters.advance(p,dt)){save(true);showEncounter()}return}const run=p.rift;
 if(enemies.length===0){if(run.paid<run.wave){const reward=Encounters.waveReward(run.base,run.wave);p.stones+=reward;run.paid=run.wave;run.intermission=3;snapshotRift();save(true);note('第 '+run.wave+' 波完成 · 靈石 +'+reward)}if(run.wave===10){finishRift(true);return}run.intermission=Math.max(0,run.intermission-dt);if(run.intermission===0){run.wave++;enemies=Encounters.wave(run.theme,run.wave,run.base);projectiles=[];snapshotRift();save(true);note('第 '+run.wave+' 波'+(run.wave===5?' · 精英來襲！':run.wave===10?' · 界主降臨！':'開始'))}return}
 for(const e of [...enemies]){if(e.hp<=0)continue;if(Encounters.transform(e)){e.name=Encounters.themes[run.theme].boss+' · 暴走';note('Boss 氣血低於 20%！變身暴走，攻擊提高 35%');save(true)}if(!e.elite&&!e.boss)continue;if(e.warning){e.warning.left-=dt;if(e.warning.left<=0){const warning=e.warning;e.warning=null;effects.push({x:warning.x,y:warning.y,t:.65,kind:'fire'});if(Math.hypot(p.position.x-warning.x,p.position.y-warning.y)<warning.radius){let damage=Math.max(1,Math.round(e.atk*(e.boss?1.2:.65)-stats().def*.5));if(activeTreasureId()==='bell')damage=Math.ceil(damage*.75);if(typeof EconomyCombat!=='undefined'&&p.economy)damage=EconomyCombat.incoming(damage,Economy.bonuses(p));p.hp-=damage;rise('-'+damage,p.position.x,p.position.y-30,'#ff977b');if(p.hp<=0){p.hp=Math.round(stats().hp*.55);finishRift(false);return}}e.skillIn=e.boss?(e.transformed?4:7):6}}else{e.skillIn-=dt;if(e.skillIn<=0&&Math.hypot(e.x-p.position.x,e.y-p.position.y)<460){e.warning={x:p.position.x,y:p.position.y,radius:e.boss?(e.transformed?165:140):70,left:e.boss?2.2:1.3,total:e.boss?2.2:1.3};if(e.boss)note(e.transformed?'暴走大招！離開紅色預警區':'Boss 蓄力大招！離開紅色預警區')}}}
 riftSnapshotClock+=dt;if(riftSnapshotClock>=1){riftSnapshotClock=0;snapshotRift()}}
function encounterJournal(){const s=p.encounters,pending=s.pending;const quests=s.quests.map(q=>'<div class="chance-quest"><h3>'+q.name+' · '+({ordinary:'普通',rare:'稀有',ancient:'上古'}[q.tier]||'普通')+'</h3><p>完成後高階掉落 '+Math.round((q.highChance||.04)*100)+'%</p><p>'+q.desc+' · '+Math.min(q.target,Encounters.progress(p,q))+' / '+q.target+'</p><p>獎勵：靈石 '+q.reward+'、仙玉 1</p><button class="btn gold" data-chance-claim="'+q.id+'" '+(Encounters.progress(p,q)<q.target?'disabled':'')+'>完成任務'+(q.kind==='collect'?'並繳交材料':'')+'</button><button class="btn line" data-chance-abandon="'+q.id+'">放棄</button></div>').join('');modal('山海機緣簿','<p>探索中不定時出現機緣，同時最多接取 3 項任務。擊殺從接取後開始計算；收集任務需繳交背包材料。</p>'+ (pending?'<button class="btn cyan" id="journalPending">查看附近機緣</button>':'')+(quests||'<p class="muted">尚未接取機緣任務，繼續探索山海。</p>')+'<h3>異世界圖鑑</h3><div class="rift-codex">'+Encounters.themes.map(t=>'<div style="border-color:'+t.accent+'"><b>'+t.name+'</b><small>'+t.style+'</small><small>界主：'+t.boss+' · 通關 '+(s.clears[t.id]||0)+' 次</small></div>').join('')+'</div>',[{text:'返回'}]);if($('journalPending'))$('journalPending').onclick=showEncounter;document.querySelectorAll('[data-chance-claim]').forEach(b=>b.onclick=()=>{if(!Encounters.claim(p,Number(b.dataset.chanceClaim),(id,n)=>Progression.takeItem(p,id,n)))return;note('任務完成！獎勵已領取');renderAll();save(true);encounterJournal()});document.querySelectorAll('[data-chance-abandon]').forEach(b=>b.onclick=()=>{s.quests=s.quests.filter(q=>q.id!==Number(b.dataset.chanceAbandon));save(true);encounterJournal()})}
function showEncounter(){tickEncounterDecision();const e=p.encounters.pending;if(!e)return encounterJournal();const countdown='<p id="encounterCountdown" role="status" style="color:#f7d59a">剩餘 30 秒 · 逾時自動拒絕</p>';if(e.kind==='quest'){const q=Encounters.quests[e.index];modal('偶遇機緣 · '+q.name,countdown+'<p>山道上，一位修士向你求助。</p><p>'+q.desc+'</p><p>獎勵：靈石 '+q.reward+'、仙玉 1</p><p>目前任務：'+p.encounters.quests.length+' / 3</p>',[{text:'婉拒',fn:()=>refuseEncounter(e)},{text:'接取任務',style:'gold',fn:()=>{if(!encounterStillAvailable(e))return;if(!Encounters.accept(p))return note('任務已滿，請先完成或放棄任務');closeModal();save(true);renderUI();note('已接取 '+q.name)}}])}else{const t=Encounters.themes[e.index],s=stats();modal('異界裂隙 · '+t.name,countdown+'<div class="rift-intro" style="border-color:'+t.accent+'"><h3>'+t.name+'</h3><p>'+t.style+'</p></div><p>十波挑戰，每波漸強，第 5 波起精英數量增加並施放預警範圍技能。</p><p>第 10 波：'+t.boss+'，基礎攻擊 '+Math.round(s.combat*1.5)+'（進入時戰力 ×1.5）。氣血低於 20% 變身，攻擊再提高 35%，大招更頻繁。</p><p>危險！點擊地圖走位躲避紅色預警；每波領取靈石，通關另獎仙玉 5。可隨時退出，保留已取得獎勵。</p>',[{text:'放棄機緣',fn:()=>refuseEncounter(e)},{text:'踏入異界',style:'gold',fn:()=>{if(!encounterStillAvailable(e))return;closeModal();beginRift(e.index)}}])}$('modal').dataset.encounterId=String(e.id);tickEncounterDecision()}
(function(){
 const strip=document.createElement('div');strip.className='encounter-strip';strip.innerHTML='<div class="encounter-info"><span id="encounterStatus">山海機緣</span><small id="riftBossStatus" class="hidden"></small></div><div><button class="btn gold small" id="encounterOpen">機緣簿</button><button class="btn line small hidden" id="riftExit">退出</button></div>';document.querySelector('.world').before(strip);$('encounterOpen').onclick=()=>p.encounters.pending?showEncounter():encounterJournal();$('riftExit').onclick=()=>modal('退出異界','<p>退出將結束本次十波挑戰，已領取的波次獎勵保留。</p>',[{text:'繼續挑戰'},{text:'返回山海',fn:()=>{closeModal();finishRift(false)}}]);
 const start=startGame;startGame=function(){riftRunning=false;Encounters.normalize(p);start();if(p.rift&&Encounters.themes[p.rift.theme]&&p.rift.wave>=1&&p.rift.wave<=10){riftRunning=true;enemies=(p.rift.enemies||[]).map(e=>({...e}));p.position={...(p.rift.position||{x:460,y:450})};destination=null;projectiles=[];updateJourney();renderUI()}if(p.encounters.pending){save(true);showEncounter()}};
 const saveBase=save;save=function(...args){snapshotRift();return saveBase(...args)};
 const spawn=spawnEnemy;spawnEnemy=function(){if(!riftRunning)return spawn()};
 const switchBase=switchMap;switchMap=function(index,force=false){if(riftRunning){if(force){finishRift(false);return true}note('請先退出異界挑戰');return false}return switchBase(index,force)};
 const loot=gainLoot;gainLoot=function(e){if(!e.rift)return loot(e);p.killCount++;snapshotRift();save(true)};
 const points=currentPoints;currentPoints=function(){return riftRunning?[]:points()};
 const journey=updateJourney;updateJourney=function(){document.querySelector('.journey-bar').classList.toggle('hidden',riftRunning);$('game').dataset.rift=riftRunning?Encounters.themes[p.rift.theme].id:'';if(!riftRunning)return journey();const run=p.rift,t=Encounters.themes[run.theme];document.querySelector('.scene-top').style.setProperty('--rift-floor',t.floor);$('sceneTitle').textContent=t.name+' · 第 '+run.wave+' 波';$('sceneDescription').textContent='十波試煉 · 點擊走位避開預警 · 法寶與靈寵協同作戰';$('mapTag').textContent=t.name;};
 const exploration=stepExploration;stepExploration=function(dt){if(!riftRunning)return exploration(dt);const automatic=destination?.automatic;if(automatic)destination=null;const gather=p.autoGather;p.autoGather=false;exploration(dt);p.autoGather=gather};
 const view=setView;setView=function(value){if(riftRunning&&value==='manage'){note('異界中請專心應戰，退出後可養成');return view('explore')}return view(value)};
 const choose=chooseTab;chooseTab=function(id){if(riftRunning){note('退出異界後可管理養成');return}return choose(id)};
 const ui=renderUI;renderUI=function(){ui();if(!p?.encounters)return;const run=p.rift,pending=p.encounters.pending;strip.classList.toggle('has-chance',!!pending);$('encounterStatus').textContent=riftRunning?Encounters.themes[run.theme].name+' · '+run.wave+'/10 波 · '+(enemies.length?'剩餘 '+enemies.length+' 敵人':'下一波 '+Math.ceil(run.intermission)+'s'):pending?(pending.kind==='rift'?'異界裂隙':'修士求助')+' · 附近有機緣':'機緣任務 '+p.encounters.quests.length+'/3 · 已完成 '+p.encounters.completed;$('encounterOpen').textContent=pending?'查看機緣':'機緣簿';$('riftExit').classList.toggle('hidden',!riftRunning);const boss=riftRunning?enemies.find(e=>e.boss):null;$('riftBossStatus').classList.toggle('hidden',!boss);if(boss)$('riftBossStatus').textContent=boss.name+' · '+fmt(Math.max(0,boss.hp))+'/'+fmt(boss.maxHp)+(boss.warning?' · 大招蓄力，快躲開！':'');if(riftRunning){$('enemyCounter').textContent='第 '+run.wave+' 波';$('mapPrev').disabled=true;$('mapNext').disabled=true}else{$('mapPrev').disabled=mapIndex===0;$('mapNext').disabled=mapIndex===MAPS.length-1}};
 const scene=drawScene;drawScene=function(g,W,H,time){if(riftRunning)return drawRiftScene(g,W,H,time);scene(g,W,H,time);const e=p.encounters?.pending;if(e){const zoom=Math.max(W/850,H/490);g.save();g.scale(zoom,zoom);g.translate(-cam.x,-cam.y);g.strokeStyle=e.kind==='rift'?'#d0a6ff':'#f7d59a';g.lineWidth=3;g.beginPath();g.ellipse(e.x,e.y-18,22,32,0,0,Math.PI*2);g.stroke();g.font='13px serif';g.textAlign='center';g.fillStyle='#fff2d0';g.fillText(e.kind==='rift'?'異界裂隙':'修士機緣',e.x,e.y-58);g.restore()}};
})();
// Each realm has a distinct procedural floor; static geometry is cached per realm.
const riftFloors=new Map();
function riftFloor(index){if(riftFloors.has(index))return riftFloors.get(index);const t=Encounters.themes[index],canvas=document.createElement('canvas');canvas.width=1500;canvas.height=900;const g=canvas.getContext('2d');g.fillStyle=t.floor;g.fillRect(0,0,1500,900);const noise=n=>(Math.sin(n*47.31)*43758.5)%1;for(let i=0;i<95;i++){const x=Math.abs(noise(i+1))*1500,y=Math.abs(noise(i+190))*900;g.save();g.translate(x,y);g.strokeStyle=t.accent+'70';g.fillStyle=t.accent+'20';g.lineWidth=2;if(index===0){g.beginPath();g.moveTo(-40,0);g.lineTo(-5,-15);g.lineTo(12,16);g.lineTo(50,-5);g.stroke();}else if(index===1){g.beginPath();g.moveTo(0,-30);g.lineTo(15,4);g.lineTo(0,18);g.lineTo(-15,4);g.closePath();g.fill();g.stroke();}else if(index===2){g.beginPath();g.ellipse(0,0,26,48,(i%4)*.4,0,Math.PI*2);g.fill();g.beginPath();g.arc(0,-12,3,0,Math.PI*2);g.fillStyle=t.accent;g.fill();}else if(index===3){g.beginPath();g.ellipse(0,0,85,18,-.2,0,Math.PI*2);g.stroke();if(i%4===0){g.fillStyle='#bca16f';g.fillRect(-9,-35,18,48);g.fillRect(-14,-39,28,7)}}else{g.beginPath();g.arc(0,0,i%5===0?19:2,0,Math.PI*2);g.fill();g.stroke();}g.restore()}g.strokeStyle=t.accent+'40';g.lineWidth=3;g.beginPath();g.arc(750,450,285,0,Math.PI*2);g.stroke();g.beginPath();g.arc(750,450,230,0,Math.PI*2);g.stroke();riftFloors.set(index,canvas);return canvas}
function drawRiftScene(g,W,H,time){const run=p.rift,t=Encounters.themes[run.theme],zoom=Math.max(W/850,H/490),viewW=W/zoom,viewH=H/zoom;cam.x=clamp(p.position.x-viewW/2,0,1500-viewW);cam.y=clamp(p.position.y-viewH/2,0,900-viewH);g.save();g.scale(zoom,zoom);g.translate(-cam.x,-cam.y);g.drawImage(riftFloor(run.theme),0,0);
 for(const e of enemies){const warning=e.warning;if(!warning)continue;g.fillStyle='#ff4a3340';g.strokeStyle='#ffb182';g.lineWidth=3;g.beginPath();g.arc(warning.x,warning.y,warning.radius,0,Math.PI*2);g.fill();g.stroke();g.strokeStyle='#fff0c0';g.lineWidth=5;g.beginPath();g.arc(warning.x,warning.y,warning.radius*clamp(1-warning.left/warning.total,0,1),0,Math.PI*2);g.stroke();g.font='14px serif';g.textAlign='center';g.fillStyle='#fff2c7';g.fillText(e.boss?'大招 · 快躲開':'精英技',warning.x,warning.y-8)}
 const actors=enemies.map(e=>({y:e.y,draw:()=>{const size=e.boss?(e.transformed?64:48):e.elite?27:20;paintRiftEnemy(g,e,t,run.theme,size,time);g.font=e.boss?'13px serif':'10px serif';g.textAlign='center';const width=e.boss?140:80,y=typeof riftEnemyLabelY==='function'?riftEnemyLabelY(e,size):e.y-size*1.6-18;g.fillStyle='#091d2be6';g.fillRect(e.x-width/2-4,y-17,width+8,28);g.fillStyle='#f1dfb5';g.fillText(e.name,e.x,y-5);g.fillStyle='#2d2630';g.fillRect(e.x-width/2,y,width,5);g.fillStyle=e.transformed?'#ff684f':'#dca077';g.fillRect(e.x-width/2,y,width*clamp(e.hp/e.maxHp,0,1),5);}}));actors.push({y:p.position.y-1,draw:()=>drawPet(g,p.position.x,p.position.y,time)},{y:p.position.y,draw:()=>drawCharacter(g,p.position.x,p.position.y,time)});actors.sort((a,b)=>a.y-b.y);actors.forEach(a=>a.draw());for(const pr of projectiles){if(pr.companion){drawCompanionProjectile(g,pr);continue}g.fillStyle=pr.kind==='fire'?'#ffb06f':'#bef9ec';g.beginPath();g.arc(pr.x,pr.y,pr.kind==='fire'?8:5,0,Math.PI*2);g.fill()}for(const e of effects){g.strokeStyle=e.kind==='heal'?'#8ce7b8':t.accent;g.globalAlpha=clamp(e.t,0,1);g.lineWidth=3;g.beginPath();g.arc(e.x,e.y,Progression.effectRadius(e.t),0,Math.PI*2);g.stroke();g.globalAlpha=1}g.restore()}
worldCanvas.addEventListener('pointerdown',event=>{const encounter=p?.encounters?.pending;if(!encounter||riftRunning||event.button!==0||!$('modal').classList.contains('hidden'))return;const rect=worldCanvas.getBoundingClientRect(),zoom=Math.max(rect.width/850,rect.height/490),x=cam.x+(event.clientX-rect.left)/zoom,y=cam.y+(event.clientY-rect.top)/zoom;if(Math.hypot(x-encounter.x,y-(encounter.y-18))<48){destination=null;showEncounter()}});
function paintRiftEnemy(g,e,t,index,size,time){g.save();g.translate(e.x,e.y);g.fillStyle='#00000060';g.beginPath();g.ellipse(0,8,size,12,0,0,Math.PI*2);g.fill();g.fillStyle=e.transformed?'#f16a58':e.elite?t.accent:t.color;g.strokeStyle=e.boss?'#ffeac1':t.accent;g.lineWidth=e.boss?3:1;g.beginPath();if(index===0){g.moveTo(-size,0);g.lineTo(-size*.8,-size*.9);g.lineTo(-size*.9,-size*1.65);g.lineTo(-size*.25,-size*1.15);g.lineTo(0,-size*1.7);g.lineTo(size*.25,-size*1.15);g.lineTo(size*.9,-size*1.65);g.lineTo(size*.8,-size*.9);g.lineTo(size,0)}else if(index===1){g.moveTo(-size,0);g.lineTo(-size*.4,-size);g.lineTo(-size*.65,-size*1.3);g.lineTo(-size*.4,-size*1.8);g.lineTo(0,-size*1.45);g.lineTo(size*.4,-size*1.8);g.lineTo(size*.65,-size*1.3);g.lineTo(size*.4,-size);g.lineTo(size,0)}else if(index===2){g.moveTo(-size*.6,0);g.lineTo(-size*.25,-size*.5);g.lineTo(-size,-size*.6);g.lineTo(-size*.9,-size*1.1);g.lineTo(-size*.45,-size*1.3);g.lineTo(0,-size*1.65);g.lineTo(size*.45,-size*1.3);g.lineTo(size*.9,-size*1.1);g.lineTo(size,-size*.6);g.lineTo(size*.25,-size*.5);g.lineTo(size*.6,0)}else if(index===3){g.moveTo(-size*.7,0);g.lineTo(-size*.75,-size*1.2);g.lineTo(-size*.45,-size*1.55);g.lineTo(size*.45,-size*1.55);g.lineTo(size*.75,-size*1.2);g.lineTo(size*.7,0)}else{g.moveTo(0,-size*1.8);g.lineTo(size,-size*.8);g.lineTo(size*.65,0);g.lineTo(0,size*.25);g.lineTo(-size*.65,0);g.lineTo(-size,-size*.8)}g.closePath();g.fill();g.stroke();g.fillStyle='#09252b';g.fillRect(-size*.5,-size*.75,size*.25,4);g.fillRect(size*.25,-size*.75,size*.25,4);if(index===3){g.strokeStyle='#967848';for(let i=0;i<4;i++){g.beginPath();g.moveTo(-size*.6,-size*.5+i*size*.14);g.lineTo(size*.6,-size*.5+i*size*.14);g.stroke()}}if(index===4){g.fillStyle='#efdbff';g.beginPath();g.arc(0,-size*.5,size*.13,0,Math.PI*2);g.fill()}if(e.boss||e.elite){g.strokeStyle=e.transformed?'#ff8c6d':t.accent;g.lineWidth=e.boss?3:1;g.beginPath();g.arc(0,-size*.8,size*1.2,time,time+Math.PI*1.6);g.stroke()}g.restore()}
