'use strict';
// V2.1 adapter: original saves, maps, combat callbacks and the single RAF remain authoritative.
const v21Images=new Map(),v21BaseImages={skill:'icon-fire',treasure:'icon-pearl',pet:'icon-fox',material:'prop-rock',enemy:'map-sword-spirit',npc:'hero-sage',prop:'prop-pavilion'};
function v21Asset(id){return './src/assets/v21/runtime/'+id+'.png';}
function v21Image(id){if(typeof V21Assets==='undefined'||!V21Assets.includes(id))return null;if(!v21Images.has(id)){const im=new Image();im.src=v21Asset(id);v21Images.set(id,im);}const im=v21Images.get(id);return im.complete&&im.naturalWidth?im:null;}
function v21Icon(id,category='skill'){return typeof V21Assets!=='undefined'&&V21Assets.includes(id)?v21Asset(id):'./src/assets/art/'+v21BaseImages[category]+'.webp';}
const v21HydrateBase=economyHydrate;economyHydrate=function(){v21HydrateBase();if(!p)return;HighRealms.normalize(p);for(const a of [...HighRealmData.materials,...HighRealmData.skills.map(s=>({id:s.bookId,assetId:s.assetId}))])if(ITEMS[a.id])ITEMS[a.id].icon='<img width="36" src="'+v21Icon(a.assetId,a.id.includes('book')?'skill':'material')+'" alt="">';};
const v21CharacterIconBase=characterIcon;characterIcon=function(id,companion=false){const it=p?.economy?.instances[id],t=EconomyData.templates[it?.baseId||id],s=HighRealmData.skills.find(s=>s.bookId===id),m=HighRealmData.materials.find(m=>m.id===id);if(t?.highRealm)return v21Icon(t.assetId,t.type);if(s||m)return v21Icon((s||m).assetId,s?'skill':'material');return v21CharacterIconBase(id,companion);};
// All economic UI paths share this asset resolver, preserving existing approved artwork.
// economyAsset is a const; high-realm runtime paths are supplied by the existing economy asset tree at build time.
const v21Start=startGame;startGame=function(){HighRealms.normalize(p);v21Start();renderV21Hotbar();};
let v21BossSpawned=false;
const v21Switch=switchMap;switchMap=function(index,force=false){const map=MAPS[index];if(!map)return false;if(map.highRealm&&!HighRealms.canEnter(p,map)){note(map.finished?'完成渡劫飛昇後才能進入':'境界不足，無法進入'+map.name);return false;}v21BossSpawned=false;const ok=v21Switch(index,force);if(ok){destination=null;HighRealms.normalize(p);p.highRealms.explored=p.highRealms.explored||{};p.highRealms.explored[map.id]=true;save(true);}return ok;};
const v21Spawn=spawnEnemy;spawnEnemy=function(){const map=MAPS[mapIndex];if(!map?.highRealm||riftRunning)return v21Spawn();if(enemies.length>=8||(map.zone===4&&v21BossSpawned))return;HighRealms.normalize(p);const spec=map.monsters[Math.floor(Math.random()*map.monsters.length)],id='v21kill:'+ ++p.highRealms.spawnSequence;enemies.push({...spec,claimId:id,highRealm:true,x:rnd(150,1350),y:rnd(140,780),maxHp:spec.hp,cd:1,hit:0,roam:2,vx:0,vy:0,skillTimer:2+Math.random()*3,skillIndex:0});if(map.zone===4)v21BossSpawned=true;};
const v21Loot=gainLoot;gainLoot=function(e){if(!e.highRealm)return v21Loot(e);const result=HighRealms.reward(p,e);if(!result.ok)return;const map=MAPS[mapIndex];p.highRealms.progress=p.highRealms.progress||{};const progress=p.highRealms.progress[map.id]||{kills:0,bossWins:0};progress.kills++;if(e.role==='boss')progress.bossWins++;p.highRealms.progress[map.id]=progress;p.killCount++;p.highRealms.killCount=(p.highRealms.killCount||0)+1;p.stones+=e.stone;p.qi=Math.min(qiMax(),p.qi+e.qi);economyHydrate();save(true);renderAll();note((e.role==='boss'?'界主已敗！保底紫品以上戰利已保存':'高階戰利已收入背包／未領取匣')+(result.rewards.some(r=>r.id.startsWith('v21_book'))?' · 獲得神通技能書':''));};
const v21ShowItem=showItem;showItem=function(id){const book=HighRealmData.skills.find(s=>s.bookId===id);if(!book)return v21ShowItem(id);modal(book.name+' · 技能書','<img class="character-detail-icon" src="'+v21Icon(book.assetId)+'" alt=""><p>'+book.desc+'</p><p>需求 '+REALMS[book.realm].name+' · 真元 '+book.cost+' · 冷卻 '+book.cooldown/1000+' 秒</p><p>重複技能書不自動消耗，保留於背包。</p><p id="v21LearnStatus" role="status"></p>',[{text:'關閉'},{text:'學習神通',style:'gold',fn:()=>{const r=HighRealms.learn(p,id);if(!r.ok){$('v21LearnStatus').textContent=r.reason;return;}save(true);renderAll();modal('神通已學會','<p>'+book.name+' 已解鎖，可於玄門神通配置快捷欄。</p>',[{text:'配置技能',fn:()=>{closeModal();closeCharacter();chooseTab('skills');}},{text:'完成'}]);}}]);};
function v21SkillMeta(id){if(id==='attack')return {id,name:'普攻',desc:'近距離普通攻擊',cost:0,cooldown:480};const old=SKILLS.find(s=>s.id===id);return old||HighRealms.skill(id);}
function renderV21Hotbar(){if(!p)return;const h=HighRealms.normalize(p),bar=document.querySelector('.world-hotkeys');if(!bar)return;bar.classList.add('v21-hotbar');if(bar.dataset.v21!=='1'){bar.dataset.v21='1';bar.innerHTML=Array.from({length:8},(_,i)=>'<button data-v21-cast="'+i+'"><img alt=""><span></span></button>').join('');bar.querySelectorAll('button').forEach(b=>b.onclick=()=>cast(Number(b.dataset.v21Cast)));}bar.querySelectorAll('button').forEach((b,i)=>{const id=h.slots[i],s=v21SkillMeta(id),left=Math.max(0,((h.cooldowns[id]||0)-Date.now())/1000),img=b.querySelector('img');b.disabled=!s||p.mp<s.cost||left>0;b.setAttribute('aria-label',s?(i+1)+' · '+s.name+(left?' · 冷卻 '+left.toFixed(1)+' 秒':''):(i+1)+' · 空技能欄');img.hidden=!s;img.src=s?.assetId?v21Icon(s.assetId):'./src/assets/art/icon-'+(id==='heal'?'herb':id==='flame'?'fire':'sword')+'.webp';b.querySelector('span').textContent=left?left.toFixed(1)+'s':s?.name.slice(0,4)||'空欄';});}
const v21RenderUI=renderUI;renderUI=function(){v21RenderUI();renderV21Hotbar();};
const v21RenderSkills=renderSkills;renderSkills=function(){v21RenderSkills();const h=HighRealms.normalize(p);$('panelContent').insertAdjacentHTML('afterbegin','<section class="v21-skill-manager"><h3>八格神通配置</h3><p>已學會神通可配置；選到已使用的技能會交換欄位。快捷鍵 1–8 對應八格，J 為第一格。</p><div class="v21-slot-grid">'+h.slots.map((id,i)=>'<label>第 '+(i+1)+' 格<select data-v21-slot="'+i+'"><option value="">空欄位</option>'+['attack','flame','sword','heal',...HighRealmData.skills.map(s=>s.id)].filter(id=>HighRealms.learned(p,id)).map(key=>'<option value="'+key+'" '+(key===id?'selected':'')+'>'+v21SkillMeta(key).name+'</option>').join('')+'</select></label>').join('')+'</div><h3>自動施放優先順序</h3><p>數字越小越優先；治療依氣血、回靈依真元、範圍技依附近敵人數施放。</p>'+h.slots.filter(Boolean).map((id,i)=>{const cfg=h.auto[id]||{};return '<div class="v21-auto-row"><label><input type="checkbox" data-v21-auto="'+id+'" '+(cfg.enabled!==false?'checked':'')+'>'+v21SkillMeta(id).name+'</label><label>優先<select data-v21-priority="'+id+'">'+Array.from({length:8},(_,n)=>'<option value="'+n+'" '+((cfg.priority??i)===n?'selected':'')+'>'+(n+1)+'</option>').join('')+'</select></label><label>氣血門檻<select data-v21-hp="'+id+'">'+[.3,.55,.8].map(n=>'<option value="'+n+'" '+((cfg.hpThreshold||.55)===n?'selected':'')+'>'+Math.round(n*100)+'%</option>').join('')+'</select></label><label>真元門檻<select data-v21-mp="'+id+'">'+[.3,.45,.7].map(n=>'<option value="'+n+'" '+((cfg.mpThreshold||.45)===n?'selected':'')+'>'+Math.round(n*100)+'%</option>').join('')+'</select></label><label>範圍目標<select data-v21-targets="'+id+'">'+[1,2,3].map(n=>'<option value="'+n+'" '+((cfg.minTargets||2)===n?'selected':'')+'>'+n+'</option>').join('')+'</select></label></div>';}).join('')+'</section>');
 $('panelContent').insertAdjacentHTML('beforeend','<h3>高階神通書庫 · 30 種</h3><div class="cards">'+HighRealmData.skills.map(s=>'<div class="card"><img width="48" src="'+v21Icon(s.assetId)+'" alt=""><h3>'+s.name+' · '+(p.skills[s.id]?'已學會':'未學會')+'</h3><p>'+s.desc+'</p><p>'+REALMS[s.realm].name+' · 真元 '+s.cost+' · CD '+s.cooldown/1000+' 秒</p><p>'+s.source+'</p>'+(p.inventory.some(e=>e.id===s.bookId)?'<button class="btn cyan" data-v21-book="'+s.bookId+'">查看技能書</button>':'')+'</div>').join('')+'</div>');
 document.querySelectorAll('[data-v21-slot]').forEach(b=>b.onchange=()=>{HighRealms.assign(p,Number(b.dataset.v21Slot),b.value);save(true);renderSkills();renderV21Hotbar();});for(const [attr,key]of [['auto','enabled'],['priority','priority'],['hp','hpThreshold'],['mp','mpThreshold'],['targets','minTargets']])document.querySelectorAll('[data-v21-'+attr+']').forEach(b=>b.onchange=()=>{const id=b.getAttribute('data-v21-'+attr);h.auto[id]={...h.auto[id],[key]:attr==='auto'?b.checked:Number(b.value)};save(true);});document.querySelectorAll('[data-v21-book]').forEach(b=>b.onclick=()=>showItem(b.dataset.v21Book));};
function v21Buff(key,value,duration){const h=HighRealms.normalize(p);h.buffs=h.buffs||{};h.buffs[key]={value,until:Date.now()+duration};}
function v21BuffValue(key){const b=p?.highRealms?.buffs?.[key];return b&&b.until>Date.now()?b.value:0;}
const v21Stats=stats;stats=function(){const s=v21Stats();s.def*=1+v21BuffValue('armor');s.crit=Math.min(.75,(s.crit||0)+v21BuffValue('reveal'));return s;};
const v21Qps=qps;qps=function(){return v21Qps()*(1+v21BuffValue('cultivate'));};
const v21Incoming=EconomyCombat.incoming;EconomyCombat.incoming=function(d,fx){d=v21Incoming(d,fx);if(!p?.highRealms)return d;const h=p.highRealms;if(h.shieldUntil>Date.now()&&h.shield>0){const absorbed=Math.min(h.shield,d);h.shield-=absorbed;d-=absorbed;}return d;};
const v21Move=economyMoveRate;economyMoveRate=function(){return v21Move()*(p?.highRealms?.slowUntil>Date.now()?.55:1);};
const v21LegacyCast=cast;
cast=function(slot){if(!p||!$('modal').classList.contains('hidden')||characterIsOpen())return false;const h=HighRealms.normalize(p),id=h.slots[slot],meta=v21SkillMeta(id),now=Date.now();if(!meta||!HighRealms.learned(p,id)||p.mp<meta.cost||now<(h.cooldowns[id]||0)||now<(h.silencedUntil||0))return false;
 if(['attack','flame','sword','heal'].includes(id)){const index={attack:0,flame:1,sword:2,heal:3}[id],before=cd[index];v21LegacyCast(index);if(cd[index]===before)return false;h.cooldowns[id]=now+Math.max(0,cd[index]-performance.now());return true;}
 const s=HighRealms.skill(id),st=stats(),near=HighRealms.targets(enemies,p.position,s.range,s.maxTargets),attack=['chain','burn','multi','dashStrike','slow','aoe','pierce','meteor','strike','silence'].includes(s.mode);if(attack&&!near.length)return false;p.mp-=s.cost;h.cooldowns[id]=now+s.cooldown*(1-Economy.bonuses(p).cooldown);
 if(attack){if(s.mode==='dashStrike'){p.position.x=clamp(near[0].x-60,40,1460);p.position.y=clamp(near[0].y,55,845);}const center=near[0],victims=['strike','pierce','dashStrike'].includes(s.mode)?near.slice(0,1):HighRealms.targets(enemies,center,s.radius,s.maxTargets);const hit=()=>{for(const e of victims){if(!enemies.includes(e)||e.hp<=0)continue;const def=e.def;if(s.mode==='pierce')e.def=0;hurtEnemy(e,st.atk*s.power);e.def=def;if(s.mode==='burn')e.v21Burn={until:now+4000,damage:st.atk*.15};if(s.mode==='slow'){e.slow=.4;e.slowUntil=now+4000;}if(s.mode==='silence')e.silencedUntil=now+5000;}effects.push({x:center.x,y:center.y,t:.7,kind:s.mode==='burn'?'fire':'sword'});};if(s.mode==='meteor'){h.meteor={at:now+900,x:center.x,y:center.y,damage:st.atk*s.power,radius:s.radius};}else hit();}
 else if(['heal','revive','restore'].includes(s.mode)){p.hp=Math.min(st.hp,p.hp+st.hp*(s.mode==='restore'?.2:.35));if(s.mode==='restore')p.mp=Math.min(st.mp,p.mp+st.mp*.25);if(s.mode==='revive'){h.shield=st.hp*.25;h.shieldUntil=now+8000;}}
 else if(s.mode==='mana')p.mp=Math.min(st.mp,p.mp+st.mp*.35);
 else if(s.mode==='shield'){h.shield=Math.max(h.shield||0,st.hp*.25);h.shieldUntil=now+7000;}
 else if(['armor','reveal','companion','cultivate'].includes(s.mode))v21Buff(s.mode,s.mode==='reveal'?.15:.35,8000);
 else if(s.mode==='cleanse'){h.slowUntil=0;h.silencedUntil=0;h.dot=null;p.hp=Math.min(st.hp,p.hp+st.hp*.15);}
 else if(s.mode==='clone')h.clone={until:now+10000,next:now,x:p.position.x-40,y:p.position.y};
 else if(['dash','teleport'].includes(s.mode)){const e=near[0],dx=s.mode==='teleport'&&e?p.position.x-e.x:keys.has('a')?-1:keys.has('d')?1:0,dy=s.mode==='teleport'&&e?p.position.y-e.y:keys.has('w')?-1:1,len=Math.hypot(dx,dy)||1;p.position.x=clamp(p.position.x+dx/len*180,40,1460);p.position.y=clamp(p.position.y+dy/len*180,55,845);}
 effects.push({x:p.position.x,y:p.position.y,t:.55,kind:attack?'cast':'heal'});return true;};
function stepV21Auto(){if(!auto||!p)return;const h=HighRealms.normalize(p),near=HighRealms.targets(enemies,p.position,360,8).length;for(const id of h.slots.filter(Boolean).sort((a,b)=>(h.auto[a]?.priority??h.slots.indexOf(a))-(h.auto[b]?.priority??h.slots.indexOf(b)))){if(h.auto[id]?.enabled===false)continue;const s=HighRealms.skill(id);if(s&&!HighRealms.autoEligible(p,s,stats(),near))continue;if(id==='heal'&&p.hp>=stats().hp*(h.auto[id]?.hpThreshold||.55))continue;cast(h.slots.indexOf(id));}}
window.addEventListener('keydown',e=>{if(!p||['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName)||e.repeat)return;if(/^[4-8]$/.test(e.key))cast(Number(e.key)-1);});
const v21Points=currentPoints;currentPoints=function(){const map=MAPS[mapIndex];if(!map?.highRealm||riftRunning)return v21Points();return [...Progression.landmarks.map((x,i)=>({...x,name:HighRealmData.themes.find(t=>t.id===map.theme).props[i%3]+(i===3?'傳承':''),x:[350,700,1050,1230][i],y:[200,380,620,200][i]})),...HighRealmData.npcs.filter(n=>n.theme===map.theme).map(n=>({...n,mark:'仙',desc:n.role,kind:'npc'}))];};
const v21Interact=interactPoint;interactPoint=function(){const point=nearestPoint(),map=MAPS[mapIndex];if(point?.kind!=='npc')return v21Interact();if(point.role.includes('商人')){showCharacterShop();return true;}if(point.role.includes('煉丹')){closeModal();chooseTab('abode');return true;}if(point.role.includes('御獸')){closeModal();chooseTab('pets');return true;}if(point.role.includes('鍛造')){showForgemaster(point.id);return true;}const h=HighRealms.normalize(p);h.npcQuests=h.npcQuests||{};const state=h.npcQuests[point.id];modal(point.name,'<p>'+map.name+'：'+map.desc+'</p><p>'+ (point.role.includes('守衛')?'完成十次高階妖獸討伐，獲得本境神通傳承。': '同境分區、秘境與首領祭壇皆可透過萬界歷練前往。')+'</p><p>'+(state?'討伐進度 '+Math.min(10,(h.killCount||0)-state.start)+'/10':'尚未接取本境討伐任務')+'</p><p id="v21NpcStatus" role="status"></p>',[{text:'返回'},{text:'萬界傳送',fn:()=>{closeModal();chooseTab('dungeons');}},{text:state?'領取傳承':'接取討伐',style:'gold',fn:()=>{if(!state){h.npcQuests[point.id]={start:h.killCount||0};save(true);$('v21NpcStatus').textContent='已接取，討伐十隻妖獸後回來領取。';return;}if(state.claimed){$('v21NpcStatus').textContent='本次傳承已領取';return;}if((h.killCount||0)-state.start<10){$('v21NpcStatus').textContent='討伐數量不足';return;}state.claimed=true;const pool=HighRealmData.skills.filter(s=>s.realm<=p.realm&&s.realm>=map.level-1),s=pool[Math.floor(Math.random()*pool.length)];HighRealms.give(p,s.bookId,1);HighRealms.reward(p,{claimId:'v21npc:'+point.id,realm:map.level,role:'encounter'});Economy.reward(p,'v21npc:'+point.id,'encounter','rare');economyHydrate();save(true);$('v21NpcStatus').textContent='傳承已保存：'+s.name+' 技能書';}}]);return true;};$('interact').onclick=interactPoint;
const v21Journey=updateJourney;updateJourney=function(){const npc=nearestPoint();if(npc?.kind==='npc'){discoveredPoint=npc;$('interact').disabled=false;$('interact').textContent='交談 · '+npc.name;$('journeyHint').textContent='已抵達 '+npc.name;return;}v21Journey();};
const v21Landmark=Progression.collectLandmark;Progression.collectLandmark=function(player,map,point,vitals,now){const r=v21Landmark(player,map,point,vitals,now);if(r.ok&&MAPS[map]?.highRealm&&point.kind==='ruins'){const theme=MAPS[map];HighRealms.reward(player,{claimId:'v21ruin:'+theme.id,realm:theme.level,role:'encounter'});}return r;};
const v21Dungeons=renderDungeons;renderDungeons=function(){v21Dungeons();if(tab!=='dungeons')return;document.querySelectorAll('[data-map]').forEach(b=>{const m=MAPS[Number(b.dataset.map)];if(m?.highRealm){const progress=p.highRealms?.progress?.[m.id];if(progress){const line=document.createElement('p');line.textContent='已擊敗 '+progress.kills+' 名敵人'+(m.zone===4?' · 首領勝利 '+progress.bossWins+' 次':'');b.before(line);}}if(m?.finished&&!p.finished){b.disabled=true;b.textContent='完成渡劫後解鎖';}});};
function v21PlayerDamage(amount){const st=stats();p.hp-=EconomyCombat.incoming(Math.max(1,amount-st.def*.35),Economy.bonuses(p));if(p.hp<=0){p.hp=st.hp*.55;switchMap(0,true);save(true);note('高階戰鬥受創，遁回安全地帶');}}
const v21Hurt=hurtEnemy;hurtEnemy=function(enemy,damage){if(enemy?.highRealm&&enemy.hp>0){if(enemy.shield>0){const n=Math.min(enemy.shield,damage);enemy.shield-=n;damage-=n;}if(enemy.reflectUntil>Date.now())v21PlayerDamage(damage*.12);}return v21Hurt(enemy,damage);};
const v21Fire=fireCompanion;fireCompanion=function(key,...args){const start=projectiles.length,result=v21Fire(key,...args);for(const shot of projectiles.slice(start))shot.damage*=1+v21BuffValue('companion');const id=key.split(':')[1],it=p?.economy?.instances[id],t=it&&EconomyData.templates[it.baseId];if(result&&t?.highRealm){const mode=t.skillMode,st=stats();if(['mana','restore'].includes(mode))p.mp=Math.min(st.mp,p.mp+st.mp*.04);if(['heal','revive','restore','leech'].includes(mode))p.hp=Math.min(st.hp,p.hp+st.hp*.025);if(['shield','armor'].includes(mode)){p.highRealms.shield=Math.max(p.highRealms.shield||0,st.hp*.04);p.highRealms.shieldUntil=Date.now()+3000;}if(['chain','multi','aoe','burn','slow'].includes(mode)){for(const shot of projectiles.slice(start,start+1))for(const target of HighRealms.targets(enemies,shot.target,100,3).filter(e=>e!==shot.target))hurtEnemy(target,shot.damage*.2);}if(['cultivate','reveal','companion','armor'].includes(mode))v21Buff(mode,mode==='reveal'?.05:.15,3000);if(mode==='cleanse'){p.highRealms.dot=null;p.highRealms.silencedUntil=0;p.highRealms.slowUntil=0;}if(mode==='clone')p.highRealms.clone={until:Date.now()+4000,next:Date.now(),x:p.position.x-40,y:p.position.y};if(['slow','silence','burn'].includes(mode)){for(const shot of projectiles.slice(start,start+1))for(const e of HighRealms.targets(enemies,shot.target,100,3)){if(mode==='slow'){e.slow=.3;e.slowUntil=Date.now()+2000;}if(mode==='silence')e.silencedUntil=Date.now()+1500;if(mode==='burn')e.v21Burn={until:Date.now()+2000,damage:shot.damage*.1};}}if(mode==='meteor'){const target=projectiles[start]?.target;if(target)p.highRealms.meteor={at:Date.now()+900,x:target.x,y:target.y,damage:projectiles[start].damage*.4,radius:100};}if(mode==='teleport'){p.position.x=clamp(p.position.x-60,40,1460);}}return result;};
function stepV21(dt){if(!p)return;const h=HighRealms.normalize(p),now=Date.now();if(h.dot?.until>now)v21PlayerDamage(h.dot.damage*dt);if(h.meteor&&now>=h.meteor.at){const m=h.meteor;h.meteor=null;for(const e of HighRealms.targets(enemies,m,m.radius,5))hurtEnemy(e,m.damage);effects.push({x:m.x,y:m.y,t:.8,kind:'fire'});}if(h.clone?.until>now&&now>=h.clone.next){h.clone.next=now+1200;const e=targetNear(360);if(e)projectiles.push({x:h.clone.x,y:h.clone.y,target:e,damage:stats().atk*.45,speed:550,kind:'sword'});}
 for(const e of enemies.slice()){if(!e.highRealm||e.hp<=0)continue;if(e.v21Burn?.until>now)hurtEnemy(e,e.v21Burn.damage*dt);if(e.hp<=0)continue;const ratio=e.hp/e.maxHp;if(e.role==='boss'&&ratio<.5&&!e.phase){e.phase=1;e.atk*=1.2;e.skillTimer=.2;note(e.name+' 進入第二階段！');}if(e.role==='boss'&&ratio<.2&&e.phase!==2){e.phase=2;e.atk*=1.25;e.shield=e.maxHp*.08;note(e.name+' 狂暴變身！');}
 if(e.warning&&now>=e.warning.at){const w=e.warning;e.warning=null;effects.push({x:w.x,y:w.y,t:.7,kind:w.mode==='slow'?'sword':'fire'});const dist=Math.hypot(p.position.x-w.x,p.position.y-w.y);let hit=dist<=w.radius;if(w.mode==='cone'){const angle=Math.atan2(p.position.y-e.y,p.position.x-e.x);hit=Math.hypot(p.position.x-e.x,p.position.y-e.y)<240&&Math.abs(Math.atan2(Math.sin(angle-w.angle),Math.cos(angle-w.angle)))<.7;}if(hit){v21PlayerDamage(e.atk*(w.mode==='heavy'?1.8:1.1));if(w.mode==='slow')h.slowUntil=now+3500;if(w.mode==='silence')h.silencedUntil=now+2000;if(w.mode==='burn'||w.mode==='poison')h.dot={until:now+4000,damage:e.atk*.12};if(w.mode==='drain')p.mp=Math.max(0,p.mp-stats().mp*.2);if(w.mode==='leech')e.hp=Math.min(e.maxHp,e.hp+e.maxHp*.05);if(w.mode==='armorBreak')v21Buff('armor',-.3,4000);}continue;}
 if(e.silencedUntil>now)continue;e.skillTimer-=dt;if(e.skillTimer>0||Math.hypot(e.x-p.position.x,e.y-p.position.y)>550)continue;e.skillTimer=e.phase?3.5:5.5;const mode=e.skills[e.skillIndex++%e.skills.length];if(mode==='shield'){e.shield=e.maxHp*.12;continue;}if(mode==='heal'){e.hp=Math.min(e.maxHp,e.hp+e.maxHp*.08);continue;}if(mode==='reflect'){e.reflectUntil=now+2500;continue;}if(mode==='rage'){if(!e.raged){e.atk*=1.15;e.raged=true;}continue;}if(mode==='teleport'){e.x=clamp(p.position.x+120,50,1450);e.y=clamp(p.position.y+80,60,840);continue;}if(mode==='summon'){if(enemies.length<8&& !e.summoned){enemies.push({...e,name:e.name+'・分身',hp:e.maxHp*.12,maxHp:e.maxHp*.12,atk:e.atk*.3,role:'normal',summoned:true,x:e.x+55,warning:null,skills:['heavy'],skillTimer:3});}continue;}e.warning={mode,x:p.position.x,y:p.position.y,radius:mode==='heavy'?65:mode==='chain'?150:115,angle:Math.atan2(p.position.y-e.y,p.position.x-e.x),at:now+1100};}
 const map=MAPS[mapIndex];if(map?.highRealm&&['thunder','void'].includes(map.theme)){if(h.hazard&&h.hazard.map!==map.id)h.hazard=null;if(!h.hazard)h.hazard={map:map.id,x:p.position.x+40,y:p.position.y+10,at:now+6000};if(now>=h.hazard.at){const w=h.hazard;if(Math.hypot(p.position.x-w.x,p.position.y-w.y)<85)v21PlayerDamage(stats().hp*.12);effects.push({x:w.x,y:w.y,t:.7,kind:'fire'});h.hazard={map:map.id,x:p.position.x+Math.random()*100-50,y:p.position.y+Math.random()*100-50,at:now+6000};}}
}
const v21LootSummons=gainLoot;gainLoot=function(e){if(e.summoned)return;return v21LootSummons(e);};
const v21DrawGround=drawGround;drawGround=function(g,time){const map=MAPS[mapIndex];if(!map?.highRealm||riftRunning)return v21DrawGround(g,time);const im=v21Image('v21_floor_'+map.theme);if(im)g.drawImage(im,0,0,1500,900);else v21DrawGround(g,time);g.save();g.strokeStyle='#d6d2b244';g.lineWidth=45;g.beginPath();const z=map.zone;g.moveTo(0,700-z*65);g.bezierCurveTo(400,80+z*90,800,800-z*120,1500,180+z*120);g.stroke();for(let i=0;i<15;i++){const x=(i*317+z*151)%1450,y=(i*211+z*83)%850,prop=v21Image('v21_prop_'+map.theme+'_'+i%3);if(prop)g.drawImage(prop,x,y,90+i%3*15,100+i%3*15);}g.restore();};
const v21DrawCreature=drawCreature;drawCreature=function(g,x,y,size,color,pet=false,enemy=null){if(enemy?.highRealm){const im=v21Image(enemy.assetId);if(im){const n=enemy.role==='boss'?130:enemy.role==='cultivator'?92:72,scale=enemy.phase===2?1.3:1;g.drawImage(im,x-n*scale/2,y-n*scale,n*scale,n*scale);return;}}v21DrawCreature(g,x,y,size,color,pet,enemy);};
const v21DrawLandmarks=drawLandmarks;drawLandmarks=function(g,time){const map=MAPS[mapIndex];if(!map?.highRealm||riftRunning)return v21DrawLandmarks(g,time);for(const point of currentPoints()){g.save();g.translate(point.x,point.y);g.strokeStyle='#d8c58a';g.beginPath();g.ellipse(0,10,30,10,0,0,Math.PI*2);g.stroke();const im=point.kind==='npc'?v21Image(point.assetId):v21Image('v21_prop_'+map.theme+'_'+(['spring','herbs','ore','ruins'].indexOf(point.kind)%3));if(im)g.drawImage(im,-40,-75,80,85);else{g.fillStyle='#d5c586';g.font='22px serif';g.textAlign='center';g.fillText(point.mark||'仙',0,-20);}g.fillStyle='#102e35';g.fillRect(-65,-104,130,22);g.fillStyle='#e7d5a0';g.font='11px serif';g.textAlign='center';g.fillText(point.name,0,-89);g.restore();}};
const v21DrawScene=drawScene;drawScene=function(g,W,H,time){v21DrawScene(g,W,H,time);if(!p?.highRealms)return;const zoom=Math.max(W/850,H/490);g.save();g.scale(zoom,zoom);g.translate(-cam.x,-cam.y);for(const e of enemies){if(!e.highRealm||!e.warning)continue;const w=e.warning;g.fillStyle='#ec705344';g.strokeStyle='#ffd18d';g.beginPath();g.arc(w.x,w.y,w.radius,0,Math.PI*2);g.fill();g.stroke();g.fillStyle='#ffe9b8';g.font='12px serif';g.fillText(w.mode,w.x-20,w.y-10);}const h=p.highRealms;if(h.hazard?.map===MAPS[mapIndex]?.id){g.strokeStyle='#cebbff';g.beginPath();g.arc(h.hazard.x,h.hazard.y,85,0,Math.PI*2);g.stroke();}if(h.clone?.until>Date.now()){g.globalAlpha=.45;drawCharacter(g,h.clone.x,h.clone.y,time);}g.restore();};

const v21EconomyReward=Economy.reward;Economy.reward=function(player,key,kind,...args){const result=v21EconomyReward(player,key,kind,...args);if(result.ok&&kind==='encounter'&&player.realm>=4)HighRealms.reward(player,{claimId:'v21:'+key,realm:player.realm,role:'encounter'});return result;};
