'use strict';
const legendBell=document.createElement('button');legendBell.id='legendBell';legendBell.className='btn line';legendBell.setAttribute('aria-label','傳說掉落通知');legendBell.onclick=showLegendAlerts;document.querySelector('.top-actions').prepend(legendBell);
function renderLegendBell(){if(!p)return;const n=LegendAlerts.pending(p).length;legendBell.textContent='🔔 '+n;legendBell.title='傳說掉落通知 · '+n+' 件待處理';legendBell.classList.toggle('legend-unread',n>0);}
function showLegendAlerts(){const list=LegendAlerts.pending(p);modal('🔔 傳說掉落通知','<p>傳說獎勵已保存。可直接裝備或設為主選，不必先清背包；換下物品無空間時會留在未領取匣。</p><div class="legend-list">'+list.map(it=>{const t=EconomyData.templates[it.baseId]||it.template;return '<button class="btn line" data-legend-id="'+it.id+'"><img src="'+economyAsset(t.assetId)+'" alt=""><span>'+escapeHTML(t.name)+'<small>'+REALMS[it.realm].name+' · '+(p.economy.mail.includes(it.id)?'未領取匣':'已持有')+'</small></span></button>';}).join('')+'</div>'+(!list.length?'<p>目前沒有待處理的傳說物品。</p>':''),[{text:'關閉'}]);document.querySelectorAll('[data-legend-id]').forEach(b=>b.onclick=()=>showLegendItem(b.dataset.legendId));}
function showLegendItem(id){const it=p.economy.instances[id];if(!it)return showLegendAlerts();const t=EconomyData.templates[it.baseId]||it.template,old=t.type==='equip'?p.equipment[t.slot]:p[t.type==='pet'?'activePet':'activeTreasure'],previous=p.economy.instances[old],next=Economy.effects(it),before=previous?Economy.effects(previous):ITEMS[old]||{},diff=t.type==='equip'?'<p>更換裝備差值：'+['atk','def','hp'].map(k=>economyEffectName(k)+' '+((next[k]||0)-(before[k]||0)>=0?'+':'')+Math.round((next[k]||0)-(before[k]||0))).join(' · ')+'</p>':'';
 modal('傳說 · '+t.name,economyDescription(it)+diff+'<p>換下的物品會完整保留；鎖定、強化與鑲嵌資料不變。</p><p id="legendActionStatus" role="status"></p>',[{text:'稍後處理',fn:showLegendAlerts},{text:'保留並收起提醒',fn:()=>{LegendAlerts.dismiss(p,id);save(true);renderLegendBell();showLegendAlerts()}},{text:t.type==='equip'?'直接裝備':t.type==='pet'?'設為主靈寵':'設為本命法寶',style:'gold',fn:()=>{const r=LegendAlerts.equip(p,id,ITEMS);if(!r.ok)return $('legendActionStatus').textContent=(r.reason==='realm'?'境界不足，獎勵仍為你保留':'物品狀態已變動，請重新開啟通知');economyHydrate();p.hp=Math.min(p.hp,stats().hp);p.mp=Math.min(p.mp,stats().mp);save(true);renderAll();renderLegendBell();modal('傳說已配置','<p>'+escapeHTML(t.name)+' 已'+(t.type==='equip'?'裝備':'設為主選')+'。換下物品已保留。</p>',[{text:'完成',style:'gold'}]);}}]);}
const legendUIBase=renderUI;renderUI=function(){legendUIBase();renderLegendBell()};
// Tag only reward dialogs. Replacement dialogs invalidate the timer ownership.
const legendModalBase=modal;let rewardDialogSequence=0;
modal=function(title,html,buttons){const sequence=++rewardDialogSequence;legendModalBase(title,html,buttons);if(title!=='魔修已伏誅 · 擊殺獎勵')return;const deadline=Date.now()+10000,clock=document.createElement('p');clock.id='rewardCountdown';clock.setAttribute('role','status');$('modalContent').prepend(clock);const interval=setInterval(()=>{if(sequence!==rewardDialogSequence||$('modal').classList.contains('hidden')){clearInterval(interval);return;}const left=LegendAlerts.seconds(deadline);clock.textContent='剩餘 '+left+' 秒自動關閉 · 傳說物品可由 🔔 通知查看';if(!left){clearInterval(interval);closeModal();}},200);clock.textContent='剩餘 10 秒自動關閉 · 傳說物品可由 🔔 通知查看';};
