'use strict';
// v3 presentation and systems integration. Legacy save format and core combat remain compatible.
let destination=null, activeView='explore', discoveredPoint=null, recentNotice='', recentNoticeAt=0, explorationGraceUntil=0;
const oldNote=note;
note=function(message){const now=performance.now();if(message===recentNotice && now-recentNoticeAt<2200)return;recentNotice=message;recentNoticeAt=now;oldNote(message)};
const originalStart=startGame;
startGame=function(){const previous=storage.getItem(SAVE);if(previous&&!storage.getItem(SAVE+'_PRE_V3'))storage.setItem(SAVE+'_PRE_V3',previous);p=Progression.normalize(p);originalStart();setView('explore');updateJourney();};
const originalSwitchMap=switchMap;
switchMap=function(index,force=false){destination=null;const savedPosition=force&&index===p.mapIndex?{...p.position}:null;const ok=originalSwitchMap(index,force);if(ok&&savedPosition)p.position={x:clamp(savedPosition.x,40,1460),y:clamp(savedPosition.y,55,845)};if(ok){if(p.exploration)updateJourney();save(true)}return ok};
const originalChoose=chooseTab;
chooseTab=function(id){originalChoose(id);setView('manage');};
function setView(view){activeView=view;$('game').dataset.view=view;document.querySelectorAll('button[data-view]').forEach(b=>{const selected=b.dataset.view===view;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',String(selected))});}
document.querySelectorAll('button[data-view]').forEach(b=>b.onclick=()=>{setView(b.dataset.view);window.scrollTo({top:0,behavior:'smooth'})});
const originalUI=renderUI;
renderUI=function(){originalUI();if(!p)return;const now=performance.now();document.querySelectorAll('[data-cast]').forEach(b=>{const which=Number(b.dataset.cast),remaining=Math.max(0,(cd[which]-now)/1000),affordable=which===0||p.mp>=SKILLS[which-1].cost;b.classList.toggle('depleted',!affordable);b.classList.toggle('cooling',remaining>0);b.querySelector('small').textContent=remaining>0?remaining.toFixed(1)+'s':!affordable?'真元不足':['普攻','離火','御劍','回春'][which];b.setAttribute('aria-label',['普通攻擊','離火真訣','萬劍歸宗','青木回春'][which]+(remaining>0?' 冷卻中':''))});$('mapPrev').disabled=mapIndex===0;$('mapNext').disabled=mapIndex===MAPS.length-1;$('autoCombat').classList.toggle('enabled',auto);$('autoMeditate').classList.toggle('enabled',autoMeditate);$('breakChance').textContent=p.finished?'已飛升成仙':'突破成功率 '+Math.round(clamp(realm().rate+(p.stage===realm().stages-1&&count('trib')>0?.25:0),.08,.99)*100)+'%';updateJourney();};
const originalCast=cast;
cast=function(which,automatic=false){if(automatic && !Progression.canAutoCast(which,p.mp,p.hp,stats().hp))return;return originalCast(which)};
const originalBreak=breakthrough;
breakthrough=function(){const previous=p.realm,stage=p.stage;originalBreak();const action=$('modalActions').lastElementChild;if(!action||p.qi<qiMax()||p.finished)return;const proceed=action.onclick;action.onclick=()=>{proceed();if(p.realm!==previous||p.stage!==stage||p.finished){p.breakthroughs++;save(true);const s=stats();modal(p.finished?'羽化登仙':'道境已成',`<div class="realm-seal">${escapeHTML(realm().name)}</div><p class="celebration">${escapeHTML(p.name)} · ${realmLabel()}</p><p class="muted">天地靈氣匯聚，新的仙途已開啟。</p><div class="result-stats"><span>攻擊<strong>${fmt(s.atk)}</strong></span><span>氣血<strong>${fmt(s.hp)}</strong></span><span>防禦<strong>${fmt(s.def)}</strong></span></div>`,[{text:'繼續問道',style:'gold'}]);}};};
$('breakthrough').onclick=()=>breakthrough();
function currentPoints(){return Progression.landmarks;}
function nearestPoint(){return currentPoints().find(point=>Math.hypot(point.x-p.position.x,point.y-p.position.y)<100)}
function updateJourney(){if(!p?.exploration)return;let nearest=nearestPoint();discoveredPoint=nearest||null;const visited=currentPoints().filter(point=>p.exploration.visited[Progression.key(mapIndex,point.id)]).length;$('journeyProgress').textContent=visited+' / '+currentPoints().length+' 地點';$('journeyHint').textContent=destination?'正在前往 '+destination.name+' · 手動移動可取消':nearest?'已抵達 '+nearest.name+' · 可互動':'探索靈泉、草坡、礦脈與古修遺跡';const interact=$('interact');interact.disabled=!nearest;if(nearest){const state=Progression.landmarkState(p,mapIndex,nearest);interact.textContent=state.claimed?'傳承已領取':state.ready?'互動 · '+nearest.name:'恢復中 · '+state.seconds+'s';interact.disabled=!state.ready;}else interact.textContent='靠近地點互動';if(nearest){const key=Progression.key(mapIndex,nearest.id);if(!p.exploration.visited[key]){p.exploration.visited[key]=true;log('發現 '+MAPS[mapIndex].name+' · '+nearest.name,'good');save(true)}}}
function interactPoint(){const point=nearestPoint();if(!point)return;const state=Progression.landmarkState(p,mapIndex,point);if(!state.ready)return;const key=Progression.key(mapIndex,point.id);explorationGraceUntil=performance.now()+1500;if(point.kind==='spring'){p.hp=stats().hp;p.mp=stats().mp;note('靈泉洗塵 · 氣血與真元已恢復')}if(point.kind==='herbs'){p.herbs+=3;note('採集靈草 ×3 · 已送入洞府')}if(point.kind==='ore'){p.stones+=25*(mapIndex+1);add('wood',2);note('獲得靈石 '+25*(mapIndex+1)+' · 靈木 ×2')}if(point.kind==='ruins'){p.stones+=60*(mapIndex+1);p.jade+=5;p.exploration.claimed[key]=true;note('古修傳承 · 仙玉 +5，靈石 +'+60*(mapIndex+1))}p.exploration.cooldowns[key]=Date.now()+point.cooldown;log('探索 '+point.name+' · '+point.desc,'good');renderAll();save(true)}
$('interact').onclick=interactPoint;
$('atlas').onclick=()=>modal('山海圖卷',`<p class="muted">選擇地點後自動行走。探索途中暫停自動追敵，手動方向鍵可取消。</p><svg class="atlas-map" viewBox="0 0 300 180" role="img" aria-label="目前地圖與探索地點"><rect width="300" height="180" rx="12" fill="#102b30"/><path d="M0 120Q85 60 160 85T300 65" fill="none" stroke="#778d6b" stroke-width="18" opacity=".3"/>${currentPoints().map(point=>`<circle cx="${point.x/5}" cy="${point.y/5}" r="7" fill="#d5bf88"/><text x="${point.x/5}" y="${point.y/5-14}" text-anchor="middle" fill="#e7d8ae" font-size="10">${point.name}</text>`).join('')}<circle cx="${p.position.x/5}" cy="${p.position.y/5}" r="4" fill="#a6ecd1"/></svg><div class="atlas-list">${currentPoints().map(point=>`<button class="atlas-point" data-destination="${point.id}"><span class="atlas-mark">${point.mark}</span><span><b>${point.name}</b><small>${point.desc}</small></span><em>${p.exploration.visited[Progression.key(mapIndex,point.id)]?'已發現':'待探索'}</em></button>`).join('')}</div>`,[{text:'收起圖卷'}]);
$('atlas').addEventListener('click',()=>document.querySelectorAll('[data-destination]').forEach(button=>button.onclick=()=>{destination=currentPoints().find(point=>point.id===button.dataset.destination);closeModal();setView('explore');note('前往 '+destination.name);updateJourney()}));
function stepExploration(dt){if(!p?.exploration)return;const moving=moveTouch||['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].some(key=>keys.has(key));if(moving){destination=null;explorationGraceUntil=0}if(destination&&!moving){const dx=destination.x-p.position.x,dy=destination.y-p.position.y,d=Math.hypot(dx,dy);if(d<35){note('已抵達 '+destination.name);destination=null;explorationGraceUntil=performance.now()+8000;}else{const step=Math.min(190*dt,d);p.position.x+=dx/d*step;p.position.y+=dy/d*step;}}}
function drawLandmarks(g,time){for(const point of currentPoints()){const visited=p.exploration.visited[Progression.key(mapIndex,point.id)];g.save();g.translate(point.x,point.y);g.strokeStyle=visited?'#86d9c0':'#e5c786';g.fillStyle='#102e32';g.lineWidth=2;g.beginPath();g.ellipse(0,9,38,13,0,0,Math.PI*2);g.fill();g.stroke();if(point.kind==='spring'){g.fillStyle='#79cfdb';g.beginPath();g.ellipse(0,5,26,8,0,0,Math.PI*2);g.fill();}else if(point.kind==='herbs'){for(let i=-1;i<=1;i++){g.fillStyle='#89bfa0';g.beginPath();g.ellipse(i*14,-3,7,20,i*.6,0,Math.PI*2);g.fill()}}else{g.fillStyle=point.kind==='ore'?'#839baf':'#c7b78e';g.beginPath();g.moveTo(-24,5);g.lineTo(-12,-24);g.lineTo(8,-33);g.lineTo(27,3);g.closePath();g.fill();}g.fillStyle='#122d32';g.fillRect(-42,-66,84,24);g.fillStyle=visited?'#a7e6cb':'#eed69f';g.textAlign='center';g.font='12px serif';g.fillText(point.name,0,-49);g.restore();}}
const originalGround=drawGround;
drawGround=function(g,t){originalGround(g,t);drawLandmarks(g,t)};
// A shared ink silhouette replaces platform-specific creature emoji in the scene.
function drawCreature(g,x,y,size,color,pet=false){g.save();g.translate(x,y);g.fillStyle='#04171966';g.beginPath();g.ellipse(0,8,size,6,0,0,Math.PI*2);g.fill();g.fillStyle=color;g.strokeStyle='#e4d6b291';g.lineWidth=1.5;g.beginPath();g.moveTo(-size,0);g.lineTo(-size*.8,-size);g.lineTo(-size*.55,-size*1.55);g.lineTo(-size*.2,-size);g.lineTo(size*.35,-size);g.lineTo(size*.7,-size*1.5);g.lineTo(size,-size*.4);g.lineTo(size*.75,size*.2);g.lineTo(-size*.8,size*.2);g.closePath();g.fill();g.stroke();g.fillStyle=pet?'#eff8d4':'#ffce97';g.beginPath();g.arc(-size*.32,-size*.53,2,0,Math.PI*2);g.arc(size*.32,-size*.53,2,0,Math.PI*2);g.fill();g.restore();}
drawPet=function(g,x,y,t){if(!p.activePet)return;drawCreature(g,x-38,y+Math.sin(t*3)*3,13,'#d7be87',true)};
renderAbode=function(){const now=Date.now(),estate=p.estate;const pending=estate.sect*Math.floor(Math.min(14400000,Math.max(0,now-estate.incomeAt))/60000)*3;$('panelContent').innerHTML=`<div class="estate-banner"><span>洞天福地</span><h3>${escapeHTML(p.name)}的山居</h3><p>種植靈草、煉製丹藥，讓探索所得成為長久的根基。</p></div><div class="cards"><div class="card"><div class="mini-label">CULTIVATION</div><h3>太虛聚靈陣 · ${p.array} 階</h3><p>靈氣吸收 +${qps().toFixed(1)} /秒</p><button class="btn cyan" id="upgradeArray">升級 · ${p.array*60} 靈石</button></div><div class="card"><div class="mini-label">SECT</div><h3>${estate.sect?'山門 · '+estate.sect+' 階':'開闢山門'}</h3><p>${estate.sect?'門人經營產出 '+estate.sect*3+' 靈石／分鐘，最多累積 4 小時。':'建立山門，招募門人經營洞府。'}</p><button class="btn gold" id="sectUpgrade" ${estate.sect>=5?'disabled':''}>${estate.sect>=5?'山門已達五階':(estate.sect?'擴建山門':'建立山門')+' · '+180*(estate.sect+1)+' 靈石'}</button><button class="btn line" id="sectIncome" ${pending?'':'disabled'}>領取收益 · ${pending} 靈石</button></div></div><h3 class="section-title estate-heading">靈藥園 <small>庫存 ${p.herbs} 株 · 90 秒成熟 · 離線繼續生長</small></h3><div class="farm-grid">${estate.plots.map((plot,i)=>{const ready=plot&&now>=plot.readyAt;return `<div class="farm-plot ${ready?'ripe':''}"><span class="farm-glyph">${plot?'芽':'田'}</span><h3>靈田 ${i+1}</h3><p data-plot-clock="${i}">${!plot?'空閒靈田':ready?'靈草已成熟':Math.ceil((plot.readyAt-now)/1000)+' 秒後成熟'}</p><button class="btn ${ready?'gold':'line'}" data-plot="${i}" ${plot&&!ready?'disabled':''}>${!plot?'播種 · 12 靈石':ready?'收穫 · '+(4+estate.sect)+' 株':'培育中'}</button></div>`}).join('')}</div><div class="cards"><div class="card"><div class="mini-label">ALCHEMY</div><h3>九陽煉丹爐</h3><p>聚氣丹：靈草 ×2、靈石 ×10</p><button class="btn cyan" id="alchemyQi">煉製聚氣丹</button><p>護劫丹：靈草 ×5、靈石 ×80</p><button class="btn line" id="alchemyTrib">煉製護劫丹</button></div><div class="card"><div class="mini-label">REST</div><h3>修士居所</h3><p>調息恢復全部氣血與真元。</p><button class="btn cyan" id="rest">靜心養傷</button><button class="btn line" id="harvest">後山採藥 · 每 30 秒一次</button></div></div>`;$('upgradeArray').onclick=()=>{if(p.stones<p.array*60)return note('靈石不足');p.stones-=p.array*60;p.array++;finishEstate('聚靈陣升階成功')};$('sectUpgrade').onclick=()=>{if(!Progression.establish(p))return note('靈石不足或山門已達上限');finishEstate('山門已擴建 · 門人開始經營')};$('sectIncome').onclick=()=>{const gain=Progression.income(p);finishEstate('山門收益 · 靈石 +'+gain)};document.querySelectorAll('[data-plot]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.plot);if(p.estate.plots[i]){const gain=Progression.harvest(p,i);if(gain)finishEstate('收穫靈草 ×'+gain)}else{if(!Progression.plant(p,i))return note('靈石不足');finishEstate('已播種 · 90 秒後成熟')}});$('alchemyQi').onclick=()=>alchemy('pill',2,10);$('alchemyTrib').onclick=()=>alchemy('trib',5,80);$('rest').onclick=()=>{p.hp=stats().hp;p.mp=stats().mp;finishEstate('氣血與真元已恢復')};$('harvest').onclick=()=>{if(Date.now()-p.lastHarvest<30000)return note('靈草尚未成熟');p.lastHarvest=Date.now();p.herbs+=3;finishEstate('後山收穫靈草 ×3')};};
function finishEstate(message){note(message);renderAll();save(true)}
setInterval(()=>{if(!p||$('game').classList.contains('hidden')||tab!=='abode'||activeView!=='manage')return;const now=Date.now();document.querySelectorAll('[data-plot-clock]').forEach(el=>{const i=Number(el.dataset.plotClock),plot=p.estate.plots[i];if(!plot)return;const ready=plot.readyAt<=now;el.textContent=ready?'靈草已成熟':Math.ceil((plot.readyAt-now)/1000)+' 秒後成熟';if(ready){const button=document.querySelector(`[data-plot="${i}"]`);button.disabled=false;button.textContent='收穫 · '+(4+p.estate.sect)+' 株';button.classList.add('gold');el.parentElement.classList.add('ripe')}});const amount=p.estate.sect*Math.floor(Math.min(14400000,Math.max(0,now-p.estate.incomeAt))/60000)*3;$('sectIncome').textContent='領取收益 · '+amount+' 靈石';$('sectIncome').disabled=!amount;},1000);
$('journeyBack').onclick=()=>setView('explore');
window.addEventListener('keydown',event=>{if(event.key.toLowerCase()==='e' && p && event.target.tagName!=='INPUT' && $('modal').classList.contains('hidden'))interactPoint()});
document.querySelectorAll('#nav .ni').forEach((icon,i)=>icon.textContent=['☯','匣','劍','訣','靈','寶','山','府'][i]);
$('instructions').onclick=()=>modal('山海行旅 · 修真指引','<p>在「山海探索」使用方向鍵行走，打開山海圖卷可前往靈泉、靈草坡、礦脈與古修遺跡。靠近地點後按互動，桌面也可按 E。</p><p>可開啟自動戰鬥與自動打坐；真元不足時不會反覆嘗試施法，修為滿值後仍會恢復真元。滿修為時可衝擊境界。</p><p>在「洞天養成」管理裝備、技能、靈寵與洞府。靈田需播種、等待成熟再收穫；山門可以產出靈石，請手動領取收益。</p><p>角色進度每 15 秒存於本機瀏覽器。換裝置前，請在設定匯出 JSON 存檔。</p>',[{text:'踏上仙途',style:'gold'}]);
const originalSettings=$('settings').onclick;
$('settings').onclick=()=>{originalSettings();if(storage.getItem(SAVE+'_PRE_V3')){const button=document.createElement('button');button.className='btn line';button.textContent='匯出升級前備份';button.onclick=()=>{const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([storage.getItem(SAVE+'_PRE_V3')],{type:'application/json'}));link.download='太虛仙途_升級前備份.json';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);note('升級前備份已匯出')};$('modalActions').append(button)}};
