'use strict';
const Economy=(()=>{
 const D=typeof EconomyData!=='undefined'?EconomyData:require('../data/economy.js');
 const roll=(r)=>Math.max(0,Math.min(.999999999,Number(r())||0));
 const pick=(list,r)=>list[Math.floor(roll(r)*list.length)];
 const integer=(range,r)=>range[0]+Math.floor(roll(r)*(range[1]-range[0]+1));
 function normalize(p){const e=p.economy||{};p.economy={...e,version:1,sequence:e.sequence||0,instances:e.instances||{},legacy:e.legacy||{},claims:e.claims||{},drops:e.drops||[],forgeLog:e.forgeLog||[],mail:e.mail||[],worlds:e.worlds||{},loadout:{pets:Array(6).fill(null),treasures:Array(6).fill(null),...e.loadout}};p.equipment={...p.equipment,belt:p.equipment.belt||null,charm:p.equipment.charm||null};return p.economy;}
 function create(p,baseId,quality,source,r=Math.random){const t=D.templates[baseId];if(!t||!['equip','treasure','pet'].includes(t.type)||!Number.isInteger(quality)||quality<0||quality>4||(t.legendOnly&&quality!==4))throw Error('Invalid item template/quality');const e=normalize(p),q=D.qualities[quality];let id;do{id='xi_'+(++e.sequence);}while(e.instances[id]);const pool=D.affixes.filter(a=>quality>=a.min),affixes=[];const n=integer(q.affixes,r);for(let i=0;i<n;i++){const a=pool.splice(Math.floor(roll(r)*pool.length),1)[0];affixes.push({key:a.key,name:a.name,value:Number((a.value*(1+(t.level||1)*.15)*q.scale).toFixed(5))});}const item={id,baseId,quality,level:t.level||1,base:{atk:Math.round((t.atk||0)*q.scale),def:Math.round((t.def||0)*q.scale),hp:Math.round((t.hp||0)*q.scale)},affixes,enhancement:0,sockets:Array(integer(q.holes,r)).fill(null),source,realm:t.realm||0,growth:t.growth||1,cultivation:0,evolution:0};e.instances[id]=item;return item;}
 function legacy(p,id,catalog){const e=normalize(p);if(!e.legacy[id]){const t=catalog[id];if(!t)return null;const q=Math.min(4,t.rarity||0);e.legacy[id]={id:'legacy:'+id,baseId:id,quality:q,level:1,base:{atk:t.atk||0,def:t.def||0,hp:t.hp||0},affixes:[],enhancement:0,sockets:[],source:'舊存檔保留',realm:t.realm||0};}return e.legacy[id];}
 function effects(item){const q={},factor=1+item.enhancement*D.config.enhance.step;for(const [k,v]of Object.entries(item.base))q[k]=v*factor;for(const a of item.affixes)q[a.key]=(q[a.key]||0)+a.value;for(const id of item.sockets){const g=D.templates[id];if(g?.type==='gem')for(const [k,v]of Object.entries(g.effects))q[k]=(q[k]||0)+v;}return q;}
 function stored(p,type){if(type==='pet')return Object.keys(p.levelPet||{}).filter(k=>p.levelPet[k]>0).length;if(type==='treasure')return p.ownedTreasures.length;return p.inventory.filter(x=>(D.templates[p.economy.instances[x.id]?.baseId]||p.economy.instances[x.id]?.template)?.type==='equip'||D.templates[x.id]?.type==='equip'||(!D.templates[x.id]&&!x.id.startsWith('gem_')&&['sword','robe','crown','boots','ring','earrings','inner','legs','necklace','bracelet','jadeSword','starRobe','belt','charm'].includes(x.id))).length;}
 function grant(p,item){if(held(p,item.id))return true;const t=D.templates[item.baseId]||item.template,cat=t.type==='pet'?'pets':t.type==='treasure'?'treasures':'equipment';if(stored(p,t.type)>=(p.bag?.capacities?.[cat]||100)){if(!p.economy.mail.includes(item.id))p.economy.mail.push(item.id);return false;}if(t.type==='pet')p.levelPet[item.id]=1;else if(t.type==='treasure')p.ownedTreasures.push(item.id);else p.inventory.push({id:item.id,count:1});return true;}
 function held(p,id){return p.inventory.some(x=>x.id===id)||Object.values(p.equipment).includes(id)||p.ownedTreasures.includes(id)||p.levelPet[id]>0;}
 function bonuses(p){const out={};const ids=[...Object.values(p.equipment),p.activeTreasure,p.activePet].filter(Boolean);for(const id of new Set(ids)){const it=p.economy?.instances[id]||p.economy?.legacy[id];if(!it)continue;const fx=effects(it);const legacy=!!p.economy.legacy[id];for(const [k,v]of Object.entries(fx)){if(['atk','def','hp'].includes(k))continue;out[k]=(out[k]||0)+v;}if(legacy)for(const k of ['atk','def','hp'])out[k]=(out[k]||0)+(fx[k]-(it.base[k]||0));}for(const [k,max]of Object.entries(D.config.caps))out[k]=Math.min(max,Math.max(0,out[k]||0));return out;}
 function canBuy(baseId,quality){const t=D.templates[baseId];return !!t&&(t.type==='gem'?t.tier<=4:Number.isInteger(quality)&&quality>=0&&quality<=2&&t.rarity<=2);}
 function price(baseId,quality=0){const t=D.templates[baseId];return t.type==='gem'?t.price:Math.round((35+(t.level||1)*25)*(1+quality*1.4)*(1+((D.qualities[quality]?.affixes[1]||1)*.12)));}
 function currency(baseId){return ['pet','treasure'].includes(D.templates[baseId]?.type)?'jade':'stones';}
 function quote(baseId,quality=0){const value=price(baseId,quality);return currency(baseId)==='jade'?Math.max(1,Math.ceil(value/50)):value;}
 function exchange(p,n){if(!Number.isSafeInteger(n)||n<1||n>Math.floor(p.stones/10000)||!Number.isSafeInteger((p.jade||0)+n))return {ok:false};p.stones-=n*10000;p.jade=(p.jade||0)+n;return {ok:true,count:n,cost:n*10000};}
 function buyMany(p,id,q,n,r=Math.random){if(!Number.isSafeInteger(n)||n<1||n>100||!canBuy(id,q))return {ok:false,reason:'quantity'};const field=currency(id),cost=quote(id,q)*n;if((p[field]||0)<cost)return {ok:false,reason:'funds'};normalize(p);const t=D.templates[id];if(t.type!=='gem'){const cat=t.type==='equip'?'equipment':t.type==='pet'?'pets':'treasures';if(stored(p,t.type)+n>(p.bag?.capacities?.[cat]||100))return {ok:false,reason:'full'};}const snapshot=JSON.stringify(p),ids=[];for(let i=0;i<n;i++){const result=buy(p,id,q,r);if(!result.ok){Object.assign(p,JSON.parse(snapshot));return result;}if(result.id)ids.push(result.id);}return {ok:true,cost,currency:field,count:n,ids};}
 function buy(p,baseId,quality,r=Math.random){const t=D.templates[baseId];if(!canBuy(baseId,quality))return {ok:false,reason:'restricted'};normalize(p);const field=currency(baseId),cost=quote(baseId,quality);if((p[field]||0)<cost)return {ok:false,reason:'funds'};if(t.type==='gem'){if(!addStack(p,baseId,1))return {ok:false,reason:'full'};}else{const cat=t.type==='equip'?'equipment':t.type==='pet'?'pets':'treasures';if(stored(p,t.type)>=(p.bag?.capacities?.[cat]||100))return {ok:false,reason:'full'};const item=create(p,baseId,quality,'萬寶閣',r);grant(p,item);p[field]-=cost;return {ok:true,cost,id:item.id,currency:field};}p[field]-=cost;return {ok:true,cost,currency:field};}
 function addStack(p,id,n){const entry=p.inventory.find(x=>x.id===id);if(entry){if(!Number.isSafeInteger(entry.count+n))return false;entry.count+=n;return true;}const count=p.inventory.filter(x=>D.templates[x.id]?.type==='gem'||(!p.economy?.instances[x.id]&&!['pill','heal','trib','sword','robe','crown','boots','ring','earrings','inner','legs','necklace','bracelet','jadeSword','starRobe','belt','charm'].includes(x.id))).length;if(count>=(p.bag?.capacities?.materials||100))return false;p.inventory.push({id,count:n});return true;}
 function take(p,id,n){const e=p.inventory.find(x=>x.id===id);if(!Number.isSafeInteger(n)||n<1||!e||e.count<n)return false;e.count-=n;if(!e.count)p.inventory.splice(p.inventory.indexOf(e),1);return true;}
 function forgeCost(it){return {stones:Math.round(35*(it.enhancement+1)*(it.quality+1)),material:1+Math.floor(it.enhancement/3),chance:Math.max(D.config.enhance.minimumChance,1-it.enhancement*.045)};}
 function enhance(p,id,r=Math.random){const it=p.economy?.instances[id];if(!it||!held(p,id)||it.enhancement>=15)return {ok:false,reason:'item'};const cost=forgeCost(it);if(p.stones<cost.stones||!take(p,'forgeDust',cost.material))return {ok:false,reason:'funds'};p.stones-=cost.stones;const success=roll(r)<cost.chance;if(success)it.enhancement++;p.economy.forgeLog.push({id,level:it.enhancement,success,cost,at:Date.now()});return {ok:true,success};}
 function socket(p,id,index,gem){const it=p.economy?.instances[id];if(!it||!held(p,id)||!Number.isInteger(index)||index<0||index>=it.sockets.length||(gem!==null&&D.templates[gem]?.type!=='gem'))return false;const old=it.sockets[index];if(old===gem)return false;const snapshot=p.inventory.map(x=>({...x}));if(gem!==null&&!take(p,gem,1))return false;if(old&&!addStack(p,old,1)){p.inventory=snapshot;return false;}it.sockets[index]=gem;return true;}
 function fuse(p,id,r=Math.random){const t=D.templates[id];if(t?.type==='gem'&&t.tier<6){const n=D.config.fusion.gemCopies,next='gem_'+t.kind+'_'+(t.tier+1),snapshot=p.inventory.map(x=>({...x}));if(p.stones<50*t.tier||!take(p,id,n))return false;if(!addStack(p,next,1)){p.inventory=snapshot;return false;}p.stones-=50*t.tier;return true;}return false;}
 function synthesize(p,ids,r=Math.random){const forge=typeof LegendForge!=='undefined'?LegendForge:require('./legend-forge.js'),result=forge.attempt(p,ids,0,r);return result.ok&&result.success?result.item:false;}
 function encounterQuality(kind,r=Math.random){if(roll(r)>=(D.config.encounters[kind]??.04))return null;return roll(r)<D.config.highWeights.legendary?4:3;}
 function bossQualities(kind,r=Math.random){const c=D.config.boss[kind]||D.config.boss.normal,out=[];if(roll(r)<c.gold)out.push(3);if(roll(r)<c.legendary)out.push(4);return out;}
 function reward(p,key,kind,level='ordinary',r=Math.random,worldId=null){normalize(p);if(p.economy.claims[key])return {ok:false};p.economy.claims[key]={kind,at:Date.now()};const qualities=kind==='boss'?bossQualities(level,r):[encounterQuality(level,r)].filter(x=>x!==null);const world=kind==='boss'?D.config.worlds.find(w=>w.id===worldId):null,dropPool=world?.dropPool;const pool=Object.values(D.templates).filter(t=>['equip','treasure','pet'].includes(t.type)&&!t.legendOnly&&t.realm<=p.realm&&(!dropPool||(t.type==='equip'?dropPool.slots.includes(t.slot):dropPool[t.type==='pet'?'pets':'treasures'].some(i=>t.id===t.type+'_'+i))));const rewards=[];for(const q of qualities){const t=pick(pool,r),item=create(p,t.id,q,kind+':'+key,r);grant(p,item);rewards.push(item.id);}const dust=kind==='boss'?5:1;if(!addStack(p,'forgeDust',dust))p.economy.mail.push({id:'forgeDust',count:dust});if(kind==='boss'){const tier=level==='ancient'?6:level==='world'?5:4;const g='gem_'+(dropPool?pick(dropPool.gems,r):pick(D.gemTypes,r)[0])+'_'+tier;if(!addStack(p,g,1))p.economy.mail.push({id:g,count:1});}p.economy.drops.push({key,kind,level,worldId,rewards,at:Date.now()});return {ok:true,rewards};}
 function recover(p){normalize(p);let n=0;for(const entry of p.economy.mail.slice()){if(entry&&typeof entry==='object'&&entry.companion){const type=entry.companion,cat=type==='pet'?'pets':'treasures';if(stored(p,type)>=(p.bag?.capacities?.[cat]||100))continue;if(type==='pet')p.levelPet[entry.id]=entry.level||1;else if(!p.ownedTreasures.includes(entry.id))p.ownedTreasures.push(entry.id);}else if(typeof entry==='string'){const i=p.economy.instances[entry],t=i&&(D.templates[i.baseId]||i.template);if(!t)continue;const cat=t.type==='pet'?'pets':t.type==='treasure'?'treasures':'equipment';if(stored(p,t.type)>=(p.bag?.capacities?.[cat]||100))continue;grant(p,i);}else {const progression=typeof Progression!=='undefined'?Progression:require('./progression.js');if(!progression.addItem(p,entry.id,entry.count))continue;}p.economy.mail.splice(p.economy.mail.indexOf(entry),1);n++;}return n;}
 function convertLegacy(p,id,catalog){const t=catalog[id];if(!t||!['equip','treasure'].includes(t.type))return null;normalize(p);const slot=Object.keys(p.equipment).find(k=>p.equipment[k]===id),index=p.ownedTreasures.indexOf(id);if(!slot&&index<0&&!p.inventory.some(x=>x.id===id&&x.count>0))return null;let uid;do{uid='xi_'+(++p.economy.sequence);}while(p.economy.instances[uid]);const it={id:uid,baseId:id,template:{...t,icon:undefined},locked:!!p.bag?.locked?.[id],quality:t.rarity||0,level:1,base:{atk:t.atk||0,def:t.def||0,hp:t.hp||0},affixes:[],enhancement:0,sockets:[],source:'舊物單件實例化，原屬性保留',realm:t.realm||0,growth:1,cultivation:0,evolution:0};
 if(slot)p.equipment[slot]=uid;else if(index>=0){p.ownedTreasures[index]=uid;if(p.activeTreasure===id)p.activeTreasure=uid;const load=p.economy.loadout.treasures;p.economy.loadout.treasures=load.map(k=>k===id?uid:k);if(p.companions){for(const field of ['order','deployed'])p.companions[field]=p.companions[field].map(k=>k==='treasure:'+id?'treasure:'+uid:k);const old=p.companions.cooldowns['treasure:'+id];if(old)p.companions.cooldowns['treasure:'+uid]=old;}}else{take(p,id,1);p.inventory.push({id:uid,count:1});}p.economy.instances[uid]=it;return it;
 }
 return {normalize,create,legacy,convertLegacy,effects,bonuses,grant,held,stored,buy,buyMany,currency,quote,exchange,canBuy,price,addStack,take,forgeCost,enhance,socket,fuse,synthesize,encounterQuality,bossQualities,reward,recover};
})();
if(typeof module!=='undefined')module.exports=Economy;
