'use strict';
const Forgemaster=(()=>{
 const D=typeof HighRealmData!=='undefined'?HighRealmData:require('../data/high-realms.js');
 const ED=typeof EconomyData!=='undefined'?EconomyData:require('../data/economy.js');
 const E=typeof Economy!=='undefined'?Economy:require('./economy.js');
 const F=typeof ForgeAffixes!=='undefined'?ForgeAffixes:require('../data/forge-affixes.js');
 const config={discount:[.50,.55,.60,.65,.70],boost:[.15,.175,.20,.225,.25],success:[.85,.875,.90,.925,.95],legend:[.15,.175,.20,.225,.25],recipe:{stones:10000,material:60,ore:12}};
 function service(p,npcId,map){const npc=D.npcs.find(n=>n.id===npcId);if(D.maps[p.mapIndex-5]?.id!==map?.id||!npc||!npc.role.includes('鍛造')||!map?.highRealm||map.theme!==npc.theme||p.realm<map.level||p.realm<npc.realm||(map.finished&&!p.finished)||!p.position||Math.hypot(p.position.x-npc.x,p.position.y-npc.y)>=100)return null;const i=Math.min(4,Math.max(0,npc.realm-4));return {npc,discount:config.discount[i],boost:config.boost[i],success:config.success[i],legend:config.legend[i]};}
 function discount(cost,s){const out={...cost};for(const key of ['stones','material','ore'])out[key]=Math.ceil(cost[key]*(1-s.discount)-1e-9);return out;}
 function quote(p,npcId,map,id){const s=service(p,npcId,map),item=p.economy?.instances[id],t=item&&(ED.templates[item.baseId]||item.template);if(!s||!item||!E.held(p,id)||!['equip','treasure'].includes(t?.type)||p.realm<item.realm)return {ok:false,reason:'請靠近本境鍛造師並選擇可使用的裝備或法寶'};const original=E.forgeCost(item),cost=discount(original,s);cost.chance=Math.min(1,original.chance+s.boost);return {ok:true,item,service:s,original,cost};}
 function affordable(p,c){return p.stones>=c.stones&&['forgeDust','celestialOre'].every((id,i)=>p.inventory.filter(e=>e.id===id).reduce((n,e)=>n+e.count,0)>=c[i?'ore':'material']);}
 function charge(p,c){p.stones-=c.stones;for(const [id,n]of [['forgeDust',c.material],['celestialOre',c.ore]]){let left=n;while(left>0){const part=Math.min(left,p.inventory.find(e=>e.id===id).count);E.take(p,id,part);left-=part;}}}
 function upgrade(p,npcId,map,id,random=Math.random){const q=quote(p,npcId,map,id);if(!q.ok)return q;if(q.item.enhancement>=q.cost.cap)return {ok:false,reason:'已達品階強化上限'};if(!affordable(p,q.cost))return {ok:false,reason:'靈石、鍛造石或天鑄玄晶不足'};const draw=random();if(!Number.isFinite(draw)||draw<0||draw>=1)return {ok:false,reason:'亂數異常，未扣除資源'};charge(p,q.cost);const success=draw<q.cost.chance;if(success)q.item.enhancement++;const unlocked=success?F.unlock(q.item):[];p.economy.forgeLog.push({id,level:q.item.enhancement,success,cost:q.cost,npcId,at:Date.now()});return {ok:true,success,cost:q.cost,unlocked};}
 function estimate(p,npcId,map,id,target){const q=quote(p,npcId,map,id);if(!q.ok||!Number.isInteger(target)||target<=q.item.enhancement||target>q.cost.cap)return {ok:false};const minimum={stones:0,material:0,ore:0},expected={...minimum};for(let level=q.item.enhancement;level<target;level++){const c=discount(E.forgeCost({...q.item,enhancement:level}),q.service),chance=Math.min(1,c.chance+q.service.boost);for(const key of Object.keys(minimum)){minimum[key]+=c[key];expected[key]+=c[key]/chance;}}for(const key of Object.keys(expected))expected[key]=Math.ceil(expected[key]-1e-9);return {ok:true,minimum,expected};}
 function upgradeTo(p,npcId,map,id,target,random=Math.random){const plan=estimate(p,npcId,map,id,target);if(!plan.ok)return {ok:false,reason:'目標等級或服務狀態無效'};const before=p.economy.instances[id].enhancement,spent={stones:0,material:0,ore:0};let attempts=0,successes=0,reason='已達目標';while(p.economy.instances[id].enhancement<target&&attempts<10000){const r=upgrade(p,npcId,map,id,random);if(!r.ok){reason=r.reason;break;}attempts++;successes+=Number(r.success);for(const k of Object.keys(spent))spent[k]+=r.cost[k];}if(attempts===10000)reason='達到本批安全上限';return {ok:attempts>0,before,after:p.economy.instances[id].enhancement,attempts,successes,spent,reason};}
 function templates(p,npcId,map,type){const s=service(p,npcId,map);return s?Object.values(ED.templates).filter(t=>t.type===type&&['equip','treasure'].includes(type)&&!t.legendOnly&&(t.realm||0)<=Math.min(p.realm,s.npc.realm)):[];}
 function craftQuote(p,npcId,map,baseId){const s=service(p,npcId,map),t=ED.templates[baseId];if(!s||!t||!templates(p,npcId,map,t.type).some(x=>x.id===baseId))return {ok:false,reason:'鍛造師無法打造此物品'};const factor=1+(s.npc.realm-4)*.5,original=Object.fromEntries(Object.entries(config.recipe).map(([k,v])=>[k,Math.round(v*factor)]));return {ok:true,service:s,template:t,original,cost:discount(original,s)};}
 function craft(p,npcId,map,baseId,random=Math.random){const q=craftQuote(p,npcId,map,baseId);if(!q.ok)return q;E.normalize(p);if(!affordable(p,q.cost))return {ok:false,reason:'靈石、鍛造石或天鑄玄晶不足'};const draw=random();if(!Number.isFinite(draw)||draw<0||draw>=1)return {ok:false,reason:'亂數異常，未扣除資源'};const success=draw<q.service.success,quality=draw<q.service.legend?4:3;let item=null;if(success){item=E.create(p,baseId,quality,q.service.npc.name+'委託打造',random);item.realm=q.service.npc.realm;if(q.template.type==='equip')for(const k of ['atk','def','hp'])item.base[k]*=4**Math.max(0,item.realm-3);}charge(p,q.cost);if(item)E.grant(p,item);p.economy.masterForgeLog=[...(p.economy.masterForgeLog||[]),{npcId,baseId,success,result:item?.id||null,quality:item?.quality??null,cost:q.cost,at:Date.now()}];return {ok:true,success,item,cost:q.cost};}
 return {config,service,quote,upgrade,estimate,upgradeTo,templates,craftQuote,craft};
})();
if(typeof module!=='undefined')module.exports=Forgemaster;
