'use strict';
const HighRealms=(()=>{
 const D=typeof HighRealmData!=='undefined'?HighRealmData:require('../data/high-realms.js'),E=typeof Economy!=='undefined'?Economy:require('./economy.js');
 function normalize(p){const v=p.highRealms||{},hadSlots=!!v.slots;const defaults={version:1,slots:Array(8).fill(null),auto:{},cooldowns:{},claims:{},spawnSequence:0};for(const [key,value] of Object.entries(defaults))if(v[key]===undefined)v[key]=value;p.highRealms=v;const h=v;if(!hadSlots)h.slots=['attack','flame','sword','heal',null,null,null,null];h.slots=Array.from({length:8},(_,i)=>h.slots[i]||null);p.skills=p.skills||{};return h;}
 function canEnter(p,map){return !!map&&p.realm>=map.level&&(!map.finished||p.finished);}
 function skill(id){return D.skills.find(s=>s.id===id);}
 function learned(p,id){return id==='attack'||(['flame','sword','heal'].includes(id)?(p.skills[id]||0)>0:!!skill(id)&&(p.skills[id]||0)>0);}
 function assign(p,slot,id){const h=normalize(p);if(!Number.isInteger(slot)||slot<0||slot>7||(id&&!learned(p,id)))return false;const old=h.slots.indexOf(id);if(id&&old>=0&&old!==slot)h.slots[old]=h.slots[slot];h.slots[slot]=id||null;return true;}
 function learn(p,book){const s=D.skills.find(s=>s.bookId===book);if(!s||p.realm<s.realm)return {ok:false,reason:'境界不足'};if(p.skills[s.id])return {ok:false,reason:'已學會，重複技能書保留於背包'};if(!E.take(p,book,1))return {ok:false,reason:'技能書不足'};p.skills[s.id]=1;normalize(p);return {ok:true,skill:s};}
 function give(p,id,count){if(!E.addStack(p,id,count))p.economy.mail.push({id,count,source:'高階探索'});}
 function reward(p,enemy,r=Math.random){E.normalize(p);const h=normalize(p),key=enemy.claimId;if(!key||h.claims[key])return {ok:false};const table=D.drops[enemy.role]||D.drops.normal,values=Array.from({length:30},()=>r());if(values.some(n=>!Number.isFinite(n)||n<0||n>=1))return {ok:false};h.claims[key]=true;const rewards=[],ids=[];const add=(id,count)=>{give(p,id,count);rewards.push({id,count});};const level=enemy.realm,theme=Math.min(5,Math.max(0,level-4));add('v21_mat_'+Math.min(8,theme),table.material);if(values[0]<table.gem){const type=EData().gemTypes[Math.floor(values[1]*12)][0],tier=table.gemTierMin+Math.floor(values[2]*(table.gemTierMax-table.gemTierMin+1));add('gem_'+type+'_'+tier,table.gemCount);}add('celestialOre',table.ore);if(values[17]<table.extraMaterialChance)add('v21_mat_'+(6+Math.floor(values[18]*3)),table.extraMaterialCount);
 const create=(type,quality,at)=>{const pool=type==='equip'?Object.values(EData().templates).filter(t=>t.type==='equip'&&!t.legendOnly):D.templates.filter(t=>t.type===type&&t.realm<=level&&t.realm>=Math.max(4,level-1));if(!pool.length)return;const t=pool[Math.floor(values[at]*pool.length)],it=E.create(p,t.id,quality,'高階'+enemy.role+':'+key,r);it.realm=level;if(type==='equip'){const scale=4**Math.max(0,level-3);for(const k of ['atk','def','hp'])it.base[k]*=scale;}E.grant(p,it);ids.push(it.id);};
 if(values[3]<table.gear)create(values[4]<table.equipmentShare?'equip':'treasure',table.minQuality,5);if(values[6]<table.gold)create('equip',3,7);if(values[8]<table.legend)create('treasure',4,9);if(values[10]<table.pet)create('pet',values[11]<table.petLegend?4:table.minQuality,12);if(values[13]<table.treasure)create('treasure',table.minQuality,14);if(values[15]<table.book){const pool=D.skills.filter(s=>s.realm<=level&&s.realm>=Math.max(4,level-1));add(pool[Math.floor(values[16]*pool.length)].bookId,table.bookCount);}p.economy.drops.push({key,kind:'highRealm',level:enemy.role,rewards:ids,items:rewards,at:Date.now()});return {ok:true,ids,rewards};
 }
 function EData(){return typeof EconomyData!=='undefined'?EconomyData:require('../data/economy.js');}
 function targets(list,origin,radius,max){return list.filter(e=>e.hp>0&&Math.hypot(e.x-origin.x,e.y-origin.y)<=radius).sort((a,b)=>Math.hypot(a.x-origin.x,a.y-origin.y)-Math.hypot(b.x-origin.x,b.y-origin.y)).slice(0,max);}
 function ready(p,id,now,stats){const h=normalize(p),s=skill(id);return !!s&&learned(p,id)&&p.mp>=s.cost&&now>=(h.cooldowns[id]||0)&&now>=(h.silencedUntil||0);}
 function autoEligible(p,s,stats,nearby){const cfg=p.highRealms.auto[s.id]||{},mode=s.mode;if(cfg.enabled===false)return false;if(['heal','revive','restore','cleanse'].includes(mode))return p.hp<stats.hp*(cfg.hpThreshold||.55);if(mode==='mana')return p.mp<stats.mp*(cfg.mpThreshold||.45);if(['aoe','multi','chain','meteor','burn','slow','silence'].includes(mode))return nearby>=(cfg.minTargets||2);return nearby>0;}
 return {normalize,canEnter,skill,learned,assign,learn,give,reward,targets,ready,autoEligible};
})();
if(typeof module!=='undefined')module.exports=HighRealms;
