'use strict';
const LegendForge=(()=>{
 const E=typeof Economy!=='undefined'?Economy:require('./economy.js'),D=typeof EconomyData!=='undefined'?EconomyData:require('../data/economy.js');
 const config={stones:3000,baseChance:.45,oreBonus:.10,maxOre:5,maxChance:.95,duration:3000,drops:{early:.01,nascent:.06,perRealm:.03,cap:.24,rift:.15,boss:.55}};
 const count=(p,id)=>p.inventory.filter(e=>e.id===id).reduce((n,e)=>n+e.count,0);
 function eligible(p,id){const it=p.economy?.instances[id],t=it&&(D.templates[it.baseId]||it.template);return !!(it&&D.templates[it.baseId]&&t.type==='equip'&&it.quality===3&&count(p,id)===1&&!Object.values(p.equipment).includes(id)&&!p.bag?.locked?.[id]&&!it.locked&&!it.enhancement&&!it.sockets.some(Boolean));}
 function quote(p,ids,ore=0){const chance=Math.min(config.maxChance,config.baseChance+ore*config.oreBonus);let reason='';if(ids.length!==3||new Set(ids).size!==3||ids.some(id=>!eligible(p,id)))reason='請放入三件不同、未鎖定、未穿戴、未強化及未鑲嵌的金品裝備';else if(!Number.isInteger(ore)||ore<0||ore>config.maxOre||count(p,'celestialOre')<ore)reason='特殊礦石數量不足或超出上限';else if(p.stones<config.stones)reason='靈石不足，需要 3,000 靈石';return {ok:!reason,reason,chance};}
 function attempt(p,ids,ore=0,random=Math.random){const q=quote(p,ids,ore);if(!q.ok)return q;const roll=random();if(!Number.isFinite(roll)||roll<0||roll>=1)return {ok:false,reason:'亂數來源異常，沒有消耗材料'};const baseId=p.economy.instances[ids[0]].baseId,success=roll<q.chance;p.stones-=config.stones;for(let remaining=ore;remaining>0;){const n=Math.min(remaining,p.inventory.find(e=>e.id==='celestialOre').count);E.take(p,'celestialOre',n);remaining-=n;}let item=null;if(success){ids.forEach(id=>E.take(p,id,1));item=E.create(p,baseId,4,'三金合傳說',random);E.grant(p,item);}const record={id:'legend-forge:'+((p.economy.synthesisSequence||0)+1),ids:[...ids],ore,chance:q.chance,success,result:item?.id||null,at:Date.now()};p.economy.synthesisSequence=(p.economy.synthesisSequence||0)+1;p.economy.synthesisLog=[...(p.economy.synthesisLog||[]),record];return {ok:true,success,item,record,chance:q.chance};}
 function dropChance(level,rift=false,boss=false){return boss&&rift?config.drops.boss:rift?config.drops.rift:level>=3?Math.min(config.drops.cap,config.drops.nascent+(level-3)*config.drops.perRealm):config.drops.early;}
 function drop(p,key,level,rift=false,boss=false,random=Math.random){E.normalize(p);const receipt='celestial-ore:'+key;if(p.economy.claims[receipt])return {ok:false,count:0};const roll=random();if(!Number.isFinite(roll)||roll<0||roll>=1)return {ok:false,count:0};p.economy.claims[receipt]={at:Date.now(),kind:'ore'};const n=roll<dropChance(level,rift,boss)?(rift&&boss?2:1):0;if(n&&!E.addStack(p,'celestialOre',n))p.economy.mail.push({id:'celestialOre',count:n,source:'妖獸特殊礦石'});return {ok:true,count:n};}
 return {config,eligible,quote,attempt,dropChance,drop};
})();
if(typeof module!=='undefined')module.exports=LegendForge;
